Домашнее задание

ДЗ №5 «Нейросетевые модели»

Цель:

Студенты учатся использовать нейронные сети в моделях торговой стратегии.

Результат - построена модель с использованием нейронных сетей.


Описание/Пошаговая инструкция выполнения домашнего задания:
- включить в модель нейросетевые модели;
- добавить анализ временных рядов;
- построить оценку качетсва модели.

In [ ]:
#!pip install pandas numpy TA-Lib-Precompiled scikit-learn hyperopt plotly backtesting backtrader
#!pip install matplotlib requests_cache
!pip install TA-Lib
#!pip install yfinance_cache
#!pip install fmp_python
#!pip install outlier_utils
!pip install mplfinance
!pip install catboost

Requirement already satisfied: TA-Lib in /usr/local/lib/python3.12/dist-packages (0.6.8)
Requirement already satisfied: build in /usr/local/lib/python3.12/dist-packages (from TA-Lib) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from TA-Lib) (2.0.2)
Requirement already satisfied: packaging>=24.0 in /usr/local/lib/python3.12/dist-packages (from build->TA-Lib) (25.0)
Requirement already satisfied: pyproject_hooks in /usr/local/lib/python3.12/dist-packages (from build->TA-Lib) (1.2.0)
Requirement already satisfied: mplfinance in /usr/local/lib/python3.12/dist-packages (0.12.10b0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from mplfinance) (3.10.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from mplfinance) (2.2.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->mplfinance) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->mplfinance) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->mplfinance) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->mplfinance) (1.4.9)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.12/dist-packages (from matplotlib->mplfinance) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->mplfinance) (25.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->mplfinance) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->mplfinance) (3.3.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib->mplfinance) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->mplfinance) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->mplfinance) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib->mplfinance) (1.17.0)
Requirement already satisfied: catboost in /usr/local/lib/python3.12/dist-packages (1.2.8)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->catboost) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (25.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.2)

In [ ]:

import torch
from scipy.spatial.distance import cosine
from transformers import AutoModel, AutoTokenizer
import gradio as gr

!pip3 install chronos-forecasting
#####!pip3 install git+https://github.com/amazon-science/chronos-forecasting.git
!pip3 install torchmetrics

from chronos import BaseChronosPipeline, Chronos2Pipeline
from torchmetrics.classification import BinaryAUROC

Requirement already satisfied: chronos-forecasting in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: accelerate<2,>=0.34 in /usr/local/lib/python3.12/dist-packages (from chronos-forecasting) (1.12.0)
Requirement already satisfied: einops<1,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from chronos-forecasting) (0.8.1)
Requirement already satisfied: numpy<3,>=1.21 in /usr/local/lib/python3.12/dist-packages (from chronos-forecasting) (2.0.2)
Requirement already satisfied: scikit-learn<2,>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from chronos-forecasting) (1.6.1)
Requirement already satisfied: torch<3,>=2.2 in /usr/local/lib/python3.12/dist-packages (from chronos-forecasting) (2.9.0+cpu)
Requirement already satisfied: transformers<5,>=4.41 in /usr/local/lib/python3.12/dist-packages (from chronos-forecasting) (4.57.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from accelerate<2,>=0.34->chronos-forecasting) (25.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate<2,>=0.34->chronos-forecasting) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from accelerate<2,>=0.34->chronos-forecasting) (6.0.3)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from accelerate<2,>=0.34->chronos-forecasting) (0.36.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate<2,>=0.34->chronos-forecasting) (0.7.0)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2,>=1.6.0->chronos-forecasting) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2,>=1.6.0->chronos-forecasting) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2,>=1.6.0->chronos-forecasting) (3.6.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.2->chronos-forecasting) (3.20.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.2->chronos-forecasting) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.2->chronos-forecasting) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.2->chronos-forecasting) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.2->chronos-forecasting) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.2->chronos-forecasting) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.2->chronos-forecasting) (2025.3.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<5,>=4.41->chronos-forecasting) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers<5,>=4.41->chronos-forecasting) (2.32.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<5,>=4.41->chronos-forecasting) (0.22.2)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers<5,>=4.41->chronos-forecasting) (4.67.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate<2,>=0.34->chronos-forecasting) (1.2.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch<3,>=2.2->chronos-forecasting) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch<3,>=2.2->chronos-forecasting) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers<5,>=4.41->chronos-forecasting) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers<5,>=4.41->chronos-forecasting) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers<5,>=4.41->chronos-forecasting) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers<5,>=4.41->chronos-forecasting) (2026.1.4)
Requirement already satisfied: torchmetrics in /usr/local/lib/python3.12/dist-packages (1.8.2)
Requirement already satisfied: numpy>1.20.0 in /usr/local/lib/python3.12/dist-packages (from torchmetrics) (2.0.2)
Requirement already satisfied: packaging>17.1 in /usr/local/lib/python3.12/dist-packages (from torchmetrics) (25.0)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from torchmetrics) (2.9.0+cpu)
Requirement already satisfied: lightning-utilities>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from torchmetrics) (0.15.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from lightning-utilities>=0.8.0->torchmetrics) (75.2.0)
Requirement already satisfied: typing_extensions in /usr/local/lib/python3.12/dist-packages (from lightning-utilities>=0.8.0->torchmetrics) (4.15.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->torchmetrics) (3.20.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->torchmetrics) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->torchmetrics) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->torchmetrics) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->torchmetrics) (2025.3.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->torchmetrics) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->torchmetrics) (3.0.3)

WARNING:torchao.kernel.intmm:Warning: Detected no triton, on systems without Triton certain kernels will not work

In [ ]:
!pip3 install backtesting
!pip3 install bokeh==3.8.1

Requirement already satisfied: backtesting in /usr/local/lib/python3.12/dist-packages (0.6.5)
Requirement already satisfied: numpy>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from backtesting) (2.0.2)
Requirement already satisfied: pandas!=0.25.0,>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from backtesting) (2.2.2)
Requirement already satisfied: bokeh!=3.0.*,!=3.2.*,>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from backtesting) (3.8.1)
Requirement already satisfied: Jinja2>=2.9 in /usr/local/lib/python3.12/dist-packages (from bokeh!=3.0.*,!=3.2.*,>=3.0.0->backtesting) (3.1.6)
Requirement already satisfied: contourpy>=1.2 in /usr/local/lib/python3.12/dist-packages (from bokeh!=3.0.*,!=3.2.*,>=3.0.0->backtesting) (1.3.3)
Requirement already satisfied: narwhals>=1.13 in /usr/local/lib/python3.12/dist-packages (from bokeh!=3.0.*,!=3.2.*,>=3.0.0->backtesting) (2.15.0)
Requirement already satisfied: packaging>=16.8 in /usr/local/lib/python3.12/dist-packages (from bokeh!=3.0.*,!=3.2.*,>=3.0.0->backtesting) (25.0)
Requirement already satisfied: pillow>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from bokeh!=3.0.*,!=3.2.*,>=3.0.0->backtesting) (11.3.0)
Requirement already satisfied: PyYAML>=3.10 in /usr/local/lib/python3.12/dist-packages (from bokeh!=3.0.*,!=3.2.*,>=3.0.0->backtesting) (6.0.3)
Requirement already satisfied: tornado>=6.2 in /usr/local/lib/python3.12/dist-packages (from bokeh!=3.0.*,!=3.2.*,>=3.0.0->backtesting) (6.5.1)
Requirement already satisfied: xyzservices>=2021.09.1 in /usr/local/lib/python3.12/dist-packages (from bokeh!=3.0.*,!=3.2.*,>=3.0.0->backtesting) (2025.11.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas!=0.25.0,>=0.25.0->backtesting) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas!=0.25.0,>=0.25.0->backtesting) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas!=0.25.0,>=0.25.0->backtesting) (2025.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from Jinja2>=2.9->bokeh!=3.0.*,!=3.2.*,>=3.0.0->backtesting) (3.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas!=0.25.0,>=0.25.0->backtesting) (1.17.0)
Requirement already satisfied: bokeh==3.8.1 in /usr/local/lib/python3.12/dist-packages (3.8.1)
Requirement already satisfied: Jinja2>=2.9 in /usr/local/lib/python3.12/dist-packages (from bokeh==3.8.1) (3.1.6)
Requirement already satisfied: contourpy>=1.2 in /usr/local/lib/python3.12/dist-packages (from bokeh==3.8.1) (1.3.3)
Requirement already satisfied: narwhals>=1.13 in /usr/local/lib/python3.12/dist-packages (from bokeh==3.8.1) (2.15.0)
Requirement already satisfied: numpy>=1.16 in /usr/local/lib/python3.12/dist-packages (from bokeh==3.8.1) (2.0.2)
Requirement already satisfied: packaging>=16.8 in /usr/local/lib/python3.12/dist-packages (from bokeh==3.8.1) (25.0)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.12/dist-packages (from bokeh==3.8.1) (2.2.2)
Requirement already satisfied: pillow>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from bokeh==3.8.1) (11.3.0)
Requirement already satisfied: PyYAML>=3.10 in /usr/local/lib/python3.12/dist-packages (from bokeh==3.8.1) (6.0.3)
Requirement already satisfied: tornado>=6.2 in /usr/local/lib/python3.12/dist-packages (from bokeh==3.8.1) (6.5.1)
Requirement already satisfied: xyzservices>=2021.09.1 in /usr/local/lib/python3.12/dist-packages (from bokeh==3.8.1) (2025.11.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from Jinja2>=2.9->bokeh==3.8.1) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->bokeh==3.8.1) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->bokeh==3.8.1) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->bokeh==3.8.1) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.2->bokeh==3.8.1) (1.17.0)

In [ ]:
import backtesting
from backtesting import Backtest, Strategy

import bokeh
print(bokeh.__version__)
from backtesting import set_bokeh_output
set_bokeh_output(notebook=True)
backtesting.set_bokeh_output(notebook=True)
if 'google.colab' in str(get_ipython()):
    get_ipython().run_line_magic('matplotlib', 'inline')

3.8.1

/usr/local/lib/python3.12/dist-packages/backtesting/_plotting.py:55: UserWarning: Jupyter Notebook detected. Setting Bokeh output to notebook. This may not work in Jupyter clients without JavaScript support, such as old IDEs. Reset with `backtesting.set_bokeh_output(notebook=False)`.
  warnings.warn('Jupyter Notebook detected. '

In [ ]:
from sklearn.metrics import roc_auc_score, roc_curve
import matplotlib.pyplot as plt

In [ ]:
import pandas as pd
import numpy as np
import re
import os

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectKBest, f_classif

import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.express as px
import matplotlib.pyplot as plt

import yfinance as yf
import talib as ta
from hyperopt import fmin, tpe, hp, Trials, STATUS_OK
import joblib

from datetime import datetime
import matplotlib.pyplot as plt
import seaborn as sns

from scipy.stats import skew, kurtosis
from statsmodels.tsa.seasonal import STL
import pywt
import mplfinance as mpf
from scipy.fft import fft
from IPython.display import display

In [ ]:
#Машинное обучение
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score, roc_curve, precision_recall_curve
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

Добавляем библиотеки для нейросетевой модели

In [ ]:
import torch.nn as nn
import torch
from torch.utils.data import TensorDataset, DataLoader

from transformers import PatchTSMixerConfig, PatchTSMixerForPrediction

In [ ]:
# backtesting
# -----------------------
class ChronosNextDayDirection(Strategy):
    def init(self):
        # backtesting.py позволяет обращаться к колонкам как self.data.<Name>
        pass

    def next(self):
        sig = int(self.data.Signal[-1])

        # если сигнала нет — выходим в кэш
        if sig == 0:
            if self.position:
                self.position.close()
            return

        # long
        if sig == 1:
            if self.position.is_short:
                self.position.close()
            if not self.position:
                self.buy()

        # short
        if sig == -1:
            if self.position.is_long:
                self.position.close()
            if not self.position:
                self.sell()

In [ ]:
class ChronosStrategy(Strategy):
    def init(self):
        # backtesting.py позволяет обращаться к колонкам как self.data.<Name>
        pass

    def next(self):
        sig = int(self.data.Signal[-1])

        if sig == 0:
            if self.position:
                self.position.close()
            return

        if sig == 1:
            if self.position.is_short:
                self.position.close()
            if not self.position:
                self.buy()

        if sig == -1:
            if self.position.is_long:
                self.position.close()
            if not self.position:
                self.sell()

In [ ]:
class BuyHold(Strategy):
    def init(self):
        # backtesting.py позволяет обращаться к колонкам как self.data.<Name>
        pass

    def next(self):
        if not self.position:
            self.buy()

In [ ]:
def backtestWithChronos(strategy, data, test_data, action=None, instrument=None) :
  print("Обрабатываем данные для модели Chronos... -> ")
  print("=" * 50)

  device_map = "cuda" if torch.cuda.is_available() else "cpu"
  train_data_neu = data.copy()
  test_data_neu = test_data.copy()
  if instrument is not None :
      strategy_instrument = instrument
  if strategy.ticker is not None:
      strategy_instrument = strategy.ticker

  def preprocess_data(df_raw, strategy_instance):
      """Единая функция для обработки train или test данных."""
      df = df_raw.copy()
      # Генерация сигналов
      signals, conditions, datadf = strategy_instance.generate_signals(df)
      if 'Signal' in conditions.columns:
          conditions.drop('Signal', axis=1, inplace=True)
      conditions.columns = conditions.columns.str.capitalize()
      df_signals = signals.reset_index()
      df_signals.columns = ['Date', 'signal']
      datadf = pd.merge(datadf, df_signals, on='Date', how='inner').fillna(0)
      # Удаляем старую колонку 'Signal', если она есть
      if 'Signal' in datadf.columns:
          datadf.drop('Signal', axis=1, inplace=True)
      datadf.rename(columns={'Date': 'Datetime'}, inplace=True)
      datadf["Datetime"] = pd.to_datetime(datadf["Datetime"])
      datadf.set_index('Datetime', inplace=True)
      # Приводим все колонки к одному регистру (например, Capitalize)
      datadf.columns = datadf.columns.str.capitalize()
      # Расчет доходностей (используем ffill для заполнения первого NaN)
      datadf['Returns'] = datadf['Close'].pct_change()
      datadf['Returns'] = datadf['Returns'].ffill().fillna(0.0)
      # Заполнение оставшихся NaN/Inf нулями для безопасности
      datadf = datadf.replace([np.inf, -np.inf], np.nan).fillna(0)
      # Подготовка таргета
      datadf['y_next_close'] = datadf['Close'].shift(-1)
      # Удаляем последнюю строку, где нет таргета
      ## datadf = datadf.iloc[:-1].copy()
      # Создаем бинарный таргет
      datadf['target'] = (datadf['y_next_close'] > datadf['Close']).astype(int)
      return datadf, conditions # Возвращаем DataFrame и список доп. признаков

  datadf_neu, train_conditions_neu = preprocess_data(train_data_neu, strategy)
  ##
  datadf_neu = datadf_neu.iloc[:-1].copy()
  datadf_neu = datadf_neu.replace([np.inf, -np.inf], np.nan)
  datadf_neu.columns = datadf_neu.columns.str.capitalize()

  FEATURES = ['Close', 'Volume', 'Returns']
  train_conditions_neu = train_conditions_neu.reindex(columns=FEATURES + train_conditions_neu.columns.tolist())
  FEATURES = train_conditions_neu.columns

  # Rolling-прогноз: завтра (t+1)
  # -----------------------
  print("Выставляем параметры для модели Chronos... -> ")
  LOOKBACK = 128            # сколько последних дней даём модели как "контекст"
  THRESH   = 0.002          # порог для сигнала (0.2%) чтобы отсечь шум
  PRED_LEN = 1

  tail_size = LOOKBACK + 1
  test_data_extended = pd.concat([train_data_neu.iloc[-tail_size:], test_data_neu])
  test_datadf_neu, test_conditions_neu = preprocess_data(test_data_extended, strategy)
  close = datadf_neu["Close"].values.astype(np.float32)

  print("Pretrain BaseChronosPipeline... ->")
  print("=" * 50)

  chronos_output_dir = "./my_chronos_model"+strategy_instrument
  # Сохранение весов и конфигурации
  #model.save_pretrained(output_dir)
  # Сохранение токенизатора (необходимо для инференса)
  #tokenizer.save_pretrained(output_dir)



  # Загрузка локальной модели
  #pipeline = Chronos2Pipeline.from_pretrained("./my_chronos_model", device_map="cuda")

  chronos_output_dir = "./my_chronos_model"+strategy_instrument
  pipeline = BaseChronosPipeline.from_pretrained(
      "amazon/chronos-bolt-tiny",
      device_map=device_map,
      dtype=torch.bfloat16 if device_map != "cpu" else torch.float32,
  )
  if (action == "Load") and os.path.isdir(chronos_output_dir):
      pipeline = BaseChronosPipeline.from_pretrained(chronos_output_dir, device_map=device_map)

  # найдём индекс квантиля 0.5 (медиана), если доступно
  def get_median_forecast(forecast_tensor, pipeline_obj):
      # forecast_tensor shape: [1, Q, 1]
      Q = forecast_tensor.shape[1]
      q_list = getattr(pipeline_obj, "quantiles", None)
      if q_list is not None and 0.5 in q_list:
          qi = q_list.index(0.5)
      else:
          # fallback: берём центральный квантиль
          qi = Q // 2
      return float(forecast_tensor[0, qi, 0].detach().cpu().float().numpy())


  signals = np.zeros(len(datadf_neu), dtype=np.int8)   # -1 short, 0 flat, +1 long
  pred_next = np.full(len(datadf_neu), np.nan, dtype=np.float32)

  # сигнал на день t рассчитываем по инфо до t включительно, торгуем на t+1
  #for t in range(LOOKBACK, len(datadf_neu) - 1):
  #    ctx = torch.tensor(close[t - LOOKBACK : t + 1])  # 1D context
  #    with torch.no_grad():
  #        fc = pipeline.predict(ctx, prediction_length=PRED_LEN)  # [1, Q, 1]
  #    yhat = get_median_forecast(fc, pipeline)
  #    pred_next[t] = yhat
  #
  #    today = close[t]
  #    if yhat > today * (1.0 + THRESH):
  #        signals[t] = 1
  #    elif yhat < today * (1.0 - THRESH):
  #        signals[t] = -1
  #    else:
  #        signals[t] = 0
  for t in range(LOOKBACK, len(datadf_neu) - 1):
      ##ctx = torch.tensor(close[t - LOOKBACK : t + 1])  # 1D context
      ctx = torch.tensor(close[t - LOOKBACK : t + 1]).unsqueeze(0).to(device_map)
      if device_map == "cuda":
          ctx = ctx.to(torch.bfloat16)
      with torch.no_grad():
          fc = pipeline.predict(ctx, prediction_length=PRED_LEN)  # [1, Q, 1]
      yhat = get_median_forecast(fc, pipeline)
      pred_next[t] = yhat

      today = close[t]
      if yhat > today * (1.0 + THRESH):
          signals[t] = 1
      elif yhat < today * (1.0 - THRESH):
          signals[t] = -1
      else:
          signals[t] = 0

  datadf_neu["Signal"] = signals
  datadf_neu["PredNextClose"] = pred_next

  pipeline.model.save_pretrained(chronos_output_dir)

  print("=" * 50)
  print("ChronosNextDayDirection... -> ")
  bt_nextday = Backtest(
      datadf_neu, ChronosNextDayDirection,
      cash=1000_000,
      commission=0.002,   # 0.2% комиссия
      trade_on_close=True, # сделка по close текущего бара
      finalize_trades=True
  )
  #!!!!!!!!2.3 Look-ahead в исполнении сигнала
  #Сейчас Signal применяется на той же свече, по которой считается Close, а прибыль считается от Close[t] -> Close[t+1].
  #Если сигнал формируется с использованием Close[t] (и индикаторов на нём), то торговля “по close” в конце свечи
  # - это оптимистичное допущение (в реальности ты узнаёшь close в момент закрытия)
  #, хотя "в принципе" мы можем достаточно хорошо ориентироваться на "Close" закрывая позицию в конце свечи.
  #Тут просто как рекомендация для более "честной" стратегии.
  # =====>>>> В библиотеках для бэктестинга (например, backtrader или vectorbt) это обычно настраивается параметрами:
  #Вместо trade_on_close=True (как у вас сейчас), используйте настройку для торговли на открытии следующего бара (trade_on_open=True или аналогичную).
  #Убедитесь, что ваша стратегия использует данные бара [t] для расчета сигнала, который затем применяется к бару [t+1].
  #Это значительно повысит реалистичность вашего тестирования, хоть и может немного снизить итоговый Sharpe Ratio.

  stats_nextday = bt_nextday.run()

 # def chronos_predict_next_close(df_chronos, pipeline, lookback=LOOKBACK):
 #   close = df_chronos["Close"].values.astype(np.float32)
 #   preds = np.full(len(df_chronos), np.nan)
 #
 #   for t in range(lookback, len(df_chronos) - 1):
 #       ctx = torch.tensor(
 #           close[t - lookback : t + 1],
 #       )
 #       with torch.no_grad():
 #           fc = pipeline.predict(ctx, prediction_length=1)
 #
 #       preds[t] = get_median_forecast(fc, pipeline)
 #
 #   return preds

  def chronos_predict_next_close(df_chronos, pipeline, lookback=LOOKBACK):
    close = df_chronos["Close"].values.astype(np.float32)
    preds = np.full(len(df_chronos), np.nan, dtype=np.float32)

    pipeline.model.eval()
    device = next(pipeline.model.parameters()).device
    #dtype = torch.bfloat16 if device_map != "cpu" else torch.float32

    #for t in range(lookback, len(df_chronos) - 1):
    for t in range(lookback, len(df_chronos)):
        ctx_slice = close[t - lookback : t + 1]
        ctx = torch.tensor(ctx_slice, device=device).unsqueeze(0)
        if device.type == "cuda":
            ctx = ctx.to(torch.bfloat16)
        with torch.no_grad():
            fc = pipeline.predict(ctx, prediction_length=1)
        preds[t] = get_median_forecast(fc, pipeline)

        #ctx = torch.tensor(
        #    close[t - lookback : t + 1],
        #).unsqueeze(0).to(device_map)
        #with torch.no_grad():
        #    fc = pipeline.predict(ctx, prediction_length=1)

        #preds[t] = get_median_forecast(fc, pipeline)

    return preds

  datadf_neu["PredNext"] = chronos_predict_next_close(
    datadf_neu, pipeline, LOOKBACK
  )

  datadf_neu = datadf_neu.dropna(subset=["PredNext"])

  #================================================
  # Расчет ROC AUC для модели
  def calculate_chronos_roc_auc(df):
    # Очищаем от NaN (где не хватило LOOKBACK)
    valid_df = df.dropna(subset=["PredNext"]).copy()

    # 1. Реальное движение цены (Target): 1 если выросла, 0 если упала или осталась той же
    # Используем Close завтрашнего дня относительно Close сегодня
    actual_move = (valid_df["Close"].shift(-1) > valid_df["Close"]).astype(int)

    # 2. Прогноз модели (Score): Ожидаемое изменение цены
    # (Чем больше разница, тем выше уверенность модели в росте)
    predicted_change = valid_df["PredNext"] - valid_df["Close"]

    # Удаляем последнюю строку, так как для неё нет "завтрашнего" Close
    actual_move = actual_move[:-1]
    predicted_change = predicted_change[:-1]

    if len(actual_move) > 0:
        auc = roc_auc_score(actual_move, predicted_change)
        return auc
    return None

  # Применение для обучающей выборки
  print("=" * 70)
  train_auc = calculate_chronos_roc_auc(datadf_neu)
  print(f"ROC AUC (Train): {train_auc:.4f}")
  print("=" * 70)

  #==============================
  #!!!!!!!!!1. В ячейке 13 есть блок:
  #Next_Ret = Close.pct_change().shift(-1)
  #и перебор candidates и выбор best_thr по Sharpe
  #Если порог выбирается на том же периоде, на котором потом оцениваешь стратегию - это overfitting на метрику.
  #Порог лучше подбирать на отдельном “validation” внутри train (например, 80/20 по времени внутри train), а финально мерить только на test/valid.
  # =====>>>>>
  # --- 1. Разделение TRAIN на Train-Proper и Validation ---
  # Берем datadf_neu (который получен из train_data_neu)
  #split_idx = int(len(datadf_neu) * 0.8)
  #train_subset = datadf_neu.iloc[:split_idx].copy()
  #val_subset = datadf_neu.iloc[split_idx:].copy()
  #print(f"Подбор порога на валидации: {len(val_subset)} свечей")
  # --- 2. Получаем прогнозы для валидационной части ---
  # Чтобы не пересчитывать всё, можно взять уже готовые PredNext из datadf_neu
  # если они были посчитаны для всего набора ранее.
  #val_subset["Next_Ret"] = val_subset["Close"].pct_change().shift(-1)
  #val_subset = val_subset.dropna(subset=["PredNext", "Next_Ret"])
  #candidates = np.linspace(0.0, 0.01, 21) # 0% - 1%
  #best_thr = 0.0
  #best_sharpe = -np.inf
  #for thr in candidates:
  #    # Генерируем сигнал только на валидационном наборе
  #    cond_long = val_subset["PredNext"] > val_subset["Close"] * (1 + thr)
  #    cond_short = val_subset["PredNext"] < val_subset["Close"] * (1 - thr)
  #   val_signal = np.where(cond_long, 1, np.where(cond_short, -1, 0))
  #   # Доходность стратегии на валидации
  #   strat_ret = val_signal * val_subset["Next_Ret"]
  #   # Считаем коэффициент Шарпа
  #   if strat_ret.std() == 0:
  #        sharpe = 0
  #   else:
  #        sharpe = (strat_ret.mean() / strat_ret.std()) * np.sqrt(252) # Годовое значение
  #    if sharpe > best_sharpe:
  #        best_sharpe = sharpe
  #        best_thr = thr
  #print(f"Выбран порог {best_thr:.4f} (Sharpe на валидации: {best_sharpe:.4f})")
  # --- 3. Финальное применение на TEST ---
  # Теперь используем best_thr, который модель "не видела" в контексте доходности теста
  #test_datadf_neu["Signal"] = np.where(
  #    test_datadf_neu["PredNext"] > test_datadf_neu["Close"] * (1 + best_thr), 1,
  #    np.where(test_datadf_neu["PredNext"] < test_datadf_neu["Close"] * (1 - best_thr), -1, 0)
  #)
  #returns = datadf_neu["Close"].pct_change().shift(-1)
  #datadf_neu["Next_Ret"] = datadf_neu["Close"].pct_change().shift(-1)
  #datadf_neu_clean = datadf_neu.dropna(subset=["PredNext", "Next_Ret"])
  #candidates = np.linspace(0.0, 0.01, 21)  # 0% … 1%
  ###best_thr, best_sharpe = None, -np.inf

  #for thr in candidates:
  #    signal = np.where(
  #        datadf_neu["PredNext"] > datadf_neu["Close"] * (1 + thr),  1,
  #        np.where(datadf_neu["PredNext"] < datadf_neu["Close"] * (1 - thr), -1, 0)
  #    )
  #
  #    strat_ret = signal * returns
  #    sharpe = strat_ret.mean() / strat_ret.std()
  #
  #    if sharpe > best_sharpe:
  #        best_sharpe = sharpe
  #        best_thr = thr

  for thr in candidates:
      cond_long = datadf_neu_clean["PredNext"] > datadf_neu_clean["Close"] * (1 + thr)
      cond_short = datadf_neu_clean["PredNext"] < datadf_neu_clean["Close"] * (1 - thr)
      temp_signal = np.where(cond_long, 1, np.where(cond_short, -1, 0))
      strat_ret = temp_signal * datadf_neu_clean["Next_Ret"]
      # Расчет шарпа (упрощенно)
      sharpe = strat_ret.mean() / (strat_ret.std() + 1e-9)
      if sharpe > best_sharpe:
          best_sharpe = sharpe
          best_thr = thr

  print("Best threshold:", best_thr, "Sharpe:", best_sharpe)

  test_datadf_neu["PredNext"] = chronos_predict_next_close(
    test_datadf_neu, pipeline, LOOKBACK
  )

  test_datadf_neu["Signal"] = np.where(
      test_datadf_neu["PredNext"] > test_datadf_neu["Close"] * (1 + best_thr),  1,
      np.where(test_datadf_neu["PredNext"] < test_datadf_neu["Close"] * (1 - best_thr), -1, 0)
  )

  print("=" * 50)
  print("ChronosStrategy... -> ")
  bt_chronos = Backtest(
      test_datadf_neu,
      ChronosStrategy,
      cash=1000_000,
      commission=0.002,
      trade_on_close=True,
      finalize_trades=True
  )

  stats_chronos = bt_chronos.run()

  print("=" * 50)
  print("BuyHold... -> ")
  bt_bh = Backtest(
    test_datadf_neu,
    BuyHold,
    cash=1000_000,
    commission=0.002,
    trade_on_close=True,
    finalize_trades=True
  )

  stats_bh = bt_bh.run()

  print("=" * 50)
  print("TemaGoldenCrossStrategy... -> ")
  #test_datadf_neu = test_datadf_neu[ LOOKBACK: ]
  #test_datadf_neu_signals = test_datadf_neu[['Signal']].copy()
  #test_datadf_neu_signals.index.name = 'Date'
  #test_datadf_neu_signals.columns = ['signal']
  #test_datadf_neu['signal'] = test_datadf_neu_signals['signal'].copy()

  test_datadf_neu = test_datadf_neu[ LOOKBACK: ]
  test_datadf_neu_signals = test_datadf_neu[['Signal']].copy()
  test_datadf_neu_signals.index.name = 'Date'
  test_datadf_neu_signals.columns = ['signal']
  test_datadf_neu['Signal'] = test_datadf_neu_signals['signal']
  test_datadf_neu['Signal'] = test_datadf_neu['Signal'].fillna(0)
  test_datadf_neu_signals = test_datadf_neu['Signal']

  test_datadf_neu_backtest = setBktDataFrame(test_datadf_neu_signals, test_conditions_neu, test_datadf_neu)


  #test_datadf_neu_backtest['Signal'] = test_datadf_neu_backtest['Label']
  btchronos = Backtest(test_datadf_neu, TemaGoldenCrossStrategy, cash=1000000, commission=.002, exclusive_orders=True, finalize_trades=True)
  stats_goldencross = btchronos.run()
  display("GoldenCrossStrategy:  ")
  btchronos.plot(
        plot_equity=True,
        plot_drawdown=True,
        relative_equity=False,
        superimpose=False #при date = 1h ошибка Invalid value for `superimpose`: Upsampling not supported
    )
  #bt.plot()
  #print(stats_goldencross[:27])

  db_chronos = pd.concat([stats_bh, stats_nextday], axis = 1)
  db_chronos.columns = ['Buy&Hold', 'GoldenCross']
  display(db_chronos)
  comparison = pd.DataFrame({
    "Chronos": stats_nextday,
    #"GoldenCross": stats_goldencross,
    "Buy&Hold": stats_bh
  })

  #print(comparison)

  risk_adjusted_return_chronos = (
            stats_nextday.iloc[7] *
            stats_nextday.iloc[12] *
            stats_nextday.iloc[13] *
            stats_nextday.iloc[7]
        ) / (1 + stats_nextday.iloc[17])

  display(f'risk_adjusted_return = {risk_adjusted_return_chronos:.2f}')

  #y_pred = torch.tensor(y_pred_binary)
  #y_true = torch.tensor(y_true_binary)
  #metric = BinaryAUROC()
  #auc_score = metric(y_pred, y_true)
  #print(f"ROC AUC: {auc_score.item()}")

  return_chronos = {
            'final_equity': stats_nextday.iloc[4], #final_equity,
            'n_trades': stats_nextday.iloc[21], #n_trades,
            'returns': stats_nextday.iloc[7], #returns,
            'max_drawdown': abs(stats_nextday.iloc[17]), #max_drawdown,
            'win_rate': stats_nextday.iloc[22], #win_rate,
            'sharpe_ratio': stats_nextday.iloc[12], #sharpe_ratio,
            'sortino_ratio': stats_nextday.iloc[13], #sortino_ratio,
            'profit_factor': stats_nextday.iloc[7], #profit_factor
            'pipeline': pipeline,
            'strategy_ticker': strategy.ticker
            #'rocauc': roc, #rocauc для модели
            #'pred': y_pred_binary.copy(), # запоминаем предсказание для набора
        }

  return return_chronos

In [ ]:
# Определение модели классификации

class TSMixerBinaryClassifier(nn.Module):
    """
    Бинарный классификатор на основе PatchTSMixer.

    Архитектура:
    1. Backbone: стандартный PatchTSMixerForPrediction из HuggingFace
    2. Feature extraction: используем prediction_outputs как признаки
    3. Classification head: полносвязные слои с dropout

    Преимущества:
    - Используем проверенную архитектуру из transformers
    - Backbone уже оптимизирован для работы с временными рядами
    - Простота и прозрачность кода
    """

    def __init__(self, config):
        super().__init__()
        self.config = config

        # Backbone: стандартная модель PatchTSMixer для prediction
        # Она обучается предсказывать следующий шаг, и мы используем её выходы как признаки
        self.backbone = PatchTSMixerForPrediction(config)

        # Classification head
        # Входные признаки: (batch, prediction_length=1, num_channels)
        # После flatten: (batch, num_channels)
        self.classifier = nn.Sequential(
            nn.Flatten(),  # (batch, 1, num_channels) -> (batch, num_channels)
            nn.Linear(config.num_input_channels, 128),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(64, 2)  # 2 класса: падение (0) и рост (1)
        )

    def forward(self, past_values):
        """
        Forward pass.

        Параметры:
        - past_values: (batch, context_length, num_channels)

        Возвращает:
        - logits: (batch, 2) - логиты для двух классов
        """
        # Получаем prediction outputs из backbone
        outputs = self.backbone(past_values=past_values)

        # prediction_outputs имеет размер (batch, prediction_length=1, num_channels)
        # Эти выходы содержат закодированную информацию о временном ряде
        features = outputs.prediction_outputs

        # Пропускаем через classification head
        logits = self.classifier(features)

        return logits

print("Класс TSMixerBinaryClassifier определен")

Класс TSMixerBinaryClassifier определен

In [ ]:
def setBktDataFrame(df_signals, df_conditions, df_data_all) :

  df_backtest = df_data_all.copy()

  # Убеждаемся, что индекс назван 'Date' или 'Datetime' и является временным
  if df_backtest.index.name is None:
     df_backtest.index.name = 'Datetime'

  # Все колонки должны быть Capitalize для ChronosNextDayDirection
  df_backtest.columns = df_backtest.columns.str.capitalize()

  # Библиотека Backtest ожидает колонку 'Open', 'High', 'Low', 'Close', 'Volume' и 'Signal'
  required_cols = ['Open', 'High', 'Low', 'Close', 'Volume', 'Signal']

  # Проверка наличия всех нужных колонок
  if not all(col in df_backtest.columns for col in required_cols):
     missing = [col for col in required_cols if col not in df_backtest.columns]
     raise ValueError(f"Отсутствуют обязательные колонки для Backtest: {missing}")

  return df_backtest[required_cols] # Возвращаем только нужные колонки

In [ ]:
def backtestWithNeu(strategy, data, test_data, action=None, instrument=None) :

  train_data_neu = data.copy()
  test_data_neu = test_data.copy()
  if instrument is not None :
      strategy_instrument = instrument
      tsmixer_output_dir = "tsmixer_full_"+strategy_instrument+".pt"
  if strategy.ticker is not None:
      strategy_instrument = strategy.ticker
      tsmixer_output_dir = "tsmixer_full_"+strategy_instrument+".pt"

  def preprocess_data(df_raw, strategy_instance):
    """Единая функция для обработки train или test данных."""
    df = df_raw.copy()
    # Генерация сигналов
    signals, conditions, datadf = strategy_instance.generate_signals(df)
    if 'Signal' in conditions.columns:
        conditions.drop('Signal', axis=1, inplace=True)
    conditions.columns = conditions.columns.str.capitalize()
    df_signals = signals.reset_index()
    df_signals.columns = ['Date', 'signal']
    datadf = pd.merge(datadf, df_signals, on='Date', how='inner').fillna(0)
    # Удаляем старую колонку 'Signal', если она есть
    if 'Signal' in datadf.columns:
        datadf.drop('Signal', axis=1, inplace=True)
    datadf.rename(columns={'Date': 'Datetime'}, inplace=True)
    datadf["Datetime"] = pd.to_datetime(datadf["Datetime"])
    datadf.set_index('Datetime', inplace=True)
    # Приводим все колонки к одному регистру (например, Capitalize)
    datadf.columns = datadf.columns.str.capitalize()
    # Расчет доходностей (используем ffill для заполнения первого NaN)
    datadf['Returns'] = datadf['Close'].pct_change()
    datadf['Returns'] = datadf['Returns'].ffill().fillna(0.0)
    # Заполнение оставшихся NaN/Inf нулями для безопасности
    datadf = datadf.replace([np.inf, -np.inf], np.nan).fillna(0)
    # Подготовка таргета
    datadf['y_next_close'] = datadf['Close'].shift(-1)
    # Удаляем последнюю строку, где нет таргета
    datadf = datadf.iloc[:-1].copy()
    # Создаем бинарный таргет
    datadf['target'] = (datadf['y_next_close'] > datadf['Close']).astype(int)
    return datadf, conditions # Возвращаем DataFrame и список доп. признаков

  # Шаг 1: Подготовка данных для бинарной классификации
  # ======================================================

  LOOKBACK = 128        # сколько дней истории подаем в модель
  PATCHLENGTH = LOOKBACK - 1
  HORIZON  = 7         # сколько дней прогнозируем вперед
  TRAIN_RATIO = 1
  EPOCHS = 50
  BATCH_SIZE = 64
  LR = 3e-4
  WEIGHT_DECAY = 1e-2
  SEED = 42
  device = "cuda" if torch.cuda.is_available() else "cpu"

  #=======================================================
  df_binary, train_conditions_neu = preprocess_data(train_data_neu, strategy)
  FEATURES = ['Returns', 'Close', 'Volume' ]
  train_conditions_neu = train_conditions_neu.reindex(columns=FEATURES + train_conditions_neu.columns.tolist())
  FEATURES = train_conditions_neu.columns

  tail_size = LOOKBACK + 1
  test_data_extended = pd.concat([train_data_neu.iloc[-tail_size:], test_data_neu])
  test_datadf_neu, test_conditions_neu = preprocess_data(test_data_extended, strategy)
  ## --- ШАГ 1: Поиск параметров на TRAIN (через внутреннюю валидацию) ---
  # Находим параметры, используя только тренировочные данные
  #best_params = optimize_on_validation(train_data_neu)
  # --- ШАГ 2: Подготовка ТЕСТА (с контекстом из прошлого) ---
  # Для Chronos нам нужны последние LOOKBACK свечей из Train, чтобы предсказать начало Test
  #tail_size = best_params['LOOKBACK']
  #test_data_extended = pd.concat([train_data_neu.iloc[-tail_size:], test_data_neu])
  # --- ШАГ 3: Инференс на ТЕСТЕ ---
  # Используем параметры, найденные на шаге 1. НИКАКОЙ новой оптимизации!
  #test_preds = get_chronos_predictions(test_data_extended, pipeline, best_params)
  # --- ШАГ 4: Финальный Бэктест ---
  #stats_test = run_backtest(test_data_neu, test_preds, best_params)

  #=======================================================
  print("=" * 70)
  print("РАСПРЕДЕЛЕНИЕ КЛАССОВ")
  print("=" * 70)
  print(df_binary['target'].value_counts().sort_index())
  print(f"\nБаланс классов (доля класса 1): {df_binary['target'].mean():.3f}")
  print(f"Всего примеров: {len(df_binary)}")
  print("=" * 70)

  # 2: Нормализация и создание временных окон
  # ================================================

  # Извлекаем признаки и таргет
  X_binary = df_binary[FEATURES].astype("float32").to_numpy()
  y_binary = df_binary["target"].astype("int64").to_numpy()

  X_binary_test = test_datadf_neu[FEATURES].astype("float32").to_numpy()
  y_binary_test = test_datadf_neu["target"].astype("int64").to_numpy()
  scaler = MinMaxScaler(feature_range=(0, 1))

  #X_binary = scaler.fit_transform(X_binary)
  #X_binary_test = scaler.transform(X_binary_test)

  # Нормализация признаков (только по train!)
  mu_binary = X_binary.mean(axis=0, keepdims=True)
  sd_binary = X_binary.std(axis=0, keepdims=True) + 1e-8
  X_binary_norm = (X_binary - mu_binary) / sd_binary

  # Нормализация признаков (только по test!)
  X_binary_norm_test = (X_binary_test - mu_binary) / sd_binary

  # Функция для создания скользящих окон
  def create_classification_windows(X_normalized, y_labels, lookback):
      """
      Создает скользящие окна для задачи классификации временных рядов.

      Параметры:
      - X_normalized: нормализованные признаки (T, num_features)
      - y_labels: метки классов (T,)
      - lookback: размер окна истории

      Возвращает:
      - X_windows: (N, lookback, num_features)
      - y_windows: (N,)
      - indices: индексы в оригинальном массиве
      """
      X_windows, y_windows, indices = [], [], []

      for i in range(lookback, len(y_labels)):
          # Берем окно истории размером lookback
          X_windows.append(X_normalized[i - lookback:i, :])
          # Таргет - это метка в момент времени i
          y_windows.append(y_labels[i])
          indices.append(i)

      X_windows = np.asarray(X_windows, dtype=np.float32)  # (N, lookback, num_features)
      y_windows = np.asarray(y_windows, dtype=np.int64)     # (N,)
      indices = np.asarray(indices, dtype=np.int64)

      return X_windows, y_windows, indices

  # Создаем окна
  X_win, y_win, idx_win = create_classification_windows(X_binary_norm, y_binary, LOOKBACK)
  # Создаем окна test
  X_win_test, y_win_test, idx_win_test = create_classification_windows(X_binary_norm_test, y_binary_test, LOOKBACK)


  print(f"Размер окон признаков: {X_win.shape}")
  print(f"Размер таргетов: {y_win.shape}")
  print(f"Размер индексов: {idx_win.shape}")

  # 3: Разделение на train/test
  # ==================================

  # Разделяем данные
  X_train_binary = X_win
  y_train_binary = y_win
  idx_train_binary = idx_win

  # Разделяем данные test
  X_test_binary = X_win_test
  y_test_binary = y_win_test
  idx_test_binary = idx_win_test

  print("=" * 70)
  print("РАЗМЕРЫ ВЫБОРОК")
  print("=" * 70)
  print(f"Train: X={X_train_binary.shape}, y={y_train_binary.shape}")
  print(f"Test:  X={X_test_binary.shape}, y={y_test_binary.shape}")
  print(f"\nРаспределение классов в test:")
  print(f"  Класс 0 (падение): {(y_test_binary == 0).sum()} ({(y_test_binary == 0).mean():.1%})")
  print(f"  Класс 1 (рост):    {(y_test_binary == 1).sum()} ({(y_test_binary == 1).mean():.1%})")
  print("=" * 70)

  # 4: Создание DataLoaders
  # =============================

  train_dataset_binary = TensorDataset(
      torch.from_numpy(X_train_binary),
      torch.from_numpy(y_train_binary)
  )

  test_dataset_binary = TensorDataset(
      torch.from_numpy(X_test_binary),
      torch.from_numpy(y_test_binary)
  )

  train_loader_binary = DataLoader(
      train_dataset_binary,
      batch_size=BATCH_SIZE,
      shuffle=True,
      drop_last=False
  )

  test_loader_binary = DataLoader(
      test_dataset_binary,
      batch_size=BATCH_SIZE,
      shuffle=False,
      drop_last=False
  )

  print(f"Train batches: {len(train_loader_binary)}")
  print(f"Test batches:  {len(test_loader_binary)}")

  # Проверим размерность одного батча
  xb_sample, yb_sample = next(iter(train_loader_binary))
  print(f"\nПример батча:")
  print(f"  X: {xb_sample.shape}  (batch, lookback, num_features)")
  print(f"  y: {yb_sample.shape}  (batch,)")

  # Проверим размерность одного батча test
  xb_sample_test, yb_sample_test = next(iter(test_loader_binary))
  print(f"\nПример батча test:")
  print(f"  X: {xb_sample_test.shape}  (batch, lookback, num_features)")
  print(f"  y: {yb_sample_test.shape}  (batch,)")

  # 6: Создание и инициализация модели
  # ========================================

  # Конфигурация модели
  # ВАЖНО: prediction_length=1, так как мы используем выход как feature vector
  config_binary = PatchTSMixerConfig(
      context_length=LOOKBACK,          # Длина входного окна
      prediction_length=1,              # Выход размером 1 (используется как признаки)
      #Обычно для классификации временных рядов prediction_length устанавливается в 0 или игнорируется, если используется PatchTSMixerForClassification
      num_input_channels=len(FEATURES), # Количество признаков (12)
      patch_length=PATCHLENGTH,                  # Размер патча
      #patch_stride=8,                   # Шаг между патчами
      patch_stride=PATCHLENGTH,
      #Обычно stride выбирают равным patch_length (без перекрытия) или чуть меньше. С таким маленьким шагом модель будет обучаться очень медленно.
      d_model=96,                       # Размерность скрытого представления
      num_layers=6,                     # Количество слоев
      dropout=0.1,                      # Dropout для регуляризации
  )


  # Создаем модель
  print("=" * 70)
  model_binary = TSMixerBinaryClassifier(config_binary).to(device)
  if (action=="Load") & os.path.exists(tsmixer_output_dir):
     print(f"Load {tsmixer_output_dir} ...")
     #model_binary = torch.load(tsmixer_output_dir, weights_only=False)
     #model_binary.load_state_dict(torch.load(tsmixer_output_dir, weights_only=True))
     checkpoint = torch.load(tsmixer_output_dir, map_location=device)
     model_binary.load_state_dict(checkpoint['model_state_dict'])
     optimizer_binary = torch.optim.AdamW(model_binary.parameters(), lr=LR)
     if 'optimizer_state_dict' in checkpoint:
        optimizer_binary.load_state_dict(checkpoint['optimizer_state_dict'])

     model_binary.to(device)
     model_binary.eval() # Перевод в режим предсказания
     EPOCHS=0
     print(f"Модель {tsmixer_output_dir} загружена.")

  if os.path.exists(tsmixer_output_dir):
      print(f"Загружены лучшие веса из {tsmixer_output_dir}")

  # Считаем количество параметров
  total_params = sum(p.numel() for p in model_binary.parameters())
  trainable_params = sum(p.numel() for p in model_binary.parameters() if p.requires_grad)

  print("=" * 70)
  print("ИНФОРМАЦИЯ О МОДЕЛИ")
  print("=" * 70)
  print(f"Всего параметров:      {total_params:,}")
  print(f"Обучаемых параметров:  {trainable_params:,}")
  print(f"Устройство:            {device}")
  print("=" * 70)

  # 7: Настройка обучения
  # ===========================

  # Optimizer: AdamW с weight decay для регуляризации
  if (action!="Load"):
      print(f"Установлен новый Optimizer: AdamW с weight decay для регуляризации")
      optimizer_binary = torch.optim.AdamW(
          model_binary.parameters(),
          lr=LR,
          weight_decay=WEIGHT_DECAY
      )

  # -------------------------------
  # 1. Считаем количество примеров каждого класса в обучающей выборке
  class_counts = df_binary['target'].value_counts().sort_index().values
  # class_counts[0] — количество объектов класса 0 (Down)
  # class_counts[1] — количество объектов класса 1 (Up)

  # 2. Вычисляем веса (обратная пропорция)
  # Общая логика: weight = total_samples / (n_classes * class_samples)
  total_samples = len(df_binary)
  n_classes = 2

  weights = total_samples / (n_classes * class_counts)

  # 3. Переводим в тензор и отправляем на устройство (CPU/GPU)
  weights_tensor = torch.tensor(weights, dtype=torch.float32).to(device)

  # 4. Инициализируем лосс с весами
  criterion_binary = nn.CrossEntropyLoss(weight=weights_tensor)

  print(f"Веса классов для Loss: 0 (Down): {weights[0]:.4f}, 1 (Up): {weights[1]:.4f}")


  # Loss function: CrossEntropyLoss для бинарной классификации
  ##criterion_binary = nn.CrossEntropyLoss()
  #Вы используете стандартный CrossEntropyLoss(). Если на шаге подготовки данных вы увидели дисбаланс (например, класс 1 занимает 60%), модель может просто научиться всегда предсказывать единицу.
  #criterion_binary = nn.CrossEntropyLoss(weight=torch.tensor([weight0, weight1]).to(device))


  # Функция для evaluation
  def evaluate_binary_classifier():
      """
      Оценка модели на test set.

      Возвращает:
      - accuracy: точность классификации
      - predictions: предсказанные метки
      - true_labels: истинные метки
      """
      model_binary.eval()
      all_preds = []
      all_labels = []

      with torch.no_grad():
          for xb, yb in test_loader_binary:
              xb = xb.to(device)
              yb = yb.to(device)

              # Forward pass
              logits = model_binary(xb)

              # Предсказания (argmax по логитам)
              preds = torch.argmax(logits, dim=1)

              # Сохраняем для подсчета метрик
              all_preds.extend(preds.cpu().numpy())
              all_labels.extend(yb.cpu().numpy())

      all_preds = np.array(all_preds)
      all_labels = np.array(all_labels)

      accuracy = (all_preds == all_labels).mean()

      return accuracy, all_preds, all_labels

  print("✓ Optimizer, loss function и evaluation function настроены")

  # 8: Обучение модели
  # ========================
  # Инициализация для сохранения лучшей модели
  best_test_acc = 0.0

  print("=" * 70)
  print("НАЧАЛО ОБУЧЕНИЯ")
  print("=" * 70)

  for epoch in range(1, EPOCHS + 1):
      # Training phase
      model_binary.train()
      train_loss_sum = 0.0
      train_correct = 0
      train_total = 0

      for xb, yb in train_loader_binary:
          xb = xb.to(device)
          yb = yb.to(device)

          # Forward pass
          logits = model_binary(xb)
          loss = criterion_binary(logits, yb)

          # Backward pass
          optimizer_binary.zero_grad(set_to_none=True)
          loss.backward()

          # Gradient clipping для стабильности
          torch.nn.utils.clip_grad_norm_(model_binary.parameters(), max_norm=1.0)

          # Update weights
          optimizer_binary.step()

          # Статистика
          train_loss_sum += loss.item()
          preds = torch.argmax(logits, dim=1)
          train_correct += (preds == yb).sum().item()
          train_total += yb.size(0)

      # Метрики за эпоху
      train_loss_avg = train_loss_sum / len(train_loader_binary)
      train_acc = train_correct / train_total

      # Evaluation на test set
      test_acc, _, _ = evaluate_binary_classifier()

      # ЛОГИКА СОХРАНЕНИЯ ЛУЧШЕЙ МОДЕЛИ
      if test_acc > best_test_acc:
          best_test_acc = test_acc
          # Сохраняем состояние (state_dict) - самый надежный способ
          #torch.save(model_binary.state_dict(), tsmixer_output_dir)
          checkpoint = {
              'model_state_dict': model_binary.state_dict(),
              'optimizer_state_dict': optimizer_binary.state_dict(),
          }
          torch.save(checkpoint, tsmixer_output_dir)
          save_status = f" | [Model Saved! Best Acc: {best_test_acc:.4f}]"
      else:
          save_status = ""

      # Вывод результатов
      print(f"Epoch {epoch:2d}/{EPOCHS} | "
            f"Train Loss: {train_loss_avg:.4f} | "
            f"Train Acc: {train_acc:.4f} | "
            f"Test Acc: {test_acc:.4f}{save_status}")


  print("=" * 70)
  print(f"ОБУЧЕНИЕ ЗАВЕРШЕНО. Лучшая точность: {best_test_acc:.4f}")
  print("=" * 70)

  # 9: Финальная оценка и детальные метрики
  # ==============================================

  from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

  # Получаем финальные предсказания


  # ЗАГРУЖАЕМ ЛУЧШИЕ ВЕСА ПЕРЕД ФИНАЛЬНОЙ ОЦЕНКОЙ
  if os.path.exists(tsmixer_output_dir):
      print("=" * 70)
      print(f"ЗАГРУЖАЕМ ЛУЧШИЕ ВЕСА ПЕРЕД ФИНАЛЬНОЙ ОЦЕНКОЙ")
      #model_binary.load_state_dict(torch.load(tsmixer_output_dir, weights_only=True))

      checkpoint = torch.load(tsmixer_output_dir, map_location=device)
      model_binary.load_state_dict(checkpoint['model_state_dict'])
      optimizer_binary = torch.optim.AdamW(model_binary.parameters(), lr=LR)
      if 'optimizer_state_dict' in checkpoint:
         optimizer_binary.load_state_dict(checkpoint['optimizer_state_dict'])
      model_binary.to(device)
      print(f"Загружены лучшие веса из {tsmixer_output_dir}")
  print("=" * 70)

  final_test_acc, y_pred_binary, y_true_binary = evaluate_binary_classifier()
  #torch.save(model_binary, tsmixer_output_dir)
  #print(f"Полная модель {tsmixer_output_dir} сохранена.")


  print("\n" + "=" * 70)
  print("ФИНАЛЬНЫЕ РЕЗУЛЬТАТЫ КЛАССИФИКАЦИИ")
  print("=" * 70)
  print(f"Test Accuracy: {final_test_acc:.4f} ({final_test_acc*100:.2f}%)")

  # Baseline - всегда предсказываем мажоритарный класс
  baseline_acc = max(y_true_binary.mean(), 1 - y_true_binary.mean())
  print(f"Baseline (majority class): {baseline_acc:.4f} ({baseline_acc*100:.2f}%)")
  print(f"Улучшение над baseline: {(final_test_acc - baseline_acc)*100:.2f}%")

  # Classification Report
  print("\n" + "-" * 70)
  print("CLASSIFICATION REPORT")
  print("-" * 70)
  print(classification_report(
      y_true_binary,
      y_pred_binary,
      target_names=['Down (0)', 'Up (1)'],
      digits=4
  ))

  # Confusion Matrix
  print("-" * 70)
  print("CONFUSION MATRIX")
  print("-" * 70)
  cm = confusion_matrix(y_true_binary, y_pred_binary)
  print("\n              Predicted")
  print("                0      1")
  print(f"Actual 0    {cm[0,0]:5d}  {cm[0,1]:5d}")
  print(f"       1    {cm[1,0]:5d}  {cm[1,1]:5d}")

  # Дополнительные метрики
  tn, fp, fn, tp = cm.ravel()
  precision_up = tp / (tp + fp) if (tp + fp) > 0 else 0
  recall_up = tp / (tp + fn) if (tp + fn) > 0 else 0
  precision_down = tn / (tn + fn) if (tn + fn) > 0 else 0
  recall_down = tn / (tn + fp) if (tn + fp) > 0 else 0

  print("\n" + "-" * 70)
  print("ИНТЕРПРЕТАЦИЯ")
  print("-" * 70)
  print(f"True Positives (правильно предсказан рост):     {tp}")
  print(f"True Negatives (правильно предсказано падение): {tn}")
  print(f"False Positives (ложный сигнал на рост):        {fp}")
  print(f"False Negatives (пропущенный рост):             {fn}")

  # 11: Бэктест торговых стратегий
  # ====================================

  # Рассчитаем реальные returns
  actual_returns_binary = np.zeros(len(y_true_binary))

  for i in range(len(idx_test_binary)):
      idx = idx_test_binary[i]
      if idx < len(df_binary):
          today_price = df_binary["Close"].iloc[idx]
          next_price = df_binary["y_next_close"].iloc[idx]
          actual_returns_binary[i] = (next_price - today_price) / today_price

  # Стратегия 1: Long only (покупаем только когда модель предсказывает рост)
  strategy_long_only = np.where(y_pred_binary == 1, actual_returns_binary, 0.0)

  # Стратегия 2: Long/Short (лонг при росте, шорт при падении)
  strategy_long_short = np.where(y_pred_binary == 1, actual_returns_binary, -actual_returns_binary)

  # Кумулятивные доходности
  cum_return_buy_hold = np.cumprod(1 + actual_returns_binary) - 1
  cum_return_long_only = np.cumprod(1 + strategy_long_only) - 1
  cum_return_long_short = np.cumprod(1 + strategy_long_short) - 1

  # Статистика
  print("\n" + "=" * 70)
  print("BACKTEST ТОРГОВЫХ СТРАТЕГИЙ")
  print("=" * 70)
  print(f"Buy & Hold:              {cum_return_buy_hold[-1]:7.2%}")
  print(f"Strategy (Long only):    {cum_return_long_only[-1]:7.2%}")
  print(f"Strategy (Long/Short):   {cum_return_long_short[-1]:7.2%}")
  print("=" * 70)

  # Дополнительные метрики
  sharpe_bh = actual_returns_binary.mean() / (actual_returns_binary.std() + 1e-8) * np.sqrt(252)
  sharpe_long = strategy_long_only.mean() / (strategy_long_only.std() + 1e-8) * np.sqrt(252)
  sharpe_ls = strategy_long_short.mean() / (strategy_long_short.std() + 1e-8) * np.sqrt(252)

  print(f"\nSharpe Ratio (годовой):")
  print(f"  Buy & Hold:           {sharpe_bh:.3f}")
  print(f"  Strategy (Long only): {sharpe_long:.3f}")
  print(f"  Strategy (Long/Short):{sharpe_ls:.3f}")
  print("=" * 70)

  # бэктест с помощью библиотеки
  test_datadf_neu = test_datadf_neu[ LOOKBACK: ]
  test_datadf_neu['Signal'] = y_pred_binary
  test_datadf_neu['Signal'] = test_datadf_neu['Signal'].ffill()
  test_datadf_neu_signals = test_datadf_neu['Signal']

  test_datadf_neu_backtest = setBktDataFrame(test_datadf_neu_signals, test_conditions_neu, test_datadf_neu)

  bt = Backtest(test_datadf_neu_backtest, ChronosNextDayDirection, cash=1000000, commission=.002, exclusive_orders=True, finalize_trades=True)

  stats_neu = bt.run()
  print(stats_neu[:27])
  bt.plot(
        plot_equity=True,
        plot_drawdown=True,
        relative_equity=False,
        superimpose=False #при date = 1h ошибка Invalid value for `superimpose`: Upsampling not supported
    )

  risk_adjusted_return_neu = (
            stats_neu.iloc[7] *
            stats_neu.iloc[12] *
            stats_neu.iloc[13] *
            stats_neu.iloc[7]
        ) / (1 + stats_neu.iloc[17])

  display(f'risk_adjusted_return = {risk_adjusted_return_neu:.2f}')

  # ROC AUC
  model_binary.eval()
  all_probs = []
  all_labels = []

  with torch.no_grad():
      for xb, yb in test_loader_binary:
          xb = xb.to(device)
          logits = model_binary(xb)
          # Получаем вероятности класса 1 (Up)
          probs = torch.softmax(logits, dim=1)[:, 1]

          all_probs.append(probs.cpu())
          all_labels.append(yb.cpu())

  # Объединяем все батчи в единые тензоры
  all_probs = torch.cat(all_probs)
  all_labels = torch.cat(all_labels)

  # Считаем метрику
  metric = BinaryAUROC()
  auc_score = metric(all_probs, all_labels)

  print(f"Финальный ROC AUC на тесте: {auc_score.item():.4f}")

  return_neu = {
            'final_equity': stats_neu.iloc[4], #final_equity,
            'n_trades': stats_neu.iloc[21], #n_trades,
            'returns': stats_neu.iloc[7], #returns,
            'max_drawdown': abs(stats_neu.iloc[17]), #max_drawdown,
            'win_rate': stats_neu.iloc[22], #win_rate,
            'sharpe_ratio': stats_neu.iloc[12], #sharpe_ratio,
            'sortino_ratio': stats_neu.iloc[13], #sortino_ratio,
            'profit_factor': stats_neu.iloc[7], #profit_factor
            'rocauc': auc_score, #rocauc для модели,
            'strategy_ticker': strategy.ticker
            #'pred': model_binary_pred.copy() # запоминаем предсказание для набора
        }
  #return_neu['final_equity'] = return_neu['final_equity'].map(lambda x: f"{x}")
  #return_neu['max_drawdown'] = return_neu['max_drawdown'].map(lambda x: x*100)

  return return_neu

In [ ]:
class TemaGoldenCrossStrategy(Strategy):
    def init(self):
        # переопределяем Индикатор по колонке Signal
        self.signal = self.I(lambda: self.data.Signal)
        self.previous_signal = 0

    def next(self):
        current_signal = self.signal[-1]

        ########################################################################
        #  previous_signal current_signal   previous_position    current_position
        #          0              1             is_short              close
        #          0              1        != is_long (close)      buy (is_long)
        #
        #         -1              1             is_short              close
        #         -1              1        != is_long (close)      buy (is_long)
        #
        #         (1)             1
        #
        if current_signal != self.previous_signal:
            if current_signal == 1:
                if self.position.is_short:
                    self.position.close()

                if not self.position.is_long:
                    self.buy()

        ########################################################################
        #  previous_signal current_signal   previous_position    current_position
        #          0              -1             is_long              close
        #          0              -1            != is_short            sell
        #
        #          1              -1             is_long              close
        #          1              -1            != is_short            sell
        #
        #        (-1)             -1

            elif current_signal == -1:
                if self.position.is_long:
                    self.position.close()

                if not self.position.is_short:
                    self.sell()

        ########################################################################
        #  previous_signal current_signal   previous_position    current_position
        #          1              0                                  close
        #
        #         -1              0                                  close
        #
        #          0              0                                  close

            elif current_signal == 0:
                if self.position:
                    self.position.close()

        self.previous_signal = current_signal

In [ ]:
def visualForBacktestML(train_df):

  good_signals = train_df[train_df['Label'] == 1].copy()
  bad_signals = train_df[train_df['Label'] == 0].copy()

  figure = make_subplots(rows=1, cols=1)

  # График цены закрытия и TEMA
  figure.add_trace(go.Scatter(x=train_df.index, y=train_df['Close'], name='Цена закрытия', line=dict(color='blue')), row=1, col=1)
  figure.add_trace(go.Scatter(x=good_signals.index, y=good_signals['Close'], mode='markers',
                            name='Покупка', marker=dict(symbol='triangle-up', size=10, color='green')), row=1, col=1)
  figure.add_trace(go.Scatter(x=bad_signals.index, y=bad_signals['Close'], mode='markers',
                            name='Продажа', marker=dict(symbol='triangle-down', size=10, color='red')), row=1, col=1)

  # Настройка макета графика
  figure.update_layout(height=800, title='Визуализация прибыльных и убыточных сделок')
  figure.update_yaxes(title_text='Цена', row=1, col=1)

  figure.show()

  return figure

Проверка работы стратегии с использованием формируемой модели машинного обучения и библиотеки backtesting

In [ ]:
#Проверка работы стратегии с использованием модели машинного обучения
def backtestWithML(strategy, data, test_data, ml_modelname=None, ml_model=None, model_pred=None):

    #train_df = signals.copy()
    train_signals, train_conditions, datadf = strategy.generate_signals(data)
    train_df = train_signals.copy()

    #train_conditions = conditions.copy()
    #bt_df = signals.copy()

    #print("Разделение на трейн и тест ")
    #split_value = int(len(bt_df) * 0.6)
    #train_df = bt_df.iloc[:split_value]
    ##
    #test_df = bt_df.iloc[:split_value]
    #test_df = bt_df.iloc[split_value:]#.reset_index(drop=True)



    bt_df = train_df.reset_index()
    bt_df.columns = ['Date', 'signal']
    bt_df['shift'] = bt_df['signal'].shift()
    bt_df['shift'] = bt_df['shift'].fillna(0)
    bt_df['action_x'] = bt_df['signal'].ne(bt_df['shift'])

    bt_df['action_id'] = 0
    bt_df['action_id'] = bt_df['signal'].ne(bt_df['signal'].shift()).cumsum()
    bt_df.columns = bt_df.columns.str.capitalize()

    data_backtest = datadf.copy()

    data_backtest.reset_index()
    data_backtest.drop('Signal', axis=1, inplace=True)
    data_merge = pd.merge(bt_df, data_backtest, on='Date', how='inner').dropna()

    data_merge.rename(columns={'Date': 'Datetime'}, inplace=True)
    data_merge["Datetime"] = pd.to_datetime(data_merge["Datetime"])
    data_merge.set_index('Datetime', inplace=True)
    data_merge.columns = data_merge.columns.str.capitalize()

    #Успешные и убыточные сделки
    # групируем по id оставляя только первые строки каждой сделки - это наши точки смены сигнала

    data_merge = data_merge.reset_index()
    train_df = data_merge.groupby('Action_id').first().reset_index()
    # добавим столбец с профитом
    train_df['profit'] = 0.0

    # Смещаем столбцы 'close' и 'signal', чтобы получить данные следующего бара
    train_df['next_close'] = train_df['Close'].shift(-1)
    train_df['next_signal'] = train_df['Signal'].shift(-1)

    # Рассчитываем PnL (отчет о прибылях и убытках)
    train_df['profit'] = (train_df['next_close'] - train_df['Close']) * train_df['Signal']

    # Заполняем PnL значением 0 для последнего бара, так как для него нет следующего бара
    train_df['profit'] = train_df['profit'].fillna(0)

    # Добавляем целевую переменную : 0 - cделка принесла убыток, 1 - сделка принесла прибыль
    train_df['Label'] = train_df['profit'].apply(lambda x: 1 if x >= 0 else 0)

    #!!!!!!2.2 Label = profit >= 0 - “нулевая прибыль” считается выигрышем
    #Это искусственно улучшает win-rate, особенно если много нулевых/почти нулевых движений.
    #Как лучше
    #- Label = profit > 0
    #- или event-based: profit > fee + slippage (т.е. прибыль должна перекрыть издержки)

    train_df = train_df[train_df['Signal'] != 0]
    train_df.set_index('Datetime', inplace=True)
    #train_df[['Close', 'next_close' , 'Signal', 'next_signal', 'profit', 'Label']]

    # Визуализация
    #visualForBacktestML(train_df)

    ##------------------

    #X_trainbkt, X_testbkt, y_trainbkt, y_testbkt = train_test_split(
    #train_df, train_df['Label'], test_size=0.3, random_state=42, stratify=train_df['Label']
    #)

    display("Создаем объект класса Backtest")

    X_train = train_df[['Signal', 'Open', 'High', 'Low', 'Close', 'Volume', 'Label']]
    #2.1 Label строится от будущей цены (shift(-1)) и затем используется как фича
    #Смотри у тебя:
    #python
    #train_df['next_close'] = train_df['Close'].shift(-1)
    #profit = (next_close - Close) * Signal
    #Label = 1 if profit >= 0 else 0
    #дальше формируется X_train = train_df[['Signal','Open','High','Low','Close','Volume','Label']] и делается Backtest(X_train, …)
    #Проблема (критично):
    #Label вычислен из будущего (через next_close), но ты кладёшь его в датафрейм, который потом подаётся в бэктест как входные данные. Даже если стратегия его напрямую не использует, это опасная утечка (и очень часто приводит к “магическим” результатам, особенно если где-то случайно используется колонка).
    #Как поправить - Никогда не держать Label, next_close, profit внутри датафрейма, который идёт в Backtest.
    #Делай отдельный df для обучения/оценки и отдельный OHLCV+Signal для бэктеста.

    # Создаем объект класса Backtest
    bt = Backtest(X_train, TemaGoldenCrossStrategy, cash=1_000_000, commission=.002, exclusive_orders=True, finalize_trades=True) # сделки идут последовательно


    display("Запускаем бэктест")

    # Запускаем бэктест
    stats = bt.run()

    ###bt.plot()

    db1 = stats[:27]

    # Выводим статистику
    #display("Выводим статистику")
    #print(stats[:27])

    ##------------------


    # И оставляем только те строки где мы входили в позицию
    #display("Оставляем только те строки где мы входили в позицию")
    #train_df = train_df[train_df['Signal'] != 0]

    # Удаляем вспомогательные столбцы
    train_df.drop(columns=['next_close', 'next_signal'], inplace=True)

    # Разделяем признаки и метки
    display("Разделяем признаки и метки")
    train_conditions.columns = train_conditions.columns.str.capitalize()
    train_conditions.drop('Signal', axis=1, inplace=True)

    X_train = train_df.filter(train_conditions.columns, axis=1)
    #X_train = train_df[['tema', 'macd', 'macd_signal', 'close', 'signal']]
    y_train = train_df['Label']


    display("RobustScaler")
    #scaler = StandardScaler()
    scaler = RobustScaler()
    x_scaled = scaler.fit_transform(X_train)
    #https://sky.pro/wiki/python/primer-ispolzovaniya-random-forest-classifier/

    # #обучаем модель
    #model = RandomForestClassifier(n_estimators=100, random_state=42)
    # # Определение гиперпараметров для настройки
    #param_grid = {
    #     'n_estimators': [50, 100, 200],
    #     'max_depth': [None, 10, 20, 30],
    #     'min_samples_split': [2, 5, 10],
    #     'min_samples_leaf': [1, 2, 4]
    # }
    # # Создание экземпляра GridSearchCV
    #grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=3, n_jobs=-1, verbose=2)
    # # Поиск лучших параметров
    #grid_search.fit(x_scaled, y_train)
    # # Вывод лучших параметров
    #print(f"Лучшие параметры: {grid_search.best_params_}")
    # # Создание модели с лучшими параметрами
    #model = grid_search.best_estimator_
    #model = RandomForestClassifier(n_estimators=100, random_state=42, max_depth = None, min_samples_leaf = 4, min_samples_split=2)

    #обучаем модель
    #model = RandomForestClassifier(random_state=42)
    model = CatBoostClassifier(random_state=42)
    model.fit(x_scaled, y_train,
              verbose = False,
              plot=False)
    if ml_modelname is not None :
      namemodel = ml_modelname
      model = joblib.load(namemodel)


    # Важность признаков
    feature_importance = pd.Series(model.feature_importances_, index=X_train.columns)
    print("Feature Importance:\n", feature_importance.sort_values(ascending=False))

    # повторяем все тоже самое с данными для теста
    display("Повторяем все тоже самое с данными для теста")

    test_signals, test_conditions, test_df = strategy.generate_signals(test_data)
    visual_signals = test_signals.copy()
    visual_signals = visual_signals.fillna(0)
    visual_signals = visual_signals.reindex(test_data.index, fill_value=0)
    close_prices = test_data['Close'].values
    if test_signals is None or test_signals.empty:
      return None
    test_signals = test_signals.fillna(0)
    test_signals = test_signals.reindex(test_data.index, fill_value=0)
    test_signals = test_signals.reset_index()
    test_signals.columns = ['Date', 'signal']
    test_df.drop('Signal', axis=1, inplace=True)
    test_df = pd.merge(test_signals, test_df, on='Date', how='inner').dropna()
    test_df.rename(columns={'Date': 'Datetime'}, inplace=True)
    test_df["Datetime"] = pd.to_datetime(test_df["Datetime"])
    test_df.set_index('Datetime', inplace=True)
    test_df['shift'] = test_df['signal'].shift()
    test_df['shift'] = test_df['shift'].fillna(0)
    test_df['action_x'] = test_df['signal'].ne(test_df['shift'])
    test_df['action_id'] = 0
    test_df['action_id'] = test_df['signal'].ne(test_df['signal'].shift()).cumsum()
    test_df = test_df.reset_index()
    test_df = test_df.groupby('action_id').first().reset_index()
    test_df['next_close'] = test_df['Close'].shift(-1)
    test_df['next_signal'] = test_df['signal'].shift(-1)
    test_df['profit'] = (test_df['next_close'] - test_df['Close']) * test_df['signal']
    test_df['profit'] = test_df['profit'].fillna(0)
    test_df['Label'] = test_df['profit'].apply(lambda x: 1 if x >= 0 else 0)

    #!!!!!!2.2 Label = profit >= 0 - “нулевая прибыль” считается выигрышем
    #Это искусственно улучшает win-rate, особенно если много нулевых/почти нулевых движений.
    #Как лучше
    #- Label = profit > 0
    #- или event-based: profit > fee + slippage (т.е. прибыль должна перекрыть издержки)
    #test_df = test_df[test_df['signal'] != 0]

    test_df.set_index('Datetime', inplace=True)
    test_df.columns = test_df.columns.str.capitalize()


    display("Для предсказания используем данные в столбацах ниже")
    # Для предсказания используем данные в столбацах condition
    #X_test = test_df[['tema', 'macd', 'macd_signal', 'close', 'signal']]
    test_conditions.columns = test_conditions.columns.str.capitalize()
    test_conditions.drop('Signal', axis=1, inplace=True)
    X_test = test_df.filter(test_conditions.columns, axis=1)
    y_test = test_df['Label']

    # делаем предсказание
    y_pred = model.predict(X_test)
    # вариант когда у нас уже есть модель
    if model_pred is not None:
      y_pred = model_pred.copy()

    # описание наших метрик
    # accuracy - точность нашей модели
    # precision - точность предсказания
    # recall - полнота предсказания
    # f1-score - среднее гармоническое точности и полноты
    # support - количество образцов в каждом классе
    # выводим предсказание
    display("Выводим предсказание")
    print(y_pred)
    # выведем нашу точность
    print(accuracy_score(y_test, y_pred))
    # выведем нашу матрицу
    print(confusion_matrix(y_test, y_pred))
    # выведем нашу классификационную отчет
    print(classification_report(y_test, y_pred))

    # Подготовим данные для бэктеста
    test_df['pred'] = y_pred
    test_df['pred'] = test_df['pred'].ffill()
    test_df.columns = test_df.columns.str.capitalize()
    test_df.loc[(test_df['Pred'] == 0) & (test_df['Signal'] != 0), 'Signal'] = 0
    # зануляем сделки предсказанные как убыточные
    #bt_df.loc[(bt_df['pred'] == 0) & (bt_df['Signal'] != 0), 'Signal'] = 0


    bt = Backtest(test_df, TemaGoldenCrossStrategy, cash=1000000, commission=.002, exclusive_orders=True, finalize_trades=True)

    # Запускаем бэктест
    stats = bt.run()

    # Выводим статистику
    print(stats[:27])

    display("Выводим график :")
    # выводим график

    bt.plot(
        plot_equity=True,
        plot_drawdown=True,
        relative_equity=False,
        superimpose=False #при date = 1h ошибка Invalid value for `superimpose`: Upsampling not supported
    )

    #backtest_strategy(strategy_params, test_df)

    display("Выводим Buy&Hold и GoldenCross :")

    db2 = stats[:27]
    db = pd.concat([db1, db2], axis = 1)
    db.columns = ['Buy&Hold', 'GoldenCross']
    display(db)

   # match = re.search(r"\d+\.\d+", db2.iloc[4])
   # if match:
   #   float_number = np.float(match.group(1))
   #   print(float_number)

    risk_adjusted_return_ml = (
            db2.iloc[7] *
            db2.iloc[12] *
            db2.iloc[13] *
            db2.iloc[7]
        ) / (1 + db2.iloc[17])

    print(f"risk_adjusted_return = {risk_adjusted_return_ml:.2f}")

    # Попытка отрисовки временного ряда с помощью не backtesting
    position_open = False
    positions = []
    equity = 1.0
    equity_curve = [equity]

    for i in range(1, len(visual_signals)):
            current_signal = visual_signals.iloc[i]
            current_date = visual_signals.index[i]

            if not position_open and current_signal != 0:
                # Открываем позицию
                position_open = True
                entry_price = close_prices[i]
                entry_signal = current_signal
                entry_date = current_date

            elif position_open and ((current_signal != 0 and current_signal != entry_signal) or i == len(visual_signals)-1):
                # Закрываем позицию
                exit_price = close_prices[i]
                profit = (exit_price - entry_price) / entry_price * entry_signal

                positions.append({
                    'entry_date': entry_date,
                    'exit_date': current_date,
                    'profit': float(profit)
                })
                equity *= (1.0 + profit)
                position_open = False

            equity_curve.append(float(equity))
    # Попытка отрисовки временного ряда с помощью не backtesting

    strategy.positions = positions
    strategy.equity = equity_curve
    strategy.signals = visual_signals

    roc = rocauc(model, X_test, y_test)

    return_ml = {
            'final_equity': db2.iloc[4], #final_equity,
            'n_trades': db2.iloc[21], #n_trades,
            'returns': db2.iloc[7], #returns,
            'max_drawdown': abs(db2.iloc[17]), #max_drawdown,
            'win_rate': db2.iloc[22], #win_rate,
            'sharpe_ratio': db2.iloc[12], #sharpe_ratio,
            'sortino_ratio': db2.iloc[13], #sortino_ratio,
            'profit_factor': db2.iloc[7], #profit_factor
            'rocauc': roc, #rocauc для модели
            'pred': y_pred.copy(), # запоминаем предсказание для набора
            'ml_model': joblib.dump(model, 'random_forest.joblib' + str(roc)),
            'ml_modelname': 'random_forest.joblib' + str(roc)
        }

    return return_ml

In [ ]:
# Класс для базовой стратегии
class BaseStrategy:
    def __init__(self):
        self.positions = []
        self.equity = []
        self.ticker = None

    def calculate_metrics(self, data):
        """Описание используемых метрик производительности:
           final_equity: Конечный капитал после завершения торгового периода. Показывает, насколько вырос или уменьшился начальный капитал в результате торговли.
           Используется для оценки общей эффективности стратегии. Чем выше конечный капитал, тем успешнее стратегия.
           n_trades: Количество сделок, совершенных за период тестирования. Показывает активность стратегии. Большое количество сделок может указывать на высокую частоту торговли, что может быть как преимуществом, так и недостатком в зависимости от контекста.
           returns: Общая доходность стратегии в процентах за период тестирования. Основной показатель прибыльности стратегии. Положительная доходность указывает на успешность стратегии, отрицательная — на убыточность.
           max_drawdown: Максимальная просадка капитала за период тестирования. Показывает наибольшее падение капитала от пика до минимума. Используется для оценки риска стратегии. Чем меньше просадка, тем стабильнее стратегия.
           win_rate: Процент прибыльных сделок от общего количества сделок. Показывает, насколько часто стратегия приносит прибыль. Высокий процент выигрышных сделок может указывать на стабильность стратегии.
           sharpe_ratio: Коэффициент Шарпа измеряет доходность с поправкой на риск. Чем выше значение, тем лучше стратегия с точки зрения доходности на единицу риска. Используется для сравнения стратегий с учетом риска. Высокий коэффициент Шарпа указывает на эффективное использование риска.
           sortino_ratio: Коэффициент Сортино, который измеряет доходность с поправкой на риск, учитывая только негативную волатильность. Аналогичен коэффициенту Шарпа, но фокусируется на риске убытков, что делает его более подходящим для оценки стратегий с асимметричным распределением доходности.
           profit_factor: Отношение общей прибыли к общему убытку. Показывает, насколько прибыльна стратегия по сравнению с убытками. Используется для оценки соотношения прибыли и убытков. Значение больше 1 указывает на прибыльность стратегии.
        """
        if not self.positions:
            return {
                'final_equity': 1.0,
                'n_trades': 0,
                'returns': 0,
                'max_drawdown': 0,
                'win_rate': 0,
                'sharpe_ratio': 0,
                'sortino_ratio': 0,
                'profit_factor': 0
            }

        # Расчет базовых метрик
        final_equity = self.equity[-1]
        n_trades = len(self.positions)
        returns = (final_equity - 1.0) * 100

        # Расчет максимальной просадки
        peak = 1.0
        drawdowns = []
        for eq in self.equity:
            if eq > peak:
                peak = eq
            drawdown = (peak - eq) / peak * 100
            drawdowns.append(drawdown)
        max_drawdown = max(drawdowns)

        # Расчет win rate
        profitable_trades = sum(1 for pos in self.positions if pos['profit'] > 0)
        win_rate = profitable_trades / n_trades * 100 if n_trades > 0 else 0

        # Расчет Sharpe и Sortino ratio
        daily_returns = pd.Series(self.equity).pct_change().dropna()
        if len(daily_returns) > 0:
            sharpe_ratio = np.sqrt(252) * daily_returns.mean() / daily_returns.std()
            downside_returns = daily_returns[daily_returns < 0]
            sortino_ratio = np.sqrt(252) * daily_returns.mean() / downside_returns.std() if len(downside_returns) > 0 else 0
        else:
            sharpe_ratio = sortino_ratio = 0

        # Расчет profit factor
        gross_profit = sum(pos['profit'] for pos in self.positions if pos['profit'] > 0)
        gross_loss = abs(sum(pos['profit'] for pos in self.positions if pos['profit'] < 0))
        profit_factor = gross_profit / gross_loss if gross_loss != 0 else 0

        return {
            'final_equity': final_equity,
            'n_trades': n_trades,
            'returns': returns,
            'max_drawdown': max_drawdown,
            'win_rate': win_rate,
            'sharpe_ratio': sharpe_ratio,
            'sortino_ratio': sortino_ratio,
            'profit_factor': profit_factor
        }

In [ ]:
# Стратегия 4: Золотой крест
#https://sergeytereshkin.ru/library/zolotoy-krest-signal-razvorota-i-metodika-poiska-na-grafike
class Strategy4(BaseStrategy):
    """
    «Золотой крест» — один из самых надежных бычьих сигналов технического анализа,
    позволяющий трейдерам структурировать вход в длинную позицию при строгом риск-менеджменте и подтверждении индикаторами.

    Выбор и настройка скользящих средних
    Оптимальные периоды для SMA
     - Для дневных и недельных графиков оптимальным сочетанием является SMA50/SMA200, поскольку SMA сглаживает шум и отражает среднесрочную и долгосрочную динамику цены.

    Использование EMA на коротких таймфреймах
     - На коротких таймфреймах (M15–H1) предпочтительнее EMA50/EMA200: EMA быстрее реагирует на последние изменения цены, что позволяет оперативнее фиксировать разворот, но требует дополнительной фильтрации шума.

    Бэктестинг настроек MA
     - Оптимальные параметры следует подбирать через бэктестинг: тестировать разные комбинации периодов,
       фиксируя доходность и максимальную просадку каждой стратегии.

    Подтверждающие индикаторы и фильтры
     - MACD как индикатор тренда
     - MACD подтверждает силу бычьего сигнала при росте гистограммы выше нулевой линии и пересечении сигнальной линии снизу вверх,
       что усиливает вероятность продолжения восходящего движения.

    RSI и оценка перекупленности
     - RSI в диапазоне 50–70 указывает на адекватный бычий импульс без перегрева рынка и помогает отсеивать ложные сигналы «золотого креста» во время флета.

    Анализ объемов и свечных паттернов
     - Дополнительным фильтром служат объемы: рост торгового объема в момент пересечения показывает активное участие игроков и подтверждает значимость сигнала.
       Бычьи свечные формации, такие как поглощение или «утренняя звезда», рядом с точкой пересечения усиливают доверие к сигналу.

    Источник Yandex:
    Некоторые оптимальные параметры стратегии Golden Cross в трейдинге:
      - Первичные условия: пересечение MA(50) над MA(200) с закреплением выше на 2+ торговых дня.
      - Направленность скользящих средних: обе MA направлены вверх под углом не менее 5°.
      - Расстояние между MA: минимальный разрыв 1,5% для исключения случайных пересечений.
      - Объёмное подтверждение: превышение 20-дневного среднего объёма на 30%+.
      - Дополнительные фильтры качества:
         RSI(14) в диапазоне 45–70 (для исключения экстремальных состояний перекупленности),
         MACD выше нулевой линии (для подтверждения смены импульса на бычий),
         отсутствие сильных уровней сопротивления в ближайших 8–12% от цены пересечения,
         макроэкономический фон (отсутствие ожидаемых негативных событий в ближайшие 4–6 недель).

    """
    def __init__(self, bb_period=20, bb_std=2, rsi_period=14, sma=10, ema_period=4, ma_period=10, macd_fast=12, macd_slow=26, macd_signal=9, stoch_k=14, stoch_d=3, stoch_slow=3):
        super().__init__()
        self.bb_period = int(bb_period)
        self.bb_std = float(bb_std)
        self.rsi_period = int(rsi_period)
        self.sma = int(sma)
        self.ema_period = int(ema_period)
        self.ma_period = int(ma_period)
        self.macd_fast = int(macd_fast)
        self.macd_slow = int(macd_slow)
        self.macd_signal = int(macd_signal)
        self.stoch_k = int(stoch_k)
        self.stoch_d = int(stoch_d)
        self.stoch_slow = int(stoch_slow)

    def get_params(self):
        """Возвращает текущие гиперпараметры стратегии"""
        return {
            'bb_period': self.bb_period,
            'bb_std': self.bb_std,
            'rsi_period': self.rsi_period,
            'sma': self.sma,
            'ema_period': self.ema_period,
            'ma_period': self.ma_period,
            'macd_fast': self.macd_fast,
            'macd_slow': self.macd_slow,
            'macd_signal': self.macd_signal,
            'stoch_k': self.stoch_k,
            'stoch_d': self.stoch_d,
            'stoch_slow': self.stoch_slow,
        }

    def generate_signals(self, data):
        try:
            df = data.copy()

            close_prices = df['Close'].values.astype(float).flatten()
            open_prices = df['Open'].values.astype(float).flatten()
            high_prices = df['High'].values.astype(float).flatten()
            low_prices = df['Low'].values.astype(float).flatten()
            volume = df['Volume'].values.astype(float).flatten()

            #Полосы Боллинджера - Уровни поддержки и сопротивления
            df['BB_middle'] = ta.SMA(close_prices, timeperiod=self.bb_period)
            std_dev = ta.STDDEV(close_prices, timeperiod=self.bb_period)
            df['BB_upper'] = df['BB_middle'] + self.bb_std * std_dev
            df['BB_lower'] = df['BB_middle'] - self.bb_std * std_dev

            df['sma'] = ta.SMA(close_prices, timeperiod=self.sma)
            df['ma_period'] = ta.MA(close_prices, timeperiod=self.ma_period)
            df['RSI'] = ta.RSI(close_prices, timeperiod=self.rsi_period)
            #df['obv'] = np.where(df['Close'] > df['Close'].shift(1), df['Volume'], np.where(df['Close'] < df['Close'].shift(1), -df['Volume'], 0)).cumsum()
            df['obv'] = ta.OBV(close_prices, volume)
            df['engulfing'] = ta.CDLENGULFING(open_prices, high_prices, low_prices, close_prices)
            df['morningstar'] = ta.CDLMORNINGSTAR(open_prices, high_prices, low_prices, close_prices)
            df['adosc'] = ta.ADOSC(high_prices, low_prices, close_prices, volume)
            slowk, slowd = ta.STOCH(high_prices,
                                   low_prices,
                                   close_prices,
                                   fastk_period=self.stoch_k,
                                   slowk_period=self.stoch_d,
                                   slowd_period=self.stoch_slow)
            df['slowk'] = slowk
            df['slowd'] = slowd
            df['doji'] = ta.CDLDOJI(open_prices, high_prices, low_prices, close_prices)
            df['hammer'] = ta.CDLHAMMER(open_prices, high_prices, low_prices, close_prices)
            df['atr14'] = ta.ATR(high_prices, low_prices, close_prices, timeperiod=14)
            df['sar'] = ta.SAR(high_prices, low_prices, acceleration=0, maximum=0)
            df['cci'] = ta.CCI(high_prices, low_prices, close_prices, timeperiod=14)
            df['adx'] = ta.ADX(high_prices, low_prices, close_prices, timeperiod=14)
            df['mfi'] = ta.MFI(high_prices, low_prices, close_prices, volume, timeperiod=14)
            df['linearreg_angle'] = ta.LINEARREG_ANGLE(close_prices, timeperiod=14)

            macd, signal, _ = ta.MACD(close_prices,
                              fastperiod=self.macd_fast,
                              slowperiod=self.macd_slow,
                              signalperiod=self.macd_signal)

            df['MACD'] = macd
            df['Signal'] = signal
            #df = df.fillna(method='ffill').fillna(method='bfill')
            df = df.ffill().copy()
            signals = pd.Series(index=df.index, data=0)

            long_condition = ((df['engulfing'] > 0) | (df['morningstar'] > 0)) #& ((df['Close'] < df['sma']) & (df['Close'].shift(1) >= df['sma'].shift(1))) & (df['MACD'] > df['Signal']) & (df['RSI'] > 50) & (df['RSI'] < 70) & (df['obv'] > 0)
            #long_condition =  (df['RSI'] > 50) & (df['sma_period'] > 50) & (df['Close'] > df['EMA']) & (df['MACD'] > df['Signal']) & (df['obv'] > 0)
            #short_condition =  (df['RSI'] < 70) & (df['sma_period'] < 200) & (df['Close'] < df['EMA']) & (df['MACD'] < df['Signal']) & (df['obv'] < 0)
            #short_condition = Стоп-лосс | тейк-профит | трейлинг-стоп
            short_condition =  (((df['sma'] < 50)) | ((df['Close'] < df['sma']) & (df['Close'].shift(1) >= df['sma'].shift(1)))) | ((df['RSI'] > 50) & (df['MACD'] < df['Signal'])) | (df['Close'] > df['BB_upper'])
            signals[long_condition] = 1
            signals[short_condition] = -1
            signals = signals.reindex_like(data)


            conditions = df.copy()
            conditions = conditions.reset_index()
            conditions = df.filter(['BB_middle', 'BB_upper',
                                    'BB_lower', 'sma', 'ma_period', 'RSI', 'obv', 'engulfing',
                                    'morningstar', 'MACD', 'slowk', 'slowd', 'doji', 'hammer', 'atr14', 'sar',
                                    'adosc', 'linearreg_angle', 'cci','adx','mfi', 'Signal'], axis=1)
            conditions = conditions.dropna()

            return signals, conditions, df
        except Exception as e:
            print(f"Ошибка в generate_signals для Strategy4: {str(e)}")
            return None

In [ ]:
# Стратегия 3: RSI + Candlestick Patterns
class Strategy3(BaseStrategy):
    """
    Комбинированная стратегия разворота тренда, использующая:
    - RSI (Relative Strength Index) - для определения перекупленности/перепроданности
    - Паттерны свечей - для подтверждения разворота (Doji, Hammer, Engulfing)

    Бизнес-логика стратегии:
    1. Основной принцип:
       - Поиск точек разворота в перекупленных/перепроданных зонах
       - Использование паттернов свечей для подтверждения разворота

    2. Условия для входа в длинную позицию (Long):
       - RSI находится в зоне перепроданности (< 30)
       - Формируется один из бычьих паттернов:
         * Doji (свеча неопределенности)
         * Hammer (молот)
         * Bullish Engulfing (бычье поглощение)

    3. Условия для входа в короткую позицию (Short):
       - RSI находится в зоне перекупленности (> 70)
       - Формируется один из медвежьих паттернов:
         * Doji (свеча неопределенности)
         * Inverted Hammer (перевернутый молот)
         * Bearish Engulfing (медвежье поглощение)

    4. Управление рисками:
       - RSI фильтрует слабые сигналы
       - Требуется подтверждение паттернами свечей
       - Учитывается сила сигнала разворота

    Особенности настройки:
    - rsi_period: период RSI (по умолчанию 14)
    - Паттерны свечей имеют фиксированные правила идентификации

    Преимущества стратегии:
    - Сочетание технического индикатора и визуального анализа
    - Четкие правила входа и выхода
    - Возможность раннего обнаружения разворотов тренда
    """
    def __init__(self, rsi_period=14):
        super().__init__()
        self.rsi_period = int(rsi_period)

    def get_params(self):
        """Возвращает текущие гиперпараметры стратегии"""
        return {
            'rsi_period': self.rsi_period
        }

    def generate_signals(self, data):
        try:
            df = data.copy()
            close_prices = df['Close'].values.astype(float).flatten()
            open_prices = df['Open'].values.astype(float).flatten()
            high_prices = df['High'].values.astype(float).flatten()
            low_prices = df['Low'].values.astype(float).flatten()
            df['RSI'] = ta.RSI(close_prices, timeperiod=self.rsi_period)
            df['doji'] = ta.CDLDOJI(open_prices, high_prices, low_prices, close_prices)
            df['hammer'] = ta.CDLHAMMER(open_prices, high_prices, low_prices, close_prices)
            df['engulfing'] = ta.CDLENGULFING(open_prices, high_prices, low_prices, close_prices)
            df = df.ffill().copy()
            #df = df.fillna(method='ffill').fillna(method='bfill')
            signals = pd.Series(index=df.index, data=0)
            long_condition = ((df['doji'] > 0) | (df['hammer'] > 0) | (df['engulfing'] > 0)) & (df['RSI'] < 30)
            short_condition = ((df['doji'] < 0) | (df['hammer'] < 0) | (df['engulfing'] < 0)) & (df['RSI'] > 70)
            signals[long_condition] = 1
            signals[short_condition] = -1
            signals = signals.reindex_like(data)

            conditions = df.copy()
            conditions = conditions.reset_index()
            conditions = df.filter(['RSI', 'doji',
                                    'hammer', 'engulfing'], axis=1)
            conditions = conditions.dropna()

            return signals, conditions, df
        except Exception as e:
            print(f"Ошибка в generate_signals для Strategy3: {str(e)}")
            return None

In [ ]:
class Strategy2(BaseStrategy):
    """
    Стратегия торговли на отскок (Mean Reversion), использующая:
    - Bollinger Bands - для определения волатильности и экстремальных значений цены
    - Stochastic Oscillator - для подтверждения разворота

    Бизнес-логика стратегии:
    1. Основной принцип:
       - Торговля от краев полос Боллинджера к средней линии
       - Использование стохастика для подтверждения сигналов разворота

    2. Условия для входа в длинную позицию (Long):
       - Цена находится ниже нижней полосы Боллинджера (перепроданность)
       - Линия %K стохастика пересекает линию %D снизу вверх (подтверждение разворота вверх)

    3. Условия для входа в короткую позицию (Short):
       - Цена находится выше верхней полосы Боллинджера (перекупленность)
       - Линия %K стохастика пересекает линию %D сверху вниз (подтверждение разворота вниз)

    4. Управление рисками:
       - Полосы Боллинджера автоматически адаптируются к волатильности
       - Стохастик подтверждает потенциал разворота
       - Торговля против тренда только при сильных сигналах

    Особенности настройки:
    - bb_period: период Bollinger Bands (по умолчанию 20)
    - bb_std: количество стандартных отклонений (по умолчанию 2)
    - stoch_k/d/slow: параметры стохастика, влияющие на его чувствительность
    """
    def __init__(self, bb_period=20, bb_std=2, stoch_k=14, stoch_d=3, stoch_slow=3, rsi_period = 14):
        super().__init__()
        self.bb_period = int(bb_period)
        self.bb_std = float(bb_std)
        self.stoch_k = int(stoch_k)
        self.stoch_d = int(stoch_d)
        self.stoch_slow = int(stoch_slow)
        self.rsi_period = int(rsi_period)

    def get_params(self):
        """Возвращает текущие гиперпараметры стратегии"""
        return {
            'bb_period': self.bb_period,
            'bb_std': self.bb_std,
            'stoch_k': self.stoch_k,
            'stoch_d': self.stoch_d,
            'stoch_slow': self.stoch_slow,
            'rsi_period': self.rsi_period
        }

    def generate_signals(self, data):
        try:
            df = data.copy()
            close_prices = df['Close'].values.astype(float).flatten()
            high_prices = df['High'].values.astype(float).flatten()
            low_prices = df['Low'].values.astype(float).flatten()
            df['BB_middle'] = ta.SMA(close_prices, timeperiod=self.bb_period)
            std_dev = ta.STDDEV(close_prices, timeperiod=self.bb_period)
            df['BB_upper'] = df['BB_middle'] + self.bb_std * std_dev
            df['BB_lower'] = df['BB_middle'] - self.bb_std * std_dev
            df['RSI'] = ta.RSI(close_prices, timeperiod=self.rsi_period)
            slowk, slowd = ta.STOCH(high_prices,
                                   low_prices,
                                   close_prices,
                                   fastk_period=self.stoch_k,
                                   slowk_period=self.stoch_d,
                                   slowd_period=self.stoch_slow)
            df['slowk'] = slowk
            df['slowd'] = slowd
            df = df.ffill().copy()
            #df = df.fillna(method='ffill').fillna(method='bfill')
            signals = pd.Series(index=df.index, data=0)
            long_condition = (df['Close'] < df['BB_lower']) & (df['slowk'] > df['slowd']) & (df['RSI'] < 70)
            short_condition = (df['Close'] > df['BB_upper']) & (df['slowk'] < df['slowd']) & (df['RSI'] > 30)
            signals[long_condition] = 1
            signals[short_condition] = -1
            signals = signals.reindex_like(data)

            conditions = df.copy()
            conditions = conditions.reset_index()
            conditions = df.filter(['BB_middle', 'BB_upper',
                                    'BB_lower', 'RSI', 'slowk', 'slowd', 'Close'], axis=1)
            conditions = conditions.dropna()

            return signals, conditions, df
        except Exception as e:
            print(f"Ошибка в generate_signals для Strategy2: {str(e)}")
            return None

In [ ]:
class Strategy1(BaseStrategy):
    """
    Комбинированная трендово-импульсная стратегия, использующая:
    - EMA (Exponential Moving Average) - для определения тренда
    - RSI (Relative Strength Index) - для определения перекупленности/перепроданности
    - MACD (Moving Average Convergence Divergence) - для определения моментума и точек входа/выхода

    Бизнес-логика стратегии:
    1. Определение тренда:
       - Цена выше EMA = восходящий тренд
       - Цена ниже EMA = нисходящий тренд

    2. Условия для входа в длинную позицию (Long):
       - Цена находится выше EMA (подтверждение восходящего тренда)
       - RSI < 70 (нет перекупленности)
       - MACD пересекает Signal Line снизу вверх (сигнал усиления восходящего импульса)

    3. Условия для входа в короткую позицию (Short):
       - Цена находится ниже EMA (подтверждение нисходящего тренда)
       - RSI > 30 (нет перепроданности)
       - MACD пересекает Signal Line сверху вниз (сигнал усиления нисходящего импульса)

    4. Управление рисками:
       - RSI используется как фильтр для предотвращения входа в перекупленной/перепроданной зоне
       - EMA подтверждает направление тренда
       - MACD подтверждает силу импульса

    Особенности настройки:
    - ema_period: период EMA (по умолчанию 20) - чем больше период, тем более долгосрочный тренд отслеживается
    - rsi_period: период RSI (по умолчанию 14) - влияет на чувствительность индикатора к изменениям цены
    - macd_fast/slow/signal: периоды MACD - влияют на скорость реакции на изменение тренда
    """
    def __init__(self, ema_period=20, rsi_period=14, macd_fast=12, macd_slow=26, macd_signal=9):
        super().__init__()
        self.ema_period = int(ema_period)
        self.rsi_period = int(rsi_period)
        self.macd_fast = int(macd_fast)
        self.macd_slow = int(macd_slow)
        self.macd_signal = int(macd_signal)

    def get_params(self):
        """Возвращает текущие гиперпараметры стратегии"""
        return {
            'ema_period': self.ema_period,
            'rsi_period': self.rsi_period,
            'macd_fast': self.macd_fast,
            'macd_slow': self.macd_slow,
            'macd_signal': self.macd_signal
        }

    def generate_signals(self, data):
        try:
            df = data.copy()
            close_prices = df['Close'].values.astype(float).flatten()
            df['EMA'] = ta.EMA(close_prices, timeperiod=self.ema_period)
            df['RSI'] = ta.RSI(close_prices, timeperiod=self.rsi_period)
            macd, signal, _ = ta.MACD(close_prices,
                                      fastperiod=self.macd_fast,
                                      slowperiod=self.macd_slow,
                                      signalperiod=self.macd_signal)
            df['MACD'] = macd
            df['Signal'] = signal
            df = df.ffill().copy()
            #df = df.fillna(method='ffill').fillna(method='bfill')
            signals = pd.Series(index=df.index, data=0)
            long_condition = (df['Close'] > df['EMA']) & (df['RSI'] < 70) & (df['MACD'] > df['Signal'])
            short_condition = (df['Close'] < df['EMA']) & (df['RSI'] > 30) & (df['MACD'] < df['Signal'])
            signals[long_condition] = 1
            signals[short_condition] = -1
            signals = signals.reindex_like(data)

            conditions = df.copy()
            conditions = conditions.reset_index()
            conditions = df.filter(['EMA', 'RSI',
                                    'MACD', 'Signal', 'Close'], axis=1)
            conditions = conditions.dropna()

            return signals, conditions, df
        except Exception as e:
            print(f"Ошибка в generate_signals для Strategy1: {str(e)}")
            return None

In [ ]:
# Определение пространств параметров для оптимизации
param_spaces = {
    'Strategy1': {
        'ema_period': hp.quniform('ema_period', 10, 50, 1),
        'rsi_period': hp.quniform('rsi_period', 7, 21, 1),
        'macd_fast': hp.quniform('macd_fast', 8, 20, 1),
        'macd_slow': hp.quniform('macd_slow', 21, 40, 1),
        'macd_signal': hp.quniform('macd_signal', 5, 15, 1)
    },
    'Strategy2': {
        'bb_period': hp.quniform('bb_period', 10, 50, 1),
        'bb_std': hp.uniform('bb_std', 1.5, 3.0),
        'stoch_k': hp.quniform('stoch_k', 7, 21, 1),
        'stoch_d': hp.quniform('stoch_d', 3, 7, 1),
        'stoch_slow': hp.quniform('stoch_slow', 3, 7, 1),
        'rsi_period': hp.quniform('rsi_period', 7, 21, 1)
    },
    'Strategy3': {
        'rsi_period': hp.quniform('rsi_period', 7, 21, 1)
    },
    'Strategy4': {
        'bb_period': hp.quniform('bb_period', 10, 50, 1),
        'bb_std': hp.uniform('bb_std', 1.5, 3.0),
        'rsi_period': hp.quniform('rsi_period', 7, 21, 1),
        'sma': hp.quniform('sma', 10, 50, 1),
        'ema_period': hp.quniform('ema_period', 10, 50, 1),
        'ma_period': hp.quniform('ma_period', 10, 50, 1),
        'macd_fast': hp.quniform('macd_fast', 8, 20, 1),
        'macd_slow': hp.quniform('macd_slow', 21, 40, 1),
        'macd_signal': hp.quniform('macd_signal', 5, 15, 1),
        'stoch_k': hp.quniform('stoch_k', 7, 21, 1),
        'stoch_d': hp.quniform('stoch_d', 3, 7, 1),
        'stoch_slow': hp.quniform('stoch_slow', 3, 7, 1),
    }
}

In [ ]:
# Функция для бэктестирования Buy & Hold стратегии
def backtest_buy_hold(data):
    """Бэктестирование Buy & Hold стратегии"""
    initial_price = float(data['Close'].iloc[0])
    final_price = float(data['Close'].iloc[-1])
    returns = (final_price - initial_price) / initial_price * 100

    daily_returns = data['Close'].pct_change().dropna()

    if len(daily_returns) > 0:
        sharpe_ratio = np.sqrt(252) * daily_returns.mean() / daily_returns.std()
        downside_returns = daily_returns[daily_returns < 0]
        sortino_ratio = np.sqrt(252) * daily_returns.mean() / downside_returns.std() if len(downside_returns) > 0 else 0
    else:
        sharpe_ratio = sortino_ratio = 0

    rolling_max = data['Close'].expanding().max()
    drawdowns = (rolling_max - data['Close']) / rolling_max
    max_drawdown = float(drawdowns.max() * 100)

    return {
        'final_equity': 1 + returns / 100,
        'n_trades': 1,
        'returns': returns,
        'max_drawdown': max_drawdown,
        'win_rate': 100.0 if returns > 0 else 0.0,
        'sharpe_ratio': float(sharpe_ratio),
        'sortino_ratio': float(sortino_ratio),
        'profit_factor': float('inf') if returns > 0 else 0.0
    }

In [ ]:
def optimize_strategy(strategy_class, data, param_space):
    def objective(params):
        strategy = strategy_class(**params)
        metrics, conditions, signals, df = backtest_strategy(strategy, data)
        if metrics:
            return {'loss': -metrics['profit_factor'], 'status': STATUS_OK}
        else:
            return {'loss': 0, 'status': STATUS_OK}

    trials = Trials()
    best = fmin(fn=objective,
                space=param_space,
                algo=tpe.suggest,
                max_evals=50,
                trials=trials)

    return best

In [ ]:
def format_metric(value):
    """Форматирует число с двумя знаками после точки, если есть дробная часть"""
    if isinstance(value, (int, float)):
        return round(value, 2) if not value.is_integer() else int(value)
    return value

In [ ]:
# Функция для создания сводной таблицы результатов
def create_summary_table(results, instrument):
    """Создание сводной таблицы результатов"""
    metrics = ['final_equity', 'n_trades', 'returns', 'max_drawdown',
               'win_rate', 'sharpe_ratio', 'sortino_ratio', 'profit_factor']

    # Создаем MultiIndex для более структурированного отображения
    index_tuples = []
    data = []

    # Buy & Hold результаты
    if 'Buy & Hold' in results and 'full' in results['Buy & Hold']:
        bh_metrics = results['Buy & Hold']['full']
        index_tuples.append(('Buy & Hold', 'Full'))
        data.append({
            'Days': len(results['Buy & Hold']['full_data']),
            'Hyperparameters': 'N/A',
            **{metric: format_metric(bh_metrics[metric]) for metric in metrics}
        })

    # Результаты торговых стратегий
    #for strategy in ['Strategy2', 'Strategy3', 'Strategy1', 'Strategy4']:
    for strategy in ['Strategy4']:
        if strategy in results:
            for dataset in ['train_default', 'test','test_ml', 'test_neu', 'test_chronos', 'valid']:
                if dataset in results[strategy]:
                    metrics_data = results[strategy][dataset]

                    # Определяем, какие гиперпараметры использовать
                    if dataset == 'train_default':
                        hyperparams = results[strategy].get('train_default_params', 'N/A')
                    elif dataset == 'test':
                        hyperparams = results[strategy].get('optimized_params', 'N/A')
                    elif dataset == 'test_ml':
                        hyperparams = results[strategy].get('optimized_params_ml', 'N/A')
                    elif dataset == 'test_neu':
                        hyperparams = results[strategy].get('optimized_params_neu', 'N/A')
                    elif dataset == 'test_chronos':
                        hyperparams = results[strategy].get('optimized_params_chronos', 'N/A')
                    elif dataset == 'valid':
                        # Для Valid используем гиперпараметры, оптимизированные на объединенном наборе Train и Test
                        hyperparams = results[strategy].get('optimized_params_combined', 'N/A')

                    days = len(results[strategy][f'{dataset}_data'])

                    # Заменяем "train_default" на "Train"
                    dataset_name = 'Train' if dataset == 'train_default' else dataset.capitalize()

                    # Форматируем гиперпараметры с двумя знаками после точки, если есть дробная часть
                    formatted_hyperparams = {}
                    if hyperparams != 'N/A':
                        for param, value in hyperparams.items():
                            formatted_hyperparams[param] = round(value, 2) if isinstance(value, float) else value
                    else:
                        formatted_hyperparams = 'N/A'

                    index_tuples.append((strategy, dataset_name))
                    data.append({
                        'Days': days,
                        'Hyperparameters': formatted_hyperparams,
                        **{metric: format_metric(metrics_data[metric]) for metric in metrics}
                    })

    # Создаем DataFrame с MultiIndex
    df = pd.DataFrame(data, index=pd.MultiIndex.from_tuples(index_tuples, names=['Strategy', 'Dataset']))

    # Форматируем таблицу для красивого отображения
    styled_df = df.style\
        .format({
            'final_equity': '{:.2f}',
            'returns': '{:.2f}%',
            'max_drawdown': '{:.2f}%',
            'win_rate': '{:.2f}%',
            'sharpe_ratio': '{:.2f}',
            'sortino_ratio': '{:.2f}',
            'profit_factor': '{:.2f}'
        })\
        .set_caption(f'Сводная таблица результатов бэктестирования стратегий для {instrument}')\
        .set_table_styles([
            {'selector': 'caption', 'props': [('text-align', 'center'), ('font-size', '16px'), ('font-weight', 'bold')]},
            {'selector': 'th', 'props': [('text-align', 'center'), ('background-color', '#f0f0f0')]},
            {'selector': 'td', 'props': [('text-align', 'right')]}
        ])\
        .background_gradient(subset=['profit_factor'], cmap='RdYlGn')\
        .background_gradient(subset=['returns'], cmap='RdYlGn')

    return styled_df

In [ ]:
def analyze_trades(strategy, data, signals):
    """ Анализ фактических сделок на основе сигналов и ценовых данных. Возвращает список сделок с точками входа/выхода и прибылью. """
    trades = []
    in_position = False
    entry_price = 0
    entry_date = None
    position_type = None  # 'long' or 'short'
    for i in range(len(data)):
        current_date = data.index[i]
        current_price = data['Close'].iloc[i]
        is_dataframe = isinstance(signals, pd.DataFrame)
        if is_dataframe:
          current_signal = signals['Signal'].iloc[i]
        elif not is_dataframe:
          current_signal = signals.iloc[i]
        if not in_position and current_signal != 0:
            # Opening a position
            in_position = True
            entry_price = current_price
            entry_date = current_date
            position_type = 'long' if current_signal == 1 else 'short'
        elif in_position:
            # Check for closing conditions
            should_close = (
                (position_type == 'long' and current_signal == -1) or
                (position_type == 'short' and current_signal == 1) or
                (i == len(data) - 1)  # Close at the end of the period
            )
            if should_close:
                # Calculate profit
                profit = (
                    (current_price - entry_price) / entry_price * 100
                    if position_type == 'long'
                    else (entry_price - current_price) / entry_price * 100
                )
                trades.append({
                    'entry_date': entry_date,
                    'entry_price': entry_price,
                    'exit_date': current_date,
                    'exit_price': current_price,
                    'type': position_type,
                    'profit': profit
                })
                in_position = False
                entry_price = 0
                entry_date = None
                position_type = None
    return trades

In [ ]:
# Функция оценки стратегических показателей и расчета доходности с поправкой на риск
def calculate_risk_adjusted_returns(metrics):
  #https://www.wallstreetprep.com/knowledge/risk-adjusted-return/
    """Risk-Adjusted Returns позволяет выбрать стратегию, которая приносит доходность с минимальным риском..
       Он позволяет сравнивать стратегии не только по их абсолютной доходности, но и по тому, насколько эффективно они используют риск для достижения этой доходности.
       Оценить, насколько стратегия эффективно использует риск для достижения доходности. Это позволяет сравнивать стратегии, которые могут иметь схожую доходность, но разный уровень риска.
       Компоненты формулы: returns: Общая доходность стратегии. Чем выше доходность, тем выше значение метрики.
                           sharpe_ratio: Коэффициент Шарпа, который измеряет доходность с поправкой на общий риск (волатильность). Чем выше коэффициент Шарпа, тем лучше стратегия использует риск для получения доходности.
                           sortino_ratio: Коэффициент Сортино, который измеряет доходность с поправкой на риск убытков (негативную волатильность). Чем выше коэффициент Сортино, тем лучше стратегия управляет риском убытков.
                           profit_factor: Отношение общей прибыли к общему убытку. Чем выше значение, тем больше прибыль по сравнению с убытками.
                           max_drawdown: Максимальная просадка капитала. Чем меньше просадка, тем стабильнее стратегия. В формуле используется 1 + max_drawdown, чтобы избежать деления на ноль и уменьшить влияние больших просадок.
        Логика расчета: В числителе стоит произведение доходности, коэффициента Шарпа, коэффициента Сортино и фактора прибыли. Это позволяет учитывать как абсолютную доходность, так и эффективность управления риском.
                        В знаменателе - метрика максимальной просадки, что снижает значение метрики, если стратегия имеет высокий уровень риска (большие просадки).
    """
    if not metrics:
        return float('-inf')

    # Нормализуем доходность по показателям риска
    risk_adjusted_return = (
        metrics['returns'] *
        metrics['sharpe_ratio'] *
        metrics['sortino_ratio']
        #metrics['profit_factor']
    ) / (1 + metrics['max_drawdown'])  # Чтобы избежать деления на ноль.

    return risk_adjusted_return

In [ ]:

def plot_best_strategy(data, strategy, signals, equity_curve, strategy_results, trades, title):
    """ Функция визуализации, показывающая реальные сделки стратегии вместо сигналов """
    fig = make_subplots(rows=2, cols=1,
                        shared_xaxes=True,
                        vertical_spacing=0.03,
                        row_heights=[0.7, 0.3],
                        subplot_titles=(
                            "Price and Trades",  # Убираем дублирование заголовка
                            "Equity Curve"
                        ))

    # Candlestick chart
    fig.add_trace(
        go.Candlestick(
            x=data.index,
            open=data['Open'],
            high=data['High'],
            low=data['Low'],
            close=data['Close'],
            name='Price'
        ),
        row=1, col=1
    )

    # Отображение сделок
    long_entries = []
    long_exits = []
    short_entries = []
    short_exits = []

    for trade in trades:
        if trade['type'] == 'long':
            long_entries.append({
                'date': trade['entry_date'],
                'price': trade['entry_price'],
                'profit': trade['profit']
            })
            long_exits.append({
                'date': trade['exit_date'],
                'price': trade['exit_price'],
                'profit': trade['profit']
            })
        else:  # short trade
            short_entries.append({
                'date': trade['entry_date'],
                'price': trade['entry_price'],
                'profit': trade['profit']
            })
            short_exits.append({
                'date': trade['exit_date'],
                'price': trade['exit_price'],
                'profit': trade['profit']
            })

    # Отображение сделок long
    if long_entries:
        fig.add_trace(
            go.Scatter(
                x=[t['date'] for t in long_entries],
                y=[t['price'] * 0.99 for t in long_entries],
                mode='markers',
                marker=dict(
                    symbol='triangle-up',
                    size=12,
                    color='green',
                    line=dict(width=2)
                ),
                name='Long Entry',
                text=[f"Long Entry<br>Date: {t['date'].strftime('%Y-%m-%d')}<br>Price: {t['price']:.2f}<br>Profit: {t['profit']:.2f}%"
                      for t in long_entries],
                hoverinfo='text'
            ),
            row=1, col=1
        )

        fig.add_trace(
            go.Scatter(
                x=[t['date'] for t in long_exits],
                y=[t['price'] * 1.01 for t in long_exits],
                mode='markers',
                marker=dict(
                    symbol='triangle-down',
                    size=12,
                    color='blue',
                    line=dict(width=2)
                ),
                name='Long Exit',
                text=[f"Long Exit<br>Date: {t['date'].strftime('%Y-%m-%d')}<br>Price: {t['price']:.2f}<br>Profit: {t['profit']:.2f}%"
                      for t in long_exits],
                hoverinfo='text'
            ),
            row=1, col=1
        )

    # Отображение сделок Short
    if short_entries:
        fig.add_trace(
            go.Scatter(
                x=[t['date'] for t in short_entries],
                y=[t['price'] * 1.01 for t in short_entries],
                mode='markers',
                marker=dict(
                    symbol='triangle-down',
                    size=12,
                    color='red',
                    line=dict(width=2)
                ),
                name='Short Entry',
                text=[f"Short Entry<br>Date: {t['date'].strftime('%Y-%m-%d')}<br>Price: {t['price']:.2f}<br>Profit: {t['profit']:.2f}%"
                      for t in short_entries],
                hoverinfo='text'
            ),
            row=1, col=1
        )

        fig.add_trace(
            go.Scatter(
                x=[t['date'] for t in short_exits],
                y=[t['price'] * 0.99 for t in short_exits],
                mode='markers',
                marker=dict(
                    symbol='triangle-up',
                    size=12,
                    color='orange',
                    line=dict(width=2)
                ),
                name='Short Exit',
                text=[f"Short Exit<br>Date: {t['date'].strftime('%Y-%m-%d')}<br>Price: {t['price']:.2f}<br>Profit: {t['profit']:.2f}%"
                      for t in short_exits],
                hoverinfo='text'
            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          row=1, col=1
        )

    # Equity curve
    if isinstance(equity_curve, list):
        equity_curve = np.array(equity_curve)

    # Проверка соответствия equity_curve длине набора данных
    if len(equity_curve) > len(data):
        equity_curve = equity_curve[-len(data):]
    elif len(equity_curve) < len(data):
        padding = np.full(len(data) - len(equity_curve), equity_curve[-1])
        equity_curve = np.concatenate([equity_curve, padding])

    fig.add_trace(
        go.Scatter(
            x=data.index,
            y=equity_curve,
            name='Equity',
            line=dict(color='blue', width=2),
            text=[f"Equity: {eq:.2f}" for eq in equity_curve],
            hoverinfo='text+x'
        ),
        row=2, col=1
    )

    # Настройки графика
    fig.update_layout(
        title=dict(
            text=title,  # Заголовок передается только здесь
            x=0.5,
            xanchor='center'
        ),
        showlegend=True,
        height=800,
        template='plotly_white',
        hovermode='x unified',
        legend=dict(
            yanchor="top",
            y=0.99,
            xanchor="left",
            x=0.01
        )
    )

    # Настройки осей графика
    fig.update_xaxes(
        title_text=" ",
        rangeslider_visible=False,
        gridcolor='lightgrey',
        showgrid=True
    )

    fig.update_yaxes(
        title_text="Price",
        gridcolor='lightgrey',
        showgrid=True,
        row=1, col=1
    )

    fig.update_yaxes(
        title_text="Equity",
        gridcolor='lightgrey',
        showgrid=True,
        row=2, col=1
    )

    return fig

In [ ]:
# расчет и визуализация roc auc
from sklearn.metrics import roc_curve, auc
from sklearn.preprocessing import label_binarize
from itertools import cycle
import numpy as np
def is_float_in_range(lower_bound, value, upper_bound):
    return lower_bound <= value <= upper_bound

###!!!! не работает
def rocauc_torch(X_test, y_test):
  auc_score = roc_auc_score(y_test, y_test)
  print(f"ROC AUC Score: {auc_score:.4f}")
  fpr, tpr, thresholds = roc_curve(y_test, y_test)

  if is_float_in_range(0.9, auc_score, 1.0) :
    print(f"Модель высокой надежности, пригодная для критически важных задач")
  elif is_float_in_range(0.8, auc_score, 0.9):
    print(f"Подходит для большинства бизнес-задач")
  elif is_float_in_range(0.7, auc_score, 0.8):
    print(f"Пригодна для некритичных задач; требует дополнительной проверки")
  elif is_float_in_range(0.6, auc_score, 0.7):
    print(f"Требует значительного улучшения")
  elif is_float_in_range(0.5, auc_score, 0.6):
    print(f"Немного лучше случайного угадывания")
  elif is_float_in_range(0.0, auc_score, 0.5):
    print(f"Эквивалентна случайному угадыванию")

  return auc_score

def rocauc(model, X_test, y_test):
  y_pred_proba = model.predict_proba(X_test)[:, 1]
  auc_score = roc_auc_score(y_test, y_pred_proba)
  print(f"ROC AUC Score: {auc_score:.4f}")
  fpr, tpr, thresholds = roc_curve(y_test, y_pred_proba)

  if is_float_in_range(0.9, auc_score, 1.0) :
    print(f"Модель высокой надежности, пригодная для критически важных задач")
  elif is_float_in_range(0.8, auc_score, 0.9):
    print(f"Подходит для большинства бизнес-задач")
  elif is_float_in_range(0.7, auc_score, 0.8):
    print(f"Пригодна для некритичных задач; требует дополнительной проверки")
  elif is_float_in_range(0.6, auc_score, 0.7):
    print(f"Требует значительного улучшения")
  elif is_float_in_range(0.5, auc_score, 0.6):
    print(f"Немного лучше случайного угадывания")
  elif is_float_in_range(0.0, auc_score, 0.5):
    print(f"Эквивалентна случайному угадыванию")

  return auc_score
  #plt.figure(figsize=(8, 6))
  #plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (area = {auc_score:.2f})')
  #plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--', label='Random Classifier')
  #plt.xlim([0.0, 1.0])
  #plt.ylim([0.0, 1.05])
  #plt.xlabel('False Positive Rate')
  #plt.ylabel('True Positive Rate')
  #plt.title('Receiver Operating Characteristic (ROC) Curve')
  #plt.legend(loc="lower right")
  #plt.grid(True)
  #plt.show()

In [ ]:
# Функция визуализации результатов лучшей стратегии с сигналами
def plot_best_strategy_signals(data, strategy, signals, strategy_results, title1):
    """Функция визуализации результатов лучшей стратегии с отдельными подграфиками для каждого индикатора"""
    if isinstance(data.columns, pd.MultiIndex):
        data.columns = data.columns.droplevel(1)

    # Определяем количество подграфиков в зависимости от стратегии
    if isinstance(strategy, Strategy1):
        # Для Strategy1: EMA, RSI, MACD
        num_subplots = 4  # Основной график + 3 индикатора
        subplot_titles = ["Price и сигналы", "EMA", "RSI", "MACD"]  # Убираем дублирование заголовка
    elif isinstance(strategy, Strategy2):
        # Для Strategy2: Bollinger Bands, Stochastic + RSI
        num_subplots = 4  # Основной график + 3 индикатора
        subplot_titles = ["Price и сигналы", "Bollinger Bands", "Stochastic %K", "Stochastic %D", "RSI"]  # Убираем дублирование заголовка
    elif isinstance(strategy, Strategy3):
        # Для Strategy3: RSI
        num_subplots = 2  # Основной график + 1 индикатор
        subplot_titles = ["Price и сигналы", "RSI"]  # Убираем дублирование заголовка
    elif isinstance(strategy, Strategy4):
        # Для Strategy4: RSI
        num_subplots = 5  # Основной график + 5 индикаторов
        subplot_titles = ["Price и сигналы", "RSI", "EMA", "MACD", "Bollinger Bands"]  # Убираем дублирование заголовка
    else:
        num_subplots = 2  # По умолчанию: основной график + 1 индикатор
        subplot_titles = ["Price и сигналы", "Indicator"]  # Убираем дублирование заголовка

    # Создание subplot с несколькими графиками
    fig = make_subplots(rows=num_subplots, cols=1,
                        shared_xaxes=True,
                        vertical_spacing=0.05,
                        row_heights=[0.6] + [0.1] * (num_subplots - 1),  # Основной график занимает больше места
                        subplot_titles=subplot_titles)  # Заголовки для каждого подграфика

    # Добавление свечного графика на первый подграфик
    fig.add_trace(
        go.Candlestick(
            x=data.index,
            open=data['Open'],
            high=data['High'],
            low=data['Low'],
            close=data['Close'],
            name='Цена'
        ),
        row=1, col=1
    )

    # Добавление сигналов на первый подграфик
    buy_signals = signals[signals == 1].index
    sell_signals = signals[signals == -1].index

    # Покупки
    if len(buy_signals) > 0:
        fig.add_trace(
            go.Scatter(
                x=buy_signals,
                y=data.loc[buy_signals, 'Low'] * 0.99,
                mode='markers',
                marker=dict(
                    symbol='triangle-up',
                    size=12,
                    color='green',
                    line=dict(width=2)
                ),
                name='Сигнал на покупку',
                text=[f"Покупка<br>Дата: {date.strftime('%Y-%m-%d')}<br>Цена: {data.loc[date, 'Close']:.2f}"
                      for date in buy_signals],
                hoverinfo='text'
            ),
            row=1, col=1
        )

    # Продажи
    if len(sell_signals) > 0:
        fig.add_trace(
            go.Scatter(
                x=sell_signals,
                y=data.loc[sell_signals, 'High'] * 1.01,
                mode='markers',
                marker=dict(
                    symbol='triangle-down',
                    size=12,
                    color='red',
                    line=dict(width=2)
                ),
                name='Сигнал на продажу',
                text=[f"Продажа<br>Дата: {date.strftime('%Y-%m-%d')}<br>Цена: {data.loc[date, 'Close']:.2f}"
                      for date in sell_signals],
                hoverinfo='text'
            ),
            row=1, col=1
        )

    # Добавление индикаторов на отдельные подграфики
    if isinstance(strategy, Strategy1):
        # Для Strategy1: EMA, RSI, MACD
        close_prices = data['Close'].values.astype(float).flatten()
        df = data.copy()
        df['EMA'] = ta.EMA(close_prices, timeperiod=strategy.ema_period)
        df['RSI'] = ta.RSI(close_prices, timeperiod=strategy.rsi_period)
        macd, signal, _ = ta.MACD(close_prices,
                                  fastperiod=strategy.macd_fast,
                                  slowperiod=strategy.macd_slow,
                                  signalperiod=strategy.macd_signal)
        df['MACD'] = macd
        df['Signal'] = signal

        # EMA на втором подграфике
        fig.add_trace(
            go.Scatter(
                x=data.index,
                y=df['EMA'],
                name='EMA',
                line=dict(color='blue', width=1)
            ),
            row=2, col=1
        )

        # RSI на третьем подграфике
        fig.add_trace(
            go.Scatter(
                x=data.index,
                y=df['RSI'],
                name='RSI',
                line=dict(color='orange', width=1)
            ),
            row=3, col=1
        )

        # MACD и Signal на четвертом подграфике
        fig.add_trace(
            go.Scatter(
                x=data.index,
                y=df['MACD'],
                name='MACD',
                line=dict(color='green', width=1)
            ),
            row=4, col=1
        )

        fig.add_trace(
            go.Scatter(
                x=data.index,
                y=df['Signal'],
                name='MACD Signal',
                line=dict(color='red', width=1)
            ),
            row=4, col=1
        )

    elif isinstance(strategy, Strategy2):
        # Для Strategy2: Bollinger Bands, Stochastic + RSI
        close_prices = data['Close'].values.astype(float).flatten()
        high_prices = data['High'].values.astype(float).flatten()
        low_prices = data['Low'].values.astype(float).flatten()
        df = data.copy()
        df['BB_middle'] = ta.SMA(close_prices, timeperiod=strategy.bb_period)
        std_dev = ta.STDDEV(close_prices, timeperiod=strategy.bb_period)
        df['RSI'] = ta.RSI(close_prices, timeperiod=strategy.rsi_period)
        df['BB_upper'] = df['BB_middle'] + strategy.bb_std * std_dev
        df['BB_lower'] = df['BB_middle'] - strategy.bb_std * std_dev
        slowk, slowd = ta.STOCH(high_prices,
                               low_prices,
                               close_prices,
                               fastk_period=strategy.stoch_k,
                               slowk_period=strategy.stoch_d,
                               slowd_period=strategy.stoch_slow)
        df['slowk'] = slowk
        df['slowd'] = slowd

        # Bollinger Bands на втором подграфике
        fig.add_trace(
            go.Scatter(
                x=data.index,
                y=df['BB_upper'],
                name='BB Upper',
                line=dict(color='blue', width=1)
            ),
            row=2, col=1
        )

        # RSI на третьем подграфике
        fig.add_trace(
            go.Scatter(
                x=data.index,
                y=df['RSI'],
                name='RSI',
                line=dict(color='orange', width=1)
            ),
            row=3, col=1
        )

        fig.add_trace(
            go.Scatter(
                x=data.index,
                y=df['BB_middle'],
                name='BB Middle',
                line=dict(color='green', width=1)
            ),
            row=2, col=1
        )

        fig.add_trace(
            go.Scatter(
                x=data.index,
                y=df['BB_lower'],
                name='BB Lower',
                line=dict(color='red', width=1)
            ),
            row=2, col=1
        )

        # Stochastic на третьем подграфике
        fig.add_trace(
            go.Scatter(
                x=data.index,
                y=df['slowk'],
                name='Stochastic %K',
                line=dict(color='purple', width=1)
            ),
            row=3, col=1
        )

        fig.add_trace(
            go.Scatter(
                x=data.index,
                y=df['slowd'],
                name='Stochastic %D',
                line=dict(color='orange', width=1)
            ),
            row=3, col=1
        )


    elif isinstance(strategy, Strategy3):
        # Для Strategy3: RSI
        close_prices = data['Close'].values.astype(float).flatten()
        df = data.copy()
        df['RSI'] = ta.RSI(close_prices, timeperiod=strategy.rsi_period)

        # RSI на втором подграфике
        fig.add_trace(
            go.Scatter(
                x=data.index,
                y=df['RSI'],
                name='RSI',
                line=dict(color='blue', width=1)
            ),
            row=2, col=1
        )
    elif isinstance(strategy, Strategy4):
        # Для Strategy4
        close_prices = data['Close'].values.astype(float).flatten()
        df = data.copy()
        df['RSI'] = ta.RSI(close_prices, timeperiod=strategy.rsi_period)
        df['BB_middle'] = ta.SMA(close_prices, timeperiod=strategy.bb_period)
        std_dev = ta.STDDEV(close_prices, timeperiod=strategy.bb_period)
        df['BB_upper'] = df['BB_middle'] + strategy.bb_std * std_dev
        df['BB_lower'] = df['BB_middle'] - strategy.bb_std * std_dev
        df['EMA'] = ta.EMA(close_prices, timeperiod=strategy.ema_period)
        macd, signal, _ = ta.MACD(close_prices,
                                  fastperiod=strategy.macd_fast,
                                  slowperiod=strategy.macd_slow,
                                  signalperiod=strategy.macd_signal)
        df['MACD'] = macd
        df['Signal'] = signal


        # RSI на втором подграфике
        fig.add_trace(
            go.Scatter(
                x=data.index,
                y=df['RSI'],
                name='RSI',
                line=dict(color='blue', width=1)
            ),
            row=2, col=1
        )

        # Bollinger Bands на пятом подграфике
        fig.add_trace(
            go.Scatter(
                x=data.index,
                y=df['BB_upper'],
                name='BB Upper',
                line=dict(color='blue', width=1)
            ),
            row=5, col=1
        )

        # EMA на втором подграфике
        fig.add_trace(
            go.Scatter(
                x=data.index,
                y=df['EMA'],
                name='EMA',
                line=dict(color='blue', width=1)
            ),
            row=3, col=1
        )

        # MACD и Signal на четвертом подграфике
        fig.add_trace(
            go.Scatter(
                x=data.index,
                y=df['MACD'],
                name='MACD',
                line=dict(color='green', width=1)
            ),
            row=4, col=1
        )

        fig.add_trace(
            go.Scatter(
                x=data.index,
                y=df['Signal'],
                name='MACD Signal',
                line=dict(color='red', width=1)
            ),
            row=4, col=1
        )

        fig.add_trace(
            go.Scatter(
                x=data.index,
                y=df['BB_middle'],
                name='BB Middle',
                line=dict(color='green', width=1)
            ),
            row=5, col=1
        )

        fig.add_trace(
            go.Scatter(
                x=data.index,
                y=df['BB_lower'],
                name='BB Lower',
                line=dict(color='red', width=1)
            ),
            row=5, col=1
        )

    # Настройка макета
    fig.update_layout(
        title=dict(
            text=title1,  # Заголовок передается только здесь
            x=0.5,
            xanchor='center'
        ),
        showlegend=True,
        height=200 * num_subplots,  # Высота графика зависит от количества подграфиков
        template='plotly_white',
        hovermode='x unified',
        legend=dict(
            yanchor="top",
            y=0.99,
            xanchor="left",
            x=0.01
        )
    )

    # Настройка осей
    fig.update_xaxes(
        title_text=" ",
        rangeslider_visible=False,
        gridcolor='lightgrey',
        showgrid=True
    )

    fig.update_yaxes(
        title_text=" ",
        gridcolor='lightgrey',
        showgrid=True,
        row=1, col=1
    )

    # Настройка осей для индикаторов
    for i in range(2, num_subplots + 1):
        fig.update_yaxes(
            title_text=" ",
            gridcolor='lightgrey',
            showgrid=True,
            row=i, col=1
        )

    return fig

In [ ]:
# Функция для бэктестирования стратегии
def backtest_strategy(strategy, data):
    """Бэктестирование стратегии"""
    try:
        if data is None or len(data) < 2:
            return None

        signals, conditions, df = strategy.generate_signals(data)
        if signals is None or signals.empty:
            return None


        signals = signals.fillna(0)
        signals = signals.reindex(data.index, fill_value=0)

        close_prices = data['Close'].values
        equity = 1.0
        equity_curve = [equity]
        positions = []
        position_open = False
        entry_price = 0
        entry_signal = 0
        entry_date = None

        for i in range(1, len(signals)):
            current_signal = signals.iloc[i]
            current_date = signals.index[i]

            if not position_open and current_signal != 0:
                # Открываем позицию
                position_open = True
                entry_price = close_prices[i]
                entry_signal = current_signal
                entry_date = current_date

            elif position_open and ((current_signal != 0 and current_signal != entry_signal) or i == len(signals)-1):
                # Закрываем позицию
                exit_price = close_prices[i]
                profit = (exit_price - entry_price) / entry_price * entry_signal

                positions.append({
                    'entry_date': entry_date,
                    'exit_date': current_date,
                    'profit': float(profit)
                })

                equity *= (1.0 + profit)
                position_open = False

            equity_curve.append(float(equity))

        strategy.positions = positions
        strategy.equity = equity_curve
        strategy.signals = signals  # Сохраняем сигналы для последующей визуализации

        return strategy.calculate_metrics(data), conditions, signals, df

    except Exception as e:
        print(f"Ошибка при бэктестировании: {str(e)}")
        return None

In [ ]:
def find_best_strategy(all_results):
    """ Поиск лучшей стратегии среди всех инструментов и наборов данных на основе доходности с поправкой на риск. """
    best_strategy = {
        'strategy_name': None,
        'instrument': None,
        'dataset': None,
        'metrics': None,
        'risk_adjusted_returns': float('-inf'),
        'params': None
    }

    for instrument, results in all_results.items():
        #for strategy_name in ['Strategy1', 'Strategy2', 'Strategy3', 'Strategy4']:
        for strategy_name in ['Strategy4']:
            if strategy_name not in results:
                continue

            # Check all datasets (train_default, test, valid)
            for dataset in ['train_default', 'test', 'test_ml','test_neu','test_chronos', 'valid']:
                if dataset not in results[strategy_name]:
                    continue

                metrics = results[strategy_name][dataset]
                risk_adjusted_returns = calculate_risk_adjusted_returns(metrics)

                if risk_adjusted_returns > best_strategy['risk_adjusted_returns']:
                    params_key = 'train_default_params' if dataset == 'train_default' else 'optimized_params'
                    if dataset == 'valid':
                        params_key = 'optimized_params_combined'

                    best_strategy = {
                        'strategy_name': strategy_name,
                        'instrument': instrument,
                        'dataset': dataset,
                        'metrics': metrics,
                        'risk_adjusted_returns': risk_adjusted_returns,
                        'params': results[strategy_name].get(params_key)
                    }

    return best_strategy

In [ ]:
def analyze_instrument(symbol):
    """Анализ торговых стратегий для одного инструмента"""

    try:
        data = load_data(symbol)
        if data is None or len(data) < 100:
            print(f"Недостаточно данных для {symbol}")
            return None, None

        data = data.copy()
        data = data.ffill().copy()
        #data = data.fillna(method='ffill').fillna(method='bfill')

        if data.isnull().any().any():
            print(f"Обнаружены пропущенные значения после обработки в {symbol}")
            return None, None

        print(f"\nРазмер данных: {len(data)} строк")

        train_data, test_data, valid_data = split_data(data)

        print("\nПериоды наборов данных:")
        print(f"Train: {train_data.index[0].date()} - {train_data.index[-1].date()}")
        print(f"Test: {test_data.index[0].date()} - {test_data.index[-1].date()}")
        print(f"Valid: {valid_data.index[0].date()} - {valid_data.index[-1].date()}")
        print(f"TestMl: {test_data.index[0].date()} - {test_data.index[-1].date()}")


        results = {}

        try:
            bh_results = backtest_buy_hold(data)
            if bh_results:
                results['Buy & Hold'] = {
                    'full': bh_results,
                    'full_data': data  # Сохраняем данные для расчета количества дней
                }
        except Exception as e:
            print(f"Ошибка при расчете Buy & Hold для {symbol}: {str(e)}")

        for strategy_name, strategy_params in [
            #('Strategy1', Strategy1()),
            #('Strategy2', Strategy2()),
            #('Strategy3', Strategy3()),
            ('Strategy4', Strategy4())
        ]:
            try:
                strategy_results = {}

                # Бэктестирование на Train с гиперпараметрами по умолчанию
                print(f"\n1. Набор данных Train. Начало бэктестирования {strategy_name} с гиперпараметрами по умолчанию: {strategy_params.get_params()}")
                #print(f"Гиперпараметры по умолчанию: {strategy_params.get_params()}")
                train_metrics, conditions, signals, df = backtest_strategy(strategy_params, train_data)
                if train_metrics:
                    strategy_results['train_default'] = train_metrics
                    strategy_results['train_default_params'] = strategy_params.get_params()  # Гиперпараметры
                    strategy_results['train_default_data'] = train_data  # Данные для расчета количества дней

                # Оптимизация гиперпараметров на Train
                print(f"\nНачало оптимизации гиперпараметров для {strategy_name} на Train...")
                param_space = param_spaces[strategy_name]
                best_params = optimize_strategy(globals()[strategy_name], train_data, param_space)
                if best_params:
                    print(f"Оптимальные гиперпараметры для {strategy_name} на Train: {best_params}")
                    optimized_strategy = globals()[strategy_name](**best_params)
                    optimized_strategy.ticker = symbol
                    strategy_results['optimized_params'] = best_params  # Оптимизированные гиперпараметры

                    # Бэктестирование на Test с оптимизированными гиперпараметрами
                    print(f"\n2. Набор данных Test. Начало бэктестирования {strategy_name} с оптимизированными гиперпараметрами на наборе Train: {best_params}")
                    #print(f"Оптимизированные гиперпараметры: {best_params}")
                    test_metrics, conditions_test, signals_test, df_test = backtest_strategy(optimized_strategy, test_data)
                    if test_metrics:
                        strategy_results['test'] = test_metrics
                        strategy_results['test_data'] = test_data  # Данные для расчета количества дней

                    #!!!!! Объединение Train и Test для оптимизации
                    #!!!!!!!!!!4. Ячейка 38: split_data формально ок, но дальше ломается логика эксперимента
                    #train_test_split(..., shuffle=False) - это нормально как “простое временное разбиение”.
                    #Но проблема в том, как test используется далее:
                    #В analyze_instrument (ячейка 38) ты делаешь:
                    #- оптимизация на Train -> проверка на Test - это ОК
                    #- затем объединяешь Train+Test, оптимизируешь снова (best_params_combined)
                    #- и после этого снова прогоняешь вещи на Test (и даже ML/NN на test) - это уже нечестно, потому что test стал частью тюнинга модели.

                    train_test_data = pd.concat([train_data, test_data])
                    print(f"\nОбъединенный набор данных Train и Test: {train_test_data.index[0].date()} - {train_test_data.index[-1].date()}")

                    # Оптимизация гиперпараметров на объединенном наборе
                    print(f"\nНачало оптимизации гиперпараметров для {strategy_name} на объединенном наборе Train и Test...")
                    best_params_combined = optimize_strategy(globals()[strategy_name], train_test_data, param_space)
                    print(f"Оптимальные гиперпараметры для {strategy_name} на объединенном наборе Train и Test: {best_params_combined}")
                    optimized_strategy_combined = globals()[strategy_name](**best_params_combined)
                    strategy_results['optimized_params_combined'] = best_params_combined  # Оптимизированные гиперпараметры

                    # проверка стратегии с испльзованием ML
                    print(f"\n3. Набор данных Test.  Начало бэктестирования {strategy_name} с оптимизированными гиперпараметрами на наборе Test: {best_params_combined} с использованием ML")
                    ml_metrics = backtestWithML(optimized_strategy, data, test_data)
                    #display(ml_metrics)
                    if ml_metrics:
                        strategy_results['test_ml'] = ml_metrics.copy()
                        strategy_results['test_ml_data'] = test_data.copy()  # Данные для расчета количества дней

                    # проверка стратегии с использованием нейронной сети txmixer
                    print(f"\n4. Набор данных Test. Модель TSMixer. Начало бэктестирования {strategy_name} с оптимизированными гиперпараметрами на наборе Test: {best_params_combined} с использованием ML")
                    neu_metrics = backtestWithNeu(optimized_strategy, data, test_data)
                    if neu_metrics:
                        strategy_results['test_neu'] = neu_metrics.copy()
                        strategy_results['test_neu_data'] = test_data.copy()  # Данные для расчета количества дней

                    # проверка стратегии с испльзованием нейронной сети chronos
                    print(f"\n5. Набор данных Test. Модель Chronos. Начало бэктестирования {strategy_name} с оптимизированными гиперпараметрами на наборе Test: {best_params_combined} с использованием ML")
                    chronos_metrics = backtestWithChronos(optimized_strategy, data, test_data, action="Load")
                    if chronos_metrics:
                        strategy_results['test_chronos'] = chronos_metrics.copy()
                        strategy_results['test_chronos_data'] = test_data.copy()  # Данные для расчета количества дней

                    # Бэктестирование на Valid с оптимизированными гиперпараметрами
                    print(f"\n6. Набор данных Valid. Начало бэктестирования {strategy_name} с оптимизированными гиперпараметрами на объединенном наборе Train и Test: {best_params_combined}")
                    #print(f"Оптимизированные гиперпараметры: {best_params_combined}")
                    #valid_metrics, conditions, signals, df = backtest_strategy(optimized_strategy_combined, valid_data)
                    valid_metrics = backtestWithNeu(optimized_strategy, data, valid_data, action="Load")
                    if valid_metrics:
                        strategy_results['valid'] = valid_metrics
                        strategy_results['valid_data'] = valid_data  # Данные для расчета количества дней
                    print("=" * 100)  # Сплошная горизонтальная линия

                if strategy_results:
                    results[strategy_name] = strategy_results

            except Exception as e:
                print(f"Ошибка при анализе стратегии {strategy_name}: {str(e)}")
                continue

        if not results:
            print(f"Не удалось получить результаты для {symbol}")
            return None, None


        return results, data

    except Exception as e:
        print(f"Ошибка при анализе инструмента {symbol}: {str(e)}")
        return None, None


# Функция отображения графика датафрейма
def display_graf(df):
  sns.set(style="darkgrid")
  plt.figure(figsize=(15, 6))
  #display(df)
  dfgr = df
  #dfgr['short_mavg'] = dfgr['Close'].rolling(50).mean()
  #dfgr['long_mavg'] = dfgr['Close'].rolling(200).mean()
  subset = dfgr[dfgr['Ticker'] == 'GOOG']
  plot_data = subset[-500:]
  plt.plot(plot_data.index, plot_data['Close'], label='GOOG')
  plt.title(' ')
  plt.xlabel('Date')
  plt.ylabel('Close Price')
  plt.legend()
  plt.show()


# Функция загрузки данных
def load_data(symbol, start_date='2022-01-01', end_date='2026-01-01'):
    """Загрузка данных с Yahoo Finance"""
    display(f"\nЗагрузка данных с Yahoo Finance {symbol}")

    df = yf.download(symbol, start=start_date, end=end_date, interval='1d', auto_adjust=True, multi_level_index=False, ignore_tz=True)#, interval='1h') progress=False, multi_level_index=False)

    df.index.name = 'Date'
    #df.index.tz_convert(None)
    df = df[['Open', 'High', 'Low', 'Close', 'Volume']]
    #pd.to_datetime(df.index, format='%Y-%m-%d %H:%M:%S')
    #df=df[df.Volume!=0]

    #df.index = pd.to_datetime(df.index, format='%Y-%m-%d %H:%M:%S')
    df.index = pd.to_datetime(df.index, format = '%Y-%m-%d')
    df = df.dropna()  # Удаление строк с пропущенными значениями
    df = df[~df.index.duplicated()]  # Удаление дубликатов


    # Перевод всех значений в числовой формат
    for c in [x for x in df.columns if x != 'Date']:
        df[c] = df[c].apply(pd.to_numeric, errors='coerce')
    # Сбрасываем мультииндекс, если он есть
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.droplevel(1)

    return df


# Функция разделения данных на наборы
def split_data(df):
    """Разделение данных на наборы данных: Train, Test и Valid"""
    train_size = 0.6
    test_size = 0.2
    # Первое разделение на train и остаток
    train_data, temp_data = train_test_split(df, train_size=train_size, shuffle=False)
    #!!!!!!!!!4. Ячейка 38: split_data формально ок, но дальше ломается логика эксперимента
    #train_test_split(..., shuffle=False) - это нормально как “простое временное разбиение”.
    #Но проблема в том, как test используется далее:
    #В analyze_instrument (ячейка 38) ты делаешь:
    #- оптимизация на Train -> проверка на Test - это ОК
    #- затем объединяешь Train+Test, оптимизируешь снова (best_params_combined)
    #- и после этого снова прогоняешь вещи на Test (и даже ML/NN на test) - это уже нечестно, потому что test стал частью тюнинга модели.
    # Разделение остатка на test и valid
    test_size_adjusted = test_size / (1 - train_size)
    test_data, valid_data = train_test_split(temp_data, train_size=test_size_adjusted, shuffle=False)
    #train_data = train_data.reindex(pd.date_range(start=train_data.index.min(),end=train_data.index.max(),freq='1D'))
    #train_data = train_data.interpolate(method='linear').ffill().copy()

    return train_data, test_data, valid_data



def main():
    """Основная функция с выбором стратегии и визуализацией"""
    all_results = {}
    # Определение списка инструментов
    stocks = ['AAPL', 'MSFT', 'GOOGL', 'NVDA', 'BTC-USD']
    #cryptos = ['SOL-USD', 'BTC-USD']

    instruments = stocks
    for instrument in instruments:

        print(f"\n\033[1;34mАнализ инструмента: {instrument}\033[0m")
        print("=" * 100)  # Сплошная горизонтальная линия
        try:
            results, data = analyze_instrument(instrument)
            if results is not None and data is not None:
                all_results[instrument] = results
                summary_table = create_summary_table(results, instrument)
                display(summary_table)

        except Exception as e:
            print(f"Ошибка в анализе инструмента {instrument}: {str(e)}")
            continue

    # Поиск лучшей стратегии, используя метод отбора
    best_strategy = find_best_strategy(all_results)

    if best_strategy['strategy_name']:
        print(f"\n\033[1;34mОпределение стратегии с лучшими показателями инструменту и по набору данных\033[0m")
        print(f"Лучшая стратегия: {best_strategy['strategy_name']}")
        print(f"Лучший инструмент: {best_strategy['instrument']}")
        print(f"Лучший набор данных: {best_strategy['dataset']}")
        print(f"Доходность с корректировкой риска (Risk-Adjusted Returns): {best_strategy['risk_adjusted_returns']:.2f}")
        print("\nОптимальные гиперпараметры:")
        for param, value in best_strategy['params'].items():
            print(f"{param}: {value}")

        # Вывод метрик производительности
        metrics = best_strategy['metrics']
        print("\nМетрики производительности для лучшей стратегии:")
        print(f"Конечный капитал (final_equity) : {metrics['final_equity']:.2f}")
        print(f"Количество сделок (n_trades): {metrics['n_trades']}")
        print(f"Доходность (returns): {metrics['returns']:.2f}%")
        print(f"Максимальная просадка (max_drawdown): {metrics['max_drawdown']:.2f}%")
        print(f"Процент прибыльных сделок (win_rate): {metrics['win_rate']:.2f}%")
        print(f"Коэффициент Шарпа (sharpe_ratio): {metrics['sharpe_ratio']:.2f}")
        print(f"Коэффициент Сортино (sortino_ratio): {metrics['sortino_ratio']:.2f}")
        print(f"Фактор прибыли (profit_factor): {metrics['profit_factor']:.2f}")

        # Создание объекта стратегии с оптимальными параметрами
        strategy_class = globals()[best_strategy['strategy_name']]
        best_strategy_obj = strategy_class(**best_strategy['params'])

        # Получение набора данных
        data = load_data(best_strategy['instrument'])
        train_data, test_data, valid_data = split_data(data)
        if best_strategy['dataset'] == 'train_default':
            best_data = train_data.copy()
            backtest_strategy(best_strategy_obj, best_data)
            trades = analyze_trades(best_strategy_obj, best_data, best_strategy_obj.signals)
        elif best_strategy['dataset'] == 'test':
            best_data = test_data.copy()
            backtest_strategy(best_strategy_obj, best_data)
            trades = analyze_trades(best_strategy_obj, best_data, best_strategy_obj.signals)
        elif best_strategy['dataset'] == 'test_ml':
            best_data = test_data.copy()
            test_metrics = backtestWithML(best_strategy_obj, train_data, best_data, ml_modelname=metrics['ml_modelname'])
            metrics = test_metrics
            trades = analyze_trades(best_strategy_obj, best_data, best_strategy_obj.signals)
            #backtest_strategy(best_strategy_obj, best_data)
        elif best_strategy['dataset'] == 'test_neu':
            best_data = test_data.copy()
            test_metrics = backtestWithNeu(best_strategy_obj, train_data, best_data, action="Load", instrument=best_strategy['instrument'])
            metrics = test_metrics
            #trades = analyze_trades(best_strategy_obj, best_data, best_strategy_obj.signals)
        elif best_strategy['dataset'] == 'test_chronos':
            best_data = test_data.copy()
            test_metrics = backtestWithChronos(best_strategy_obj, train_data, best_data, action="Load", instrument=best_strategy['instrument'])
            metrics = test_metrics
            #trades = analyze_trades(best_strategy_obj, best_data, best_strategy_obj.signals)
        else:
            best_data = valid_data.copy()
            valid_metrics = backtestWithNeu(best_strategy_obj, train_data, best_data, action="Load", instrument=best_strategy['instrument'])
            metrics = valid_metrics
            #trades = analyze_trades(best_strategy_obj, best_data, best_strategy_obj.signals)


    else:
        print("\nНе найдена лучшая стратегия")

if __name__ == "__main__":

  main()

Анализ инструмента: AAPL
====================================================================================================

'\nЗагрузка данных с Yahoo Finance AAPL'

[*********************100%***********************]  1 of 1 completed

Размер данных: 1003 строк

Периоды наборов данных:
Train: 2022-01-03 - 2024-05-23
Test: 2024-05-24 - 2025-03-14
Valid: 2025-03-17 - 2025-12-31
TestMl: 2024-05-24 - 2025-03-14

1. Набор данных Train. Начало бэктестирования Strategy4 с гиперпараметрами по умолчанию: {'bb_period': 20, 'bb_std': 2.0, 'rsi_period': 14, 'sma': 10, 'ema_period': 4, 'ma_period': 10, 'macd_fast': 12, 'macd_slow': 26, 'macd_signal': 9, 'stoch_k': 14, 'stoch_d': 3, 'stoch_slow': 3}

Начало оптимизации гиперпараметров для Strategy4 на Train...
  0%|          | 0/50 [00:00<?, ?trial/s, best loss=?]

100%|██████████| 50/50 [00:05<00:00,  9.75trial/s, best loss: -1.4025422886110488]
Оптимальные гиперпараметры для Strategy4 на Train: {'bb_period': np.float64(32.0), 'bb_std': np.float64(2.743394926900637), 'ema_period': np.float64(25.0), 'ma_period': np.float64(35.0), 'macd_fast': np.float64(10.0), 'macd_signal': np.float64(15.0), 'macd_slow': np.float64(40.0), 'rsi_period': np.float64(11.0), 'sma': np.float64(50.0), 'stoch_d': np.float64(3.0), 'stoch_k': np.float64(13.0), 'stoch_slow': np.float64(5.0)}

2. Набор данных Test. Начало бэктестирования Strategy4 с оптимизированными гиперпараметрами на наборе Train: {'bb_period': np.float64(32.0), 'bb_std': np.float64(2.743394926900637), 'ema_period': np.float64(25.0), 'ma_period': np.float64(35.0), 'macd_fast': np.float64(10.0), 'macd_signal': np.float64(15.0), 'macd_slow': np.float64(40.0), 'rsi_period': np.float64(11.0), 'sma': np.float64(50.0), 'stoch_d': np.float64(3.0), 'stoch_k': np.float64(13.0), 'stoch_slow': np.float64(5.0)}

Объединенный набор данных Train и Test: 2022-01-03 - 2025-03-14

Начало оптимизации гиперпараметров для Strategy4 на объединенном наборе Train и Test...
100%|██████████| 50/50 [00:05<00:00,  8.39trial/s, best loss: -1.24111820474768]
Оптимальные гиперпараметры для Strategy4 на объединенном наборе Train и Test: {'bb_period': np.float64(44.0), 'bb_std': np.float64(2.8686392494556547), 'ema_period': np.float64(15.0), 'ma_period': np.float64(21.0), 'macd_fast': np.float64(18.0), 'macd_signal': np.float64(15.0), 'macd_slow': np.float64(24.0), 'rsi_period': np.float64(11.0), 'sma': np.float64(46.0), 'stoch_d': np.float64(5.0), 'stoch_k': np.float64(8.0), 'stoch_slow': np.float64(4.0)}

3. Набор данных Test.  Начало бэктестирования Strategy4 с оптимизированными гиперпараметрами на наборе Test: {'bb_period': np.float64(44.0), 'bb_std': np.float64(2.8686392494556547), 'ema_period': np.float64(15.0), 'ma_period': np.float64(21.0), 'macd_fast': np.float64(18.0), 'macd_signal': np.float64(15.0), 'macd_slow': np.float64(24.0), 'rsi_period': np.float64(11.0), 'sma': np.float64(46.0), 'stoch_d': np.float64(5.0), 'stoch_k': np.float64(8.0), 'stoch_slow': np.float64(4.0)} с использованием ML

'Создаем объект класса Backtest'

'Запускаем бэктест'

Backtest.run:   0%|          | 0/99 [00:00<?, ?bar/s]

'Разделяем признаки и метки'

'RobustScaler'

Feature Importance:
 Macd               9.869517
Adx                9.806498
Atr14              7.693093
Engulfing          6.873799
Adosc              6.689864
Slowk              5.832290
Mfi                5.767568
Rsi                5.726999
Slowd              5.188385
Bb_lower           4.880510
Bb_middle          4.522788
Sma                4.332105
Cci                4.232329
Linearreg_angle    4.151343
Obv                3.987048
Bb_upper           3.722494
Ma_period          3.496899
Morningstar        2.262249
Sar                0.722943
Doji               0.166846
Hammer             0.074433
dtype: float64

'Повторяем все тоже самое с данными для теста'

'Для предсказания используем данные в столбацах ниже'

'Выводим предсказание'

[1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1
 1 1]
0.7435897435897436
[[ 2  8]
 [ 2 27]]
              precision    recall  f1-score   support

           0       0.50      0.20      0.29        10
           1       0.77      0.93      0.84        29

    accuracy                           0.74        39
   macro avg       0.64      0.57      0.56        39
weighted avg       0.70      0.74      0.70        39

Backtest.run:   0%|          | 0/38 [00:00<?, ?bar/s]

Start                     2024-08-12 00:00:00
End                       2025-03-11 00:00:00
Duration                    211 days 00:00:00
Exposure Time [%]                   79.487179
Equity Final [$]                906027.590709
Equity Peak [$]                 1018448.76789
Commissions [$]                  61280.889818
Return [%]                          -9.397241
Buy & Hold Return [%]                1.745065
Return (Ann.) [%]                  -47.147242
Volatility (Ann.) [%]               11.244654
CAGR [%]                           -11.118075
Sharpe Ratio                        -4.192858
Sortino Ratio                        -2.73346
Calmar Ratio                        -4.173096
Alpha [%]                           -9.663969
Beta                                 0.152847
Max. Drawdown [%]                  -11.297904
Avg. Drawdown [%]                   -6.490281
Max. Drawdown Duration      155 days 00:00:00
Avg. Drawdown Duration       84 days 00:00:00
# Trades                                   16
Win Rate [%]                             37.5
Best Trade [%]                       4.071297
Worst Trade [%]                     -3.856783
Avg. Trade [%]                      -0.616203
Max. Trade Duration          31 days 00:00:00
dtype: object

'Выводим график :'

'Выводим Buy&Hold и GoldenCross :'

                                   Buy&Hold          GoldenCross
Start                   2022-04-04 00:00:00  2024-08-12 00:00:00
End                     2025-12-31 00:00:00  2025-03-11 00:00:00
Duration                 1367 days 00:00:00    211 days 00:00:00
Exposure Time [%]                      98.0            79.487179
Equity Final [$]              371090.132831        906027.590709
Equity Peak [$]              1588026.903361        1018448.76789
Commissions [$]                147899.16021         61280.889818
Return [%]                       -62.890987            -9.397241
Buy & Hold Return [%]               55.3518             1.745065
Return (Ann.) [%]                -91.775905           -47.147242
Volatility (Ann.) [%]              10.34515            11.244654
CAGR [%]                         -16.701811           -11.118075
Sharpe Ratio                      -8.871394            -4.192858
Sortino Ratio                     -1.268676             -2.73346
Calmar Ratio                      -1.186855            -4.173096
Alpha [%]                         -51.99423            -9.663969
Beta                              -0.196864             0.152847
Max. Drawdown [%]                -77.326983           -11.297904
Avg. Drawdown [%]                -23.083754            -6.490281
Max. Drawdown Duration   1058 days 00:00:00    155 days 00:00:00
Avg. Drawdown Duration    262 days 00:00:00     84 days 00:00:00
# Trades                                 40                   16
Win Rate [%]                           32.5                 37.5
Best Trade [%]                    15.130216             4.071297
Worst Trade [%]                  -33.537633            -3.856783
Avg. Trade [%]                    -2.460094            -0.616203
Max. Trade Duration       147 days 00:00:00     31 days 00:00:00

risk_adjusted_return = -98.28
ROC AUC Score: 0.6483
Требует значительного улучшения

4. Набор данных Test. Модель TSMixer. Начало бэктестирования Strategy4 с оптимизированными гиперпараметрами на наборе Test: {'bb_period': np.float64(44.0), 'bb_std': np.float64(2.8686392494556547), 'ema_period': np.float64(15.0), 'ma_period': np.float64(21.0), 'macd_fast': np.float64(18.0), 'macd_signal': np.float64(15.0), 'macd_slow': np.float64(24.0), 'rsi_period': np.float64(11.0), 'sma': np.float64(46.0), 'stoch_d': np.float64(5.0), 'stoch_k': np.float64(8.0), 'stoch_slow': np.float64(4.0)} с использованием ML
======================================================================
РАСПРЕДЕЛЕНИЕ КЛАССОВ
======================================================================
target
0    472
1    530
Name: count, dtype: int64

Баланс классов (доля класса 1): 0.529
Всего примеров: 1002
======================================================================
Размер окон признаков: (874, 128, 24)
Размер таргетов: (874,)
Размер индексов: (874,)
======================================================================
РАЗМЕРЫ ВЫБОРОК
======================================================================
Train: X=(874, 128, 24), y=(874,)
Test:  X=(201, 128, 24), y=(201,)

Распределение классов в test:
  Класс 0 (падение): 85 (42.3%)
  Класс 1 (рост):    116 (57.7%)
======================================================================
Train batches: 14
Test batches:  4

Пример батча:
  X: torch.Size([64, 128, 24])  (batch, lookback, num_features)
  y: torch.Size([64])  (batch,)

Пример батча test:
  X: torch.Size([64, 128, 24])  (batch, lookback, num_features)
  y: torch.Size([64])  (batch,)
======================================================================
Загружены лучшие веса из tsmixer_full_AAPL.pt
======================================================================
ИНФОРМАЦИЯ О МОДЕЛИ
======================================================================
Всего параметров:      305,113
Обучаемых параметров:  305,113
Устройство:            cpu
======================================================================
Установлен новый Optimizer: AdamW с weight decay для регуляризации
Веса классов для Loss: 0 (Down): 1.0614, 1 (Up): 0.9453
✓ Optimizer, loss function и evaluation function настроены
======================================================================
НАЧАЛО ОБУЧЕНИЯ
======================================================================
Epoch  1/50 | Train Loss: 0.6959 | Train Acc: 0.4725 | Test Acc: 0.4478 | [Model Saved! Best Acc: 0.4478]
Epoch  2/50 | Train Loss: 0.6935 | Train Acc: 0.4954 | Test Acc: 0.4428
Epoch  3/50 | Train Loss: 0.6929 | Train Acc: 0.5069 | Test Acc: 0.4428
Epoch  4/50 | Train Loss: 0.6924 | Train Acc: 0.5092 | Test Acc: 0.4478
Epoch  5/50 | Train Loss: 0.6916 | Train Acc: 0.5137 | Test Acc: 0.4478
Epoch  6/50 | Train Loss: 0.6876 | Train Acc: 0.5549 | Test Acc: 0.4378
Epoch  7/50 | Train Loss: 0.6909 | Train Acc: 0.5332 | Test Acc: 0.4478
Epoch  8/50 | Train Loss: 0.6872 | Train Acc: 0.5423 | Test Acc: 0.4279
Epoch  9/50 | Train Loss: 0.6878 | Train Acc: 0.5446 | Test Acc: 0.4279
Epoch 10/50 | Train Loss: 0.6829 | Train Acc: 0.5732 | Test Acc: 0.4229
Epoch 11/50 | Train Loss: 0.6842 | Train Acc: 0.5469 | Test Acc: 0.4478
Epoch 12/50 | Train Loss: 0.6740 | Train Acc: 0.5915 | Test Acc: 0.4279
Epoch 13/50 | Train Loss: 0.6748 | Train Acc: 0.5915 | Test Acc: 0.4478
Epoch 14/50 | Train Loss: 0.6734 | Train Acc: 0.5686 | Test Acc: 0.4229
Epoch 15/50 | Train Loss: 0.6617 | Train Acc: 0.5892 | Test Acc: 0.4577 | [Model Saved! Best Acc: 0.4577]
Epoch 16/50 | Train Loss: 0.6558 | Train Acc: 0.6190 | Test Acc: 0.4577
Epoch 17/50 | Train Loss: 0.6541 | Train Acc: 0.6178 | Test Acc: 0.4577
Epoch 18/50 | Train Loss: 0.6524 | Train Acc: 0.6339 | Test Acc: 0.4975 | [Model Saved! Best Acc: 0.4975]
Epoch 19/50 | Train Loss: 0.6319 | Train Acc: 0.6430 | Test Acc: 0.5025 | [Model Saved! Best Acc: 0.5025]
Epoch 20/50 | Train Loss: 0.6184 | Train Acc: 0.6522 | Test Acc: 0.4826
Epoch 21/50 | Train Loss: 0.6100 | Train Acc: 0.6773 | Test Acc: 0.4925
Epoch 22/50 | Train Loss: 0.5988 | Train Acc: 0.6773 | Test Acc: 0.5025
Epoch 23/50 | Train Loss: 0.5895 | Train Acc: 0.6922 | Test Acc: 0.5174 | [Model Saved! Best Acc: 0.5174]
Epoch 24/50 | Train Loss: 0.5954 | Train Acc: 0.6945 | Test Acc: 0.5274 | [Model Saved! Best Acc: 0.5274]
Epoch 25/50 | Train Loss: 0.5639 | Train Acc: 0.7231 | Test Acc: 0.5323 | [Model Saved! Best Acc: 0.5323]
Epoch 26/50 | Train Loss: 0.5525 | Train Acc: 0.7197 | Test Acc: 0.5373 | [Model Saved! Best Acc: 0.5373]
Epoch 27/50 | Train Loss: 0.5477 | Train Acc: 0.7265 | Test Acc: 0.5522 | [Model Saved! Best Acc: 0.5522]
Epoch 28/50 | Train Loss: 0.5323 | Train Acc: 0.7380 | Test Acc: 0.5771 | [Model Saved! Best Acc: 0.5771]
Epoch 29/50 | Train Loss: 0.5187 | Train Acc: 0.7574 | Test Acc: 0.5970 | [Model Saved! Best Acc: 0.5970]
Epoch 30/50 | Train Loss: 0.5286 | Train Acc: 0.7391 | Test Acc: 0.5771
Epoch 31/50 | Train Loss: 0.5165 | Train Acc: 0.7460 | Test Acc: 0.5970
Epoch 32/50 | Train Loss: 0.4927 | Train Acc: 0.7563 | Test Acc: 0.6169 | [Model Saved! Best Acc: 0.6169]
Epoch 33/50 | Train Loss: 0.4875 | Train Acc: 0.7609 | Test Acc: 0.6219 | [Model Saved! Best Acc: 0.6219]
Epoch 34/50 | Train Loss: 0.4588 | Train Acc: 0.7872 | Test Acc: 0.6119
Epoch 35/50 | Train Loss: 0.4476 | Train Acc: 0.7952 | Test Acc: 0.6368 | [Model Saved! Best Acc: 0.6368]
Epoch 36/50 | Train Loss: 0.4300 | Train Acc: 0.8089 | Test Acc: 0.6617 | [Model Saved! Best Acc: 0.6617]
Epoch 37/50 | Train Loss: 0.4090 | Train Acc: 0.8101 | Test Acc: 0.6169
Epoch 38/50 | Train Loss: 0.3972 | Train Acc: 0.8124 | Test Acc: 0.6318
Epoch 39/50 | Train Loss: 0.3945 | Train Acc: 0.8238 | Test Acc: 0.6318
Epoch 40/50 | Train Loss: 0.3946 | Train Acc: 0.8204 | Test Acc: 0.6269
Epoch 41/50 | Train Loss: 0.3512 | Train Acc: 0.8444 | Test Acc: 0.6219
Epoch 42/50 | Train Loss: 0.3668 | Train Acc: 0.8410 | Test Acc: 0.6269
Epoch 43/50 | Train Loss: 0.3552 | Train Acc: 0.8661 | Test Acc: 0.6567
Epoch 44/50 | Train Loss: 0.3170 | Train Acc: 0.8604 | Test Acc: 0.6269
Epoch 45/50 | Train Loss: 0.3168 | Train Acc: 0.8650 | Test Acc: 0.6716 | [Model Saved! Best Acc: 0.6716]
Epoch 46/50 | Train Loss: 0.3168 | Train Acc: 0.8616 | Test Acc: 0.6368
Epoch 47/50 | Train Loss: 0.3131 | Train Acc: 0.8638 | Test Acc: 0.6567
Epoch 48/50 | Train Loss: 0.2859 | Train Acc: 0.8730 | Test Acc: 0.6716
Epoch 49/50 | Train Loss: 0.2720 | Train Acc: 0.8879 | Test Acc: 0.6866 | [Model Saved! Best Acc: 0.6866]
Epoch 50/50 | Train Loss: 0.2695 | Train Acc: 0.8764 | Test Acc: 0.6716
======================================================================
ОБУЧЕНИЕ ЗАВЕРШЕНО. Лучшая точность: 0.6866
======================================================================
======================================================================
ЗАГРУЖАЕМ ЛУЧШИЕ ВЕСА ПЕРЕД ФИНАЛЬНОЙ ОЦЕНКОЙ
Загружены лучшие веса из tsmixer_full_AAPL.pt
======================================================================

======================================================================
ФИНАЛЬНЫЕ РЕЗУЛЬТАТЫ КЛАССИФИКАЦИИ
======================================================================
Test Accuracy: 0.6866 (68.66%)
Baseline (majority class): 0.5771 (57.71%)
Улучшение над baseline: 10.95%

----------------------------------------------------------------------
CLASSIFICATION REPORT
----------------------------------------------------------------------
              precision    recall  f1-score   support

    Down (0)     0.6058    0.7412    0.6667        85
      Up (1)     0.7732    0.6466    0.7042       116

    accuracy                         0.6866       201
   macro avg     0.6895    0.6939    0.6854       201
weighted avg     0.7024    0.6866    0.6883       201

----------------------------------------------------------------------
CONFUSION MATRIX
----------------------------------------------------------------------

              Predicted
                0      1
Actual 0       63     22
       1       41     75

----------------------------------------------------------------------
ИНТЕРПРЕТАЦИЯ
----------------------------------------------------------------------
True Positives (правильно предсказан рост):     75
True Negatives (правильно предсказано падение): 63
False Positives (ложный сигнал на рост):        22
False Negatives (пропущенный рост):             41

======================================================================
BACKTEST ТОРГОВЫХ СТРАТЕГИЙ
======================================================================
Buy & Hold:               11.88%
Strategy (Long only):     13.68%
Strategy (Long/Short):     9.75%
======================================================================

Sharpe Ratio (годовой):
  Buy & Hold:           0.603
  Strategy (Long only): 0.945
  Strategy (Long/Short):0.528
======================================================================

/tmp/ipython-input-577606817.py:532: UserWarning: Data index is not sorted in ascending order. Sorting.
  bt = Backtest(test_datadf_neu_backtest, ChronosNextDayDirection, cash=1000000, commission=.002, exclusive_orders=True, finalize_trades=True)

Backtest.run:   0%|          | 0/200 [00:00<?, ?bar/s]

Start                     2024-05-24 00:00:00
End                       2025-12-31 00:00:00
Duration                    586 days 00:00:00
Exposure Time [%]                   74.129353
Equity Final [$]               1097870.321094
Equity Peak [$]                1121030.892907
Commissions [$]                 214415.678246
Return [%]                           9.787032
Buy & Hold Return [%]               44.071193
Return (Ann.) [%]                   12.419103
Volatility (Ann.) [%]               20.848291
CAGR [%]                             4.097029
Sharpe Ratio                         0.595689
Sortino Ratio                        0.856242
Calmar Ratio                         0.659008
Alpha [%]                            1.992702
Beta                                 0.176858
Max. Drawdown [%]                   -18.84515
Avg. Drawdown [%]                   -3.823658
Max. Drawdown Duration      299 days 00:00:00
Avg. Drawdown Duration       82 days 00:00:00
# Trades                                   54
Win Rate [%]                        61.111111
Best Trade [%]                       4.677598
Worst Trade [%]                    -11.644574
Avg. Trade [%]                       0.173387
Max. Trade Duration          11 days 00:00:00
dtype: object

'risk_adjusted_return = -2.74'

Финальный ROC AUC на тесте: 0.7267

5. Набор данных Test. Модель Chronos. Начало бэктестирования Strategy4 с оптимизированными гиперпараметрами на наборе Test: {'bb_period': np.float64(44.0), 'bb_std': np.float64(2.8686392494556547), 'ema_period': np.float64(15.0), 'ma_period': np.float64(21.0), 'macd_fast': np.float64(18.0), 'macd_signal': np.float64(15.0), 'macd_slow': np.float64(24.0), 'rsi_period': np.float64(11.0), 'sma': np.float64(46.0), 'stoch_d': np.float64(5.0), 'stoch_k': np.float64(8.0), 'stoch_slow': np.float64(4.0)} с использованием ML
Обрабатываем данные для модели Chronos... ->
==================================================
Выставляем параметры для модели Chronos... ->
Pretrain BaseChronosPipeline... ->
==================================================

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

==================================================
ChronosNextDayDirection... ->

Backtest.run:   0%|          | 0/1001 [00:00<?, ?bar/s]

======================================================================
ROC AUC (Train): 0.5103
======================================================================
Best threshold: 0.0095 Sharpe: 0.017368971243615517
==================================================
ChronosStrategy... ->

/tmp/ipython-input-2513420128.py:279: UserWarning: Data index is not sorted in ascending order. Sorting.
  bt_chronos = Backtest(

Backtest.run:   0%|          | 0/329 [00:00<?, ?bar/s]

==================================================
BuyHold... ->

/tmp/ipython-input-2513420128.py:292: UserWarning: Data index is not sorted in ascending order. Sorting.
  bt_bh = Backtest(

Backtest.run:   0%|          | 0/329 [00:00<?, ?bar/s]

==================================================
TemaGoldenCrossStrategy... ->

/tmp/ipython-input-2513420128.py:323: UserWarning: Data index is not sorted in ascending order. Sorting.
  btchronos = Backtest(test_datadf_neu, TemaGoldenCrossStrategy, cash=1000000, commission=.002, exclusive_orders=True, finalize_trades=True)

Backtest.run:   0%|          | 0/201 [00:00<?, ?bar/s]

'GoldenCrossStrategy:  '

,Buy&Hold,GoldenCross
Start,2024-05-24 00:00:00,2022-01-03 00:00:00
End,2025-12-31 00:00:00,2025-12-30 00:00:00
Duration,586 days 00:00:00,1457 days 00:00:00
Exposure Time [%],99.393939,73.353293
Equity Final [$],1441273.617706,553566.116092
Equity Peak [$],1513487.47556,1197079.900121
Commissions [$],4883.872895,444349.808957
Return [%],44.127362,-44.643388
Buy & Hold Return [%],44.071193,53.183087
Return (Ann.) [%],32.197899,-13.819721
Volatility (Ann.) [%],31.638022,19.438462
CAGR [%],17.021695,-9.722593
Sharpe Ratio,1.017696,-0.710947
Sortino Ratio,2.046376,-0.876456
Calmar Ratio,1.485367,-0.239826
Alpha [%],0.069345,-53.475393
Beta,0.999701,0.166068
Max. Drawdown [%],-21.676726,-57.623944
Avg. Drawdown [%],-3.977253,-9.359026
Max. Drawdown Duration,298 days 00:00:00,1090 days 00:00:00
Avg. Drawdown Duration,33 days 00:00:00,141 days 00:00:00
# Trades,1,139
Win Rate [%],100.0,45.323741
Best Trade [%],44.22069,8.918317
Worst Trade [%],44.22069,-11.545859
Avg. Trade [%],44.22069,-0.425549
Max. Trade Duration,581 days 00:00:00,42 days 00:00:00
Avg. Trade Duration,581 days 00:00:00,7 days 00:00:00
Profit Factor,NaN,0.711255
Expectancy [%],44.22069,-0.375839
SQN,NaN,-1.41825
Kelly Criterion,NaN,-0.192488
_strategy,BuyHold,ChronosNextDayDirection
_equity_curve,Equity DrawdownPct Drawdown...,Equity DrawdownPct Drawdo...
_trades,Size EntryBar ExitBar EntryPrice ExitP...,Size EntryBar ExitBar EntryPrice Exi...

'risk_adjusted_return = -21.93'

6. Набор данных Valid. Начало бэктестирования Strategy4 с оптимизированными гиперпараметрами на объединенном наборе Train и Test: {'bb_period': np.float64(44.0), 'bb_std': np.float64(2.8686392494556547), 'ema_period': np.float64(15.0), 'ma_period': np.float64(21.0), 'macd_fast': np.float64(18.0), 'macd_signal': np.float64(15.0), 'macd_slow': np.float64(24.0), 'rsi_period': np.float64(11.0), 'sma': np.float64(46.0), 'stoch_d': np.float64(5.0), 'stoch_k': np.float64(8.0), 'stoch_slow': np.float64(4.0)}
======================================================================
РАСПРЕДЕЛЕНИЕ КЛАССОВ
======================================================================
target
0    472
1    530
Name: count, dtype: int64

Баланс классов (доля класса 1): 0.529
Всего примеров: 1002
======================================================================
Размер окон признаков: (874, 128, 24)
Размер таргетов: (874,)
Размер индексов: (874,)
======================================================================
РАЗМЕРЫ ВЫБОРОК
======================================================================
Train: X=(874, 128, 24), y=(874,)
Test:  X=(459, 128, 24), y=(459,)

Распределение классов в test:
  Класс 0 (падение): 314 (68.4%)
  Класс 1 (рост):    145 (31.6%)
======================================================================
Train batches: 14
Test batches:  8

Пример батча:
  X: torch.Size([64, 128, 24])  (batch, lookback, num_features)
  y: torch.Size([64])  (batch,)

Пример батча test:
  X: torch.Size([64, 128, 24])  (batch, lookback, num_features)
  y: torch.Size([64])  (batch,)
======================================================================
Load tsmixer_full_AAPL.pt ...
Модель tsmixer_full_AAPL.pt загружена.
Загружены лучшие веса из tsmixer_full_AAPL.pt
======================================================================
ИНФОРМАЦИЯ О МОДЕЛИ
======================================================================
Всего параметров:      305,113
Обучаемых параметров:  305,113
Устройство:            cpu
======================================================================
Веса классов для Loss: 0 (Down): 1.0614, 1 (Up): 0.9453
✓ Optimizer, loss function и evaluation function настроены
======================================================================
НАЧАЛО ОБУЧЕНИЯ
======================================================================
======================================================================
ОБУЧЕНИЕ ЗАВЕРШЕНО. Лучшая точность: 0.0000
======================================================================
======================================================================
ЗАГРУЖАЕМ ЛУЧШИЕ ВЕСА ПЕРЕД ФИНАЛЬНОЙ ОЦЕНКОЙ
Загружены лучшие веса из tsmixer_full_AAPL.pt
======================================================================

======================================================================
ФИНАЛЬНЫЕ РЕЗУЛЬТАТЫ КЛАССИФИКАЦИИ
======================================================================
Test Accuracy: 0.4858 (48.58%)
Baseline (majority class): 0.6841 (68.41%)
Улучшение над baseline: -19.83%

----------------------------------------------------------------------
CLASSIFICATION REPORT
----------------------------------------------------------------------
              precision    recall  f1-score   support

    Down (0)     0.7053    0.4268    0.5317       314
      Up (1)     0.3309    0.6138    0.4300       145

    accuracy                         0.4858       459
   macro avg     0.5181    0.5203    0.4808       459
weighted avg     0.5870    0.4858    0.4996       459

----------------------------------------------------------------------
CONFUSION MATRIX
----------------------------------------------------------------------

              Predicted
                0      1
Actual 0      134    180
       1       56     89

----------------------------------------------------------------------
ИНТЕРПРЕТАЦИЯ
----------------------------------------------------------------------
True Positives (правильно предсказан рост):     89
True Negatives (правильно предсказано падение): 134
False Positives (ложный сигнал на рост):        180
False Negatives (пропущенный рост):             56

======================================================================
BACKTEST ТОРГОВЫХ СТРАТЕГИЙ
======================================================================
Buy & Hold:               24.81%
Strategy (Long only):     -5.60%
Strategy (Long/Short):   -31.82%
======================================================================

Sharpe Ratio (годовой):
  Buy & Hold:           0.598
  Strategy (Long only): -0.051
  Strategy (Long/Short):-0.679
======================================================================

/tmp/ipython-input-577606817.py:532: UserWarning: Data index is not sorted in ascending order. Sorting.
  bt = Backtest(test_datadf_neu_backtest, ChronosNextDayDirection, cash=1000000, commission=.002, exclusive_orders=True, finalize_trades=True)

Backtest.run:   0%|          | 0/458 [00:00<?, ?bar/s]

Start                     2025-03-17 00:00:00
End                       2025-12-31 00:00:00
Duration                    289 days 00:00:00
Exposure Time [%]                   79.084967
Equity Final [$]                764748.310612
Equity Peak [$]                1035790.051817
Commissions [$]                 321028.404895
Return [%]                         -23.525169
Buy & Hold Return [%]               27.471771
Return (Ann.) [%]                  -28.556368
Volatility (Ann.) [%]               14.126097
CAGR [%]                           -20.853561
Sharpe Ratio                        -2.021533
Sortino Ratio                       -1.905487
Calmar Ratio                        -1.083948
Alpha [%]                          -32.015442
Beta                                 0.309054
Max. Drawdown [%]                  -26.344775
Avg. Drawdown [%]                  -15.949156
Max. Drawdown Duration      279 days 00:00:00
Avg. Drawdown Duration      169 days 00:00:00
# Trades                                   96
Win Rate [%]                        33.333333
Best Trade [%]                        5.94225
Worst Trade [%]                    -11.693069
Avg. Trade [%]                      -0.279626
Max. Trade Duration          12 days 00:00:00
dtype: object

'risk_adjusted_return = -84.11'

Финальный ROC AUC на тесте: 0.5204
====================================================================================================

/usr/local/lib/python3.12/dist-packages/pandas/io/formats/style.py:3811: RuntimeWarning: invalid value encountered in scalar multiply
  norm = _matplotlib.colors.Normalize(smin - (rng * low), smax + (rng * high))

Анализ инструмента: MSFT
====================================================================================================

'\nЗагрузка данных с Yahoo Finance MSFT'

[*********************100%***********************]  1 of 1 completed

Размер данных: 1003 строк

Периоды наборов данных:
Train: 2022-01-03 - 2024-05-23
Test: 2024-05-24 - 2025-03-14
Valid: 2025-03-17 - 2025-12-31
TestMl: 2024-05-24 - 2025-03-14

1. Набор данных Train. Начало бэктестирования Strategy4 с гиперпараметрами по умолчанию: {'bb_period': 20, 'bb_std': 2.0, 'rsi_period': 14, 'sma': 10, 'ema_period': 4, 'ma_period': 10, 'macd_fast': 12, 'macd_slow': 26, 'macd_signal': 9, 'stoch_k': 14, 'stoch_d': 3, 'stoch_slow': 3}

Начало оптимизации гиперпараметров для Strategy4 на Train...
  0%|          | 0/50 [00:00<?, ?trial/s, best loss=?]

100%|██████████| 50/50 [00:01<00:00, 25.12trial/s, best loss: -0.5817160411030173]
Оптимальные гиперпараметры для Strategy4 на Train: {'bb_period': np.float64(27.0), 'bb_std': np.float64(1.7440107584828752), 'ema_period': np.float64(25.0), 'ma_period': np.float64(36.0), 'macd_fast': np.float64(18.0), 'macd_signal': np.float64(11.0), 'macd_slow': np.float64(22.0), 'rsi_period': np.float64(12.0), 'sma': np.float64(30.0), 'stoch_d': np.float64(6.0), 'stoch_k': np.float64(21.0), 'stoch_slow': np.float64(4.0)}

2. Набор данных Test. Начало бэктестирования Strategy4 с оптимизированными гиперпараметрами на наборе Train: {'bb_period': np.float64(27.0), 'bb_std': np.float64(1.7440107584828752), 'ema_period': np.float64(25.0), 'ma_period': np.float64(36.0), 'macd_fast': np.float64(18.0), 'macd_signal': np.float64(11.0), 'macd_slow': np.float64(22.0), 'rsi_period': np.float64(12.0), 'sma': np.float64(30.0), 'stoch_d': np.float64(6.0), 'stoch_k': np.float64(21.0), 'stoch_slow': np.float64(4.0)}

Объединенный набор данных Train и Test: 2022-01-03 - 2025-03-14

Начало оптимизации гиперпараметров для Strategy4 на объединенном наборе Train и Test...
100%|██████████| 50/50 [00:02<00:00, 23.42trial/s, best loss: -0.7222070254602946]
Оптимальные гиперпараметры для Strategy4 на объединенном наборе Train и Test: {'bb_period': np.float64(28.0), 'bb_std': np.float64(1.7177577754653477), 'ema_period': np.float64(19.0), 'ma_period': np.float64(34.0), 'macd_fast': np.float64(9.0), 'macd_signal': np.float64(5.0), 'macd_slow': np.float64(35.0), 'rsi_period': np.float64(14.0), 'sma': np.float64(32.0), 'stoch_d': np.float64(4.0), 'stoch_k': np.float64(16.0), 'stoch_slow': np.float64(5.0)}

3. Набор данных Test.  Начало бэктестирования Strategy4 с оптимизированными гиперпараметрами на наборе Test: {'bb_period': np.float64(28.0), 'bb_std': np.float64(1.7177577754653477), 'ema_period': np.float64(19.0), 'ma_period': np.float64(34.0), 'macd_fast': np.float64(9.0), 'macd_signal': np.float64(5.0), 'macd_slow': np.float64(35.0), 'rsi_period': np.float64(14.0), 'sma': np.float64(32.0), 'stoch_d': np.float64(4.0), 'stoch_k': np.float64(16.0), 'stoch_slow': np.float64(5.0)} с использованием ML

'Создаем объект класса Backtest'

'Запускаем бэктест'

Backtest.run:   0%|          | 0/113 [00:00<?, ?bar/s]

'Разделяем признаки и метки'

'RobustScaler'

Feature Importance:
 Mfi                9.349880
Adx                9.148534
Adosc              9.092931
Atr14              9.011469
Macd               7.159699
Slowd              7.063477
Obv                5.953191
Linearreg_angle    5.603886
Slowk              4.900044
Cci                4.825221
Rsi                4.711482
Engulfing          4.431596
Bb_middle          3.911332
Ma_period          3.489758
Bb_lower           3.348336
Sma                3.283727
Bb_upper           3.263427
Sar                0.923645
Morningstar        0.383474
Doji               0.144890
Hammer             0.000000
dtype: float64

'Повторяем все тоже самое с данными для теста'

'Для предсказания используем данные в столбацах ниже'

'Выводим предсказание'

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
0.7272727272727273
[[ 0  9]
 [ 0 24]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         9
           1       0.73      1.00      0.84        24

    accuracy                           0.73        33
   macro avg       0.36      0.50      0.42        33
weighted avg       0.53      0.73      0.61        33

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Backtest.run:   0%|          | 0/32 [00:00<?, ?bar/s]

Start                     2024-07-17 00:00:00
End                       2025-02-06 00:00:00
Duration                    204 days 00:00:00
Exposure Time [%]                   90.909091
Equity Final [$]                959541.115954
Equity Peak [$]                     1000000.0
Commissions [$]                   60596.37949
Return [%]                          -4.045888
Buy & Hold Return [%]               -5.888507
Return (Ann.) [%]                  -27.049035
Volatility (Ann.) [%]               21.157122
CAGR [%]                            -4.973823
Sharpe Ratio                        -1.278484
Sortino Ratio                       -1.437377
Calmar Ratio                        -2.614861
Alpha [%]                           -7.071148
Beta                                -0.513757
Max. Drawdown [%]                  -10.344351
Avg. Drawdown [%]                  -10.344351
Max. Drawdown Duration      168 days 00:00:00
Avg. Drawdown Duration      168 days 00:00:00
# Trades                                   16
Win Rate [%]                             37.5
Best Trade [%]                       3.902865
Worst Trade [%]                     -4.695238
Avg. Trade [%]                      -0.258391
Max. Trade Duration          29 days 00:00:00
dtype: object

'Выводим график :'

'Выводим Buy&Hold и GoldenCross :'

                                   Buy&Hold          GoldenCross
Start                   2022-02-24 00:00:00  2024-07-17 00:00:00
End                     2025-12-02 00:00:00  2025-02-06 00:00:00
Duration                 1377 days 00:00:00    204 days 00:00:00
Exposure Time [%]                 98.245614            90.909091
Equity Final [$]              498746.280565        959541.115954
Equity Peak [$]              1059650.753627            1000000.0
Commissions [$]               102869.967432          60596.37949
Return [%]                       -50.125372            -4.045888
Buy & Hold Return [%]             71.550861            -5.888507
Return (Ann.) [%]                -78.514025           -27.049035
Volatility (Ann.) [%]             18.355848            21.157122
CAGR [%]                         -11.953924            -4.973823
Sharpe Ratio                       -4.27733            -1.278484
Sortino Ratio                     -1.395901            -1.437377
Calmar Ratio                      -1.244504            -2.614861
Alpha [%]                         -5.407901            -7.071148
Beta                              -0.624975            -0.513757
Max. Drawdown [%]                -63.088623           -10.344351
Avg. Drawdown [%]                -32.970968           -10.344351
Max. Drawdown Duration   1275 days 00:00:00    168 days 00:00:00
Avg. Drawdown Duration    685 days 00:00:00    168 days 00:00:00
# Trades                                 38                   16
Win Rate [%]                      36.842105                 37.5
Best Trade [%]                     12.82382             3.902865
Worst Trade [%]                  -27.974312            -4.695238
Avg. Trade [%]                    -1.818547            -0.258391
Max. Trade Duration       259 days 00:00:00     29 days 00:00:00

risk_adjusted_return = -3.22
ROC AUC Score: 0.5926
Немного лучше случайного угадывания

4. Набор данных Test. Модель TSMixer. Начало бэктестирования Strategy4 с оптимизированными гиперпараметрами на наборе Test: {'bb_period': np.float64(28.0), 'bb_std': np.float64(1.7177577754653477), 'ema_period': np.float64(19.0), 'ma_period': np.float64(34.0), 'macd_fast': np.float64(9.0), 'macd_signal': np.float64(5.0), 'macd_slow': np.float64(35.0), 'rsi_period': np.float64(14.0), 'sma': np.float64(32.0), 'stoch_d': np.float64(4.0), 'stoch_k': np.float64(16.0), 'stoch_slow': np.float64(5.0)} с использованием ML
======================================================================
РАСПРЕДЕЛЕНИЕ КЛАССОВ
======================================================================
target
0    478
1    524
Name: count, dtype: int64

Баланс классов (доля класса 1): 0.523
Всего примеров: 1002
======================================================================
Размер окон признаков: (874, 128, 24)
Размер таргетов: (874,)
Размер индексов: (874,)
======================================================================
РАЗМЕРЫ ВЫБОРОК
======================================================================
Train: X=(874, 128, 24), y=(874,)
Test:  X=(201, 128, 24), y=(201,)

Распределение классов в test:
  Класс 0 (падение): 93 (46.3%)
  Класс 1 (рост):    108 (53.7%)
======================================================================
Train batches: 14
Test batches:  4

Пример батча:
  X: torch.Size([64, 128, 24])  (batch, lookback, num_features)
  y: torch.Size([64])  (batch,)

Пример батча test:
  X: torch.Size([64, 128, 24])  (batch, lookback, num_features)
  y: torch.Size([64])  (batch,)
======================================================================
Загружены лучшие веса из tsmixer_full_MSFT.pt
======================================================================
ИНФОРМАЦИЯ О МОДЕЛИ
======================================================================
Всего параметров:      305,113
Обучаемых параметров:  305,113
Устройство:            cpu
======================================================================
Установлен новый Optimizer: AdamW с weight decay для регуляризации
Веса классов для Loss: 0 (Down): 1.0481, 1 (Up): 0.9561
✓ Optimizer, loss function и evaluation function настроены
======================================================================
НАЧАЛО ОБУЧЕНИЯ
======================================================================
Epoch  1/50 | Train Loss: 0.6944 | Train Acc: 0.4828 | Test Acc: 0.5075 | [Model Saved! Best Acc: 0.5075]
Epoch  2/50 | Train Loss: 0.6923 | Train Acc: 0.4966 | Test Acc: 0.5174 | [Model Saved! Best Acc: 0.5174]
Epoch  3/50 | Train Loss: 0.6904 | Train Acc: 0.5355 | Test Acc: 0.5274 | [Model Saved! Best Acc: 0.5274]
Epoch  4/50 | Train Loss: 0.6901 | Train Acc: 0.5217 | Test Acc: 0.5274
Epoch  5/50 | Train Loss: 0.6907 | Train Acc: 0.5435 | Test Acc: 0.5025
Epoch  6/50 | Train Loss: 0.6872 | Train Acc: 0.5538 | Test Acc: 0.5274
Epoch  7/50 | Train Loss: 0.6879 | Train Acc: 0.5526 | Test Acc: 0.5224
Epoch  8/50 | Train Loss: 0.6854 | Train Acc: 0.5641 | Test Acc: 0.5423 | [Model Saved! Best Acc: 0.5423]
Epoch  9/50 | Train Loss: 0.6827 | Train Acc: 0.5515 | Test Acc: 0.5323
Epoch 10/50 | Train Loss: 0.6818 | Train Acc: 0.5755 | Test Acc: 0.5323
Epoch 11/50 | Train Loss: 0.6737 | Train Acc: 0.5904 | Test Acc: 0.5075
Epoch 12/50 | Train Loss: 0.6695 | Train Acc: 0.5881 | Test Acc: 0.5174
Epoch 13/50 | Train Loss: 0.6589 | Train Acc: 0.6156 | Test Acc: 0.5373
Epoch 14/50 | Train Loss: 0.6589 | Train Acc: 0.6213 | Test Acc: 0.5423
Epoch 15/50 | Train Loss: 0.6415 | Train Acc: 0.6350 | Test Acc: 0.5572 | [Model Saved! Best Acc: 0.5572]
Epoch 16/50 | Train Loss: 0.6221 | Train Acc: 0.6476 | Test Acc: 0.5572
Epoch 17/50 | Train Loss: 0.6288 | Train Acc: 0.6522 | Test Acc: 0.5771 | [Model Saved! Best Acc: 0.5771]
Epoch 18/50 | Train Loss: 0.5969 | Train Acc: 0.6819 | Test Acc: 0.5721
Epoch 19/50 | Train Loss: 0.5855 | Train Acc: 0.6888 | Test Acc: 0.5672
Epoch 20/50 | Train Loss: 0.5705 | Train Acc: 0.7140 | Test Acc: 0.5821 | [Model Saved! Best Acc: 0.5821]
Epoch 21/50 | Train Loss: 0.5503 | Train Acc: 0.7071 | Test Acc: 0.5771
Epoch 22/50 | Train Loss: 0.5194 | Train Acc: 0.7449 | Test Acc: 0.5821
Epoch 23/50 | Train Loss: 0.4940 | Train Acc: 0.7517 | Test Acc: 0.5821
Epoch 24/50 | Train Loss: 0.4824 | Train Acc: 0.7815 | Test Acc: 0.5871 | [Model Saved! Best Acc: 0.5871]
Epoch 25/50 | Train Loss: 0.4347 | Train Acc: 0.8021 | Test Acc: 0.5721
Epoch 26/50 | Train Loss: 0.4331 | Train Acc: 0.8135 | Test Acc: 0.6169 | [Model Saved! Best Acc: 0.6169]
Epoch 27/50 | Train Loss: 0.4030 | Train Acc: 0.8158 | Test Acc: 0.6269 | [Model Saved! Best Acc: 0.6269]
Epoch 28/50 | Train Loss: 0.3895 | Train Acc: 0.8249 | Test Acc: 0.6368 | [Model Saved! Best Acc: 0.6368]
Epoch 29/50 | Train Loss: 0.3591 | Train Acc: 0.8364 | Test Acc: 0.6269
Epoch 30/50 | Train Loss: 0.3327 | Train Acc: 0.8432 | Test Acc: 0.6716 | [Model Saved! Best Acc: 0.6716]
Epoch 31/50 | Train Loss: 0.3164 | Train Acc: 0.8627 | Test Acc: 0.6567
Epoch 32/50 | Train Loss: 0.2787 | Train Acc: 0.8661 | Test Acc: 0.6517
Epoch 33/50 | Train Loss: 0.2695 | Train Acc: 0.8879 | Test Acc: 0.6716
Epoch 34/50 | Train Loss: 0.2473 | Train Acc: 0.9050 | Test Acc: 0.6667
Epoch 35/50 | Train Loss: 0.2100 | Train Acc: 0.9211 | Test Acc: 0.6667
Epoch 36/50 | Train Loss: 0.2035 | Train Acc: 0.9085 | Test Acc: 0.6716
Epoch 37/50 | Train Loss: 0.2084 | Train Acc: 0.9176 | Test Acc: 0.6816 | [Model Saved! Best Acc: 0.6816]
Epoch 38/50 | Train Loss: 0.2000 | Train Acc: 0.9165 | Test Acc: 0.6866 | [Model Saved! Best Acc: 0.6866]
Epoch 39/50 | Train Loss: 0.1720 | Train Acc: 0.9348 | Test Acc: 0.7065 | [Model Saved! Best Acc: 0.7065]
Epoch 40/50 | Train Loss: 0.1577 | Train Acc: 0.9451 | Test Acc: 0.7114 | [Model Saved! Best Acc: 0.7114]
Epoch 41/50 | Train Loss: 0.1700 | Train Acc: 0.9325 | Test Acc: 0.7114
Epoch 42/50 | Train Loss: 0.1396 | Train Acc: 0.9451 | Test Acc: 0.7015
Epoch 43/50 | Train Loss: 0.1250 | Train Acc: 0.9462 | Test Acc: 0.7114
Epoch 44/50 | Train Loss: 0.1342 | Train Acc: 0.9428 | Test Acc: 0.7214 | [Model Saved! Best Acc: 0.7214]
Epoch 45/50 | Train Loss: 0.1053 | Train Acc: 0.9657 | Test Acc: 0.6915
Epoch 46/50 | Train Loss: 0.1000 | Train Acc: 0.9622 | Test Acc: 0.7114
Epoch 47/50 | Train Loss: 0.0770 | Train Acc: 0.9737 | Test Acc: 0.7214
Epoch 48/50 | Train Loss: 0.1023 | Train Acc: 0.9622 | Test Acc: 0.7413 | [Model Saved! Best Acc: 0.7413]
Epoch 49/50 | Train Loss: 0.0729 | Train Acc: 0.9783 | Test Acc: 0.7463 | [Model Saved! Best Acc: 0.7463]
Epoch 50/50 | Train Loss: 0.0640 | Train Acc: 0.9760 | Test Acc: 0.7512 | [Model Saved! Best Acc: 0.7512]
======================================================================
ОБУЧЕНИЕ ЗАВЕРШЕНО. Лучшая точность: 0.7512
======================================================================
======================================================================
ЗАГРУЖАЕМ ЛУЧШИЕ ВЕСА ПЕРЕД ФИНАЛЬНОЙ ОЦЕНКОЙ
Загружены лучшие веса из tsmixer_full_MSFT.pt
======================================================================

======================================================================
ФИНАЛЬНЫЕ РЕЗУЛЬТАТЫ КЛАССИФИКАЦИИ
======================================================================
Test Accuracy: 0.7512 (75.12%)
Baseline (majority class): 0.5373 (53.73%)
Улучшение над baseline: 21.39%

----------------------------------------------------------------------
CLASSIFICATION REPORT
----------------------------------------------------------------------
              precision    recall  f1-score   support

    Down (0)     0.7129    0.7742    0.7423        93
      Up (1)     0.7900    0.7315    0.7596       108

    accuracy                         0.7512       201
   macro avg     0.7514    0.7528    0.7509       201
weighted avg     0.7543    0.7512    0.7516       201

----------------------------------------------------------------------
CONFUSION MATRIX
----------------------------------------------------------------------

              Predicted
                0      1
Actual 0       72     21
       1       29     79

----------------------------------------------------------------------
ИНТЕРПРЕТАЦИЯ
----------------------------------------------------------------------
True Positives (правильно предсказан рост):     79
True Negatives (правильно предсказано падение): 72
False Positives (ложный сигнал на рост):        21
False Negatives (пропущенный рост):             29

======================================================================
BACKTEST ТОРГОВЫХ СТРАТЕГИЙ
======================================================================
Buy & Hold:               11.18%
Strategy (Long only):     29.35%
Strategy (Long/Short):    43.20%
======================================================================

Sharpe Ratio (годовой):
  Buy & Hold:           0.559
  Strategy (Long only): 1.503
  Strategy (Long/Short):1.493
======================================================================

/tmp/ipython-input-577606817.py:532: UserWarning: Data index is not sorted in ascending order. Sorting.
  bt = Backtest(test_datadf_neu_backtest, ChronosNextDayDirection, cash=1000000, commission=.002, exclusive_orders=True, finalize_trades=True)

Backtest.run:   0%|          | 0/200 [00:00<?, ?bar/s]

Start                     2024-05-24 00:00:00
End                       2025-12-31 00:00:00
Duration                    586 days 00:00:00
Exposure Time [%]                   75.124378
Equity Final [$]               1159756.575759
Equity Peak [$]                1178500.492267
Commissions [$]                 220240.608146
Return [%]                          15.975658
Buy & Hold Return [%]               13.688537
Return (Ann.) [%]                    20.42003
Volatility (Ann.) [%]               17.757935
CAGR [%]                             6.581037
Sharpe Ratio                          1.14991
Sortino Ratio                        1.999848
Calmar Ratio                         2.399798
Alpha [%]                           13.802657
Beta                                 0.158746
Max. Drawdown [%]                   -8.509062
Avg. Drawdown [%]                   -1.905078
Max. Drawdown Duration      301 days 00:00:00
Avg. Drawdown Duration       38 days 00:00:00
# Trades                                   53
Win Rate [%]                        54.716981
Best Trade [%]                       4.592955
Worst Trade [%]                     -5.437445
Avg. Trade [%]                       0.280609
Max. Trade Duration           8 days 00:00:00
dtype: object

'risk_adjusted_return = -78.16'

Финальный ROC AUC на тесте: 0.8035

5. Набор данных Test. Модель Chronos. Начало бэктестирования Strategy4 с оптимизированными гиперпараметрами на наборе Test: {'bb_period': np.float64(28.0), 'bb_std': np.float64(1.7177577754653477), 'ema_period': np.float64(19.0), 'ma_period': np.float64(34.0), 'macd_fast': np.float64(9.0), 'macd_signal': np.float64(5.0), 'macd_slow': np.float64(35.0), 'rsi_period': np.float64(14.0), 'sma': np.float64(32.0), 'stoch_d': np.float64(4.0), 'stoch_k': np.float64(16.0), 'stoch_slow': np.float64(5.0)} с использованием ML
Обрабатываем данные для модели Chronos... ->
==================================================
Выставляем параметры для модели Chronos... ->
Pretrain BaseChronosPipeline... ->
==================================================
==================================================
ChronosNextDayDirection... ->

Backtest.run:   0%|          | 0/1001 [00:00<?, ?bar/s]

======================================================================
ROC AUC (Train): 0.4661
======================================================================
Best threshold: 0.0 Sharpe: 0.024927893657023605
==================================================
ChronosStrategy... ->

/tmp/ipython-input-2513420128.py:279: UserWarning: Data index is not sorted in ascending order. Sorting.
  bt_chronos = Backtest(

Backtest.run:   0%|          | 0/329 [00:00<?, ?bar/s]

==================================================
BuyHold... ->

/tmp/ipython-input-2513420128.py:292: UserWarning: Data index is not sorted in ascending order. Sorting.
  bt_bh = Backtest(

Backtest.run:   0%|          | 0/329 [00:00<?, ?bar/s]

==================================================
TemaGoldenCrossStrategy... ->

/tmp/ipython-input-2513420128.py:323: UserWarning: Data index is not sorted in ascending order. Sorting.
  btchronos = Backtest(test_datadf_neu, TemaGoldenCrossStrategy, cash=1000000, commission=.002, exclusive_orders=True, finalize_trades=True)

Backtest.run:   0%|          | 0/201 [00:00<?, ?bar/s]

'GoldenCrossStrategy:  '

,Buy&Hold,GoldenCross
Start,2024-05-24 00:00:00,2022-01-03 00:00:00
End,2025-12-31 00:00:00,2025-12-30 00:00:00
Duration,586 days 00:00:00,1457 days 00:00:00
Exposure Time [%],99.393939,69.261477
Equity Final [$],1140947.163916,420252.29003
Equity Peak [$],1268872.3592,1107878.244495
Commissions [$],4282.103967,382057.939553
Return [%],14.094716,-57.974771
Buy & Hold Return [%],13.688537,50.504014
Return (Ann.) [%],10.593612,-19.589287
Volatility (Ann.) [%],36.362067,16.093908
CAGR [%],5.834225,-13.923815
Sharpe Ratio,0.291337,-1.217186
Sortino Ratio,0.678553,-1.354885
Calmar Ratio,0.572103,-0.312521
Alpha [%],0.41252,-69.036903
Beta,0.999537,0.219035
Max. Drawdown [%],-18.516976,-62.681464
Avg. Drawdown [%],-3.611777,-9.86516
Max. Drawdown Duration,360 days 00:00:00,1167 days 00:00:00
Avg. Drawdown Duration,41 days 00:00:00,159 days 00:00:00
# Trades,1,138
Win Rate [%],100.0,41.304348
Best Trade [%],14.124217,10.516897
Worst Trade [%],14.124217,-15.049635
Avg. Trade [%],14.124217,-0.627867
Max. Trade Duration,581 days 00:00:00,57 days 00:00:00
Avg. Trade Duration,581 days 00:00:00,6 days 00:00:00
Profit Factor,NaN,0.575828
Expectancy [%],14.124217,-0.580357
SQN,NaN,-2.043048
Kelly Criterion,NaN,-0.29467
_strategy,BuyHold,ChronosNextDayDirection
_equity_curve,Equity DrawdownPct Drawdown...,Equity DrawdownPct Drawdo...
_trades,Size EntryBar ExitBar EntryPrice ExitP...,Size EntryBar ExitBar EntryPrice Exi...

'risk_adjusted_return = -89.86'

6. Набор данных Valid. Начало бэктестирования Strategy4 с оптимизированными гиперпараметрами на объединенном наборе Train и Test: {'bb_period': np.float64(28.0), 'bb_std': np.float64(1.7177577754653477), 'ema_period': np.float64(19.0), 'ma_period': np.float64(34.0), 'macd_fast': np.float64(9.0), 'macd_signal': np.float64(5.0), 'macd_slow': np.float64(35.0), 'rsi_period': np.float64(14.0), 'sma': np.float64(32.0), 'stoch_d': np.float64(4.0), 'stoch_k': np.float64(16.0), 'stoch_slow': np.float64(5.0)}
======================================================================
РАСПРЕДЕЛЕНИЕ КЛАССОВ
======================================================================
target
0    478
1    524
Name: count, dtype: int64

Баланс классов (доля класса 1): 0.523
Всего примеров: 1002
======================================================================
Размер окон признаков: (874, 128, 24)
Размер таргетов: (874,)
Размер индексов: (874,)
======================================================================
РАЗМЕРЫ ВЫБОРОК
======================================================================
Train: X=(874, 128, 24), y=(874,)
Test:  X=(459, 128, 24), y=(459,)

Распределение классов в test:
  Класс 0 (падение): 316 (68.8%)
  Класс 1 (рост):    143 (31.2%)
======================================================================
Train batches: 14
Test batches:  8

Пример батча:
  X: torch.Size([64, 128, 24])  (batch, lookback, num_features)
  y: torch.Size([64])  (batch,)

Пример батча test:
  X: torch.Size([64, 128, 24])  (batch, lookback, num_features)
  y: torch.Size([64])  (batch,)
======================================================================
Load tsmixer_full_MSFT.pt ...
Модель tsmixer_full_MSFT.pt загружена.
Загружены лучшие веса из tsmixer_full_MSFT.pt
======================================================================
ИНФОРМАЦИЯ О МОДЕЛИ
======================================================================
Всего параметров:      305,113
Обучаемых параметров:  305,113
Устройство:            cpu
======================================================================
Веса классов для Loss: 0 (Down): 1.0481, 1 (Up): 0.9561
✓ Optimizer, loss function и evaluation function настроены
======================================================================
НАЧАЛО ОБУЧЕНИЯ
======================================================================
======================================================================
ОБУЧЕНИЕ ЗАВЕРШЕНО. Лучшая точность: 0.0000
======================================================================
======================================================================
ЗАГРУЖАЕМ ЛУЧШИЕ ВЕСА ПЕРЕД ФИНАЛЬНОЙ ОЦЕНКОЙ
Загружены лучшие веса из tsmixer_full_MSFT.pt
======================================================================

======================================================================
ФИНАЛЬНЫЕ РЕЗУЛЬТАТЫ КЛАССИФИКАЦИИ
======================================================================
Test Accuracy: 0.5076 (50.76%)
Baseline (majority class): 0.6885 (68.85%)
Улучшение над baseline: -18.08%

----------------------------------------------------------------------
CLASSIFICATION REPORT
----------------------------------------------------------------------
              precision    recall  f1-score   support

    Down (0)     0.6974    0.5032    0.5846       316
      Up (1)     0.3203    0.5175    0.3957       143

    accuracy                         0.5076       459
   macro avg     0.5089    0.5103    0.4901       459
weighted avg     0.5799    0.5076    0.5257       459

----------------------------------------------------------------------
CONFUSION MATRIX
----------------------------------------------------------------------

              Predicted
                0      1
Actual 0      159    157
       1       69     74

----------------------------------------------------------------------
ИНТЕРПРЕТАЦИЯ
----------------------------------------------------------------------
True Positives (правильно предсказан рост):     74
True Negatives (правильно предсказано падение): 159
False Positives (ложный сигнал на рост):        157
False Negatives (пропущенный рост):             69

======================================================================
BACKTEST ТОРГОВЫХ СТРАТЕГИЙ
======================================================================
Buy & Hold:               56.93%
Strategy (Long only):     49.05%
Strategy (Long/Short):    32.00%
======================================================================

Sharpe Ratio (годовой):
  Buy & Hold:           1.034
  Strategy (Long only): 1.221
  Strategy (Long/Short):0.689
======================================================================

/tmp/ipython-input-577606817.py:532: UserWarning: Data index is not sorted in ascending order. Sorting.
  bt = Backtest(test_datadf_neu_backtest, ChronosNextDayDirection, cash=1000000, commission=.002, exclusive_orders=True, finalize_trades=True)

Backtest.run:   0%|          | 0/458 [00:00<?, ?bar/s]

Start                     2025-03-17 00:00:00
End                       2025-12-31 00:00:00
Duration                    289 days 00:00:00
Exposure Time [%]                   69.934641
Equity Final [$]                876730.964608
Equity Peak [$]                1197903.972203
Commissions [$]                 380948.425129
Return [%]                         -12.326904
Buy & Hold Return [%]               25.086856
Return (Ann.) [%]                  -15.205097
Volatility (Ann.) [%]               17.668095
CAGR [%]                           -10.837747
Sharpe Ratio                        -0.860596
Sortino Ratio                       -1.254343
Calmar Ratio                        -0.556989
Alpha [%]                          -29.497538
Beta                                 0.684447
Max. Drawdown [%]                  -27.298748
Avg. Drawdown [%]                   -8.747107
Max. Drawdown Duration      153 days 00:00:00
Avg. Drawdown Duration       48 days 00:00:00
# Trades                                   93
Win Rate [%]                        31.182796
Best Trade [%]                      11.256233
Worst Trade [%]                     -4.036238
Avg. Trade [%]                      -0.141723
Max. Trade Duration          11 days 00:00:00
dtype: object

'risk_adjusted_return = -6.24'

Финальный ROC AUC на тесте: 0.5299
====================================================================================================

/usr/local/lib/python3.12/dist-packages/pandas/io/formats/style.py:3811: RuntimeWarning: invalid value encountered in scalar multiply
  norm = _matplotlib.colors.Normalize(smin - (rng * low), smax + (rng * high))

Анализ инструмента: GOOGL
====================================================================================================

'\nЗагрузка данных с Yahoo Finance GOOGL'

[*********************100%***********************]  1 of 1 completed

Размер данных: 1003 строк

Периоды наборов данных:
Train: 2022-01-03 - 2024-05-23
Test: 2024-05-24 - 2025-03-14
Valid: 2025-03-17 - 2025-12-31
TestMl: 2024-05-24 - 2025-03-14

1. Набор данных Train. Начало бэктестирования Strategy4 с гиперпараметрами по умолчанию: {'bb_period': 20, 'bb_std': 2.0, 'rsi_period': 14, 'sma': 10, 'ema_period': 4, 'ma_period': 10, 'macd_fast': 12, 'macd_slow': 26, 'macd_signal': 9, 'stoch_k': 14, 'stoch_d': 3, 'stoch_slow': 3}

Начало оптимизации гиперпараметров для Strategy4 на Train...
  0%|          | 0/50 [00:00<?, ?trial/s, best loss=?]

100%|██████████| 50/50 [00:02<00:00, 17.08trial/s, best loss: -1.1437760775912065]
Оптимальные гиперпараметры для Strategy4 на Train: {'bb_period': np.float64(14.0), 'bb_std': np.float64(1.7455237251171234), 'ema_period': np.float64(17.0), 'ma_period': np.float64(10.0), 'macd_fast': np.float64(19.0), 'macd_signal': np.float64(8.0), 'macd_slow': np.float64(40.0), 'rsi_period': np.float64(7.0), 'sma': np.float64(48.0), 'stoch_d': np.float64(3.0), 'stoch_k': np.float64(12.0), 'stoch_slow': np.float64(3.0)}

2. Набор данных Test. Начало бэктестирования Strategy4 с оптимизированными гиперпараметрами на наборе Train: {'bb_period': np.float64(14.0), 'bb_std': np.float64(1.7455237251171234), 'ema_period': np.float64(17.0), 'ma_period': np.float64(10.0), 'macd_fast': np.float64(19.0), 'macd_signal': np.float64(8.0), 'macd_slow': np.float64(40.0), 'rsi_period': np.float64(7.0), 'sma': np.float64(48.0), 'stoch_d': np.float64(3.0), 'stoch_k': np.float64(12.0), 'stoch_slow': np.float64(3.0)}

Объединенный набор данных Train и Test: 2022-01-03 - 2025-03-14

Начало оптимизации гиперпараметров для Strategy4 на объединенном наборе Train и Test...
100%|██████████| 50/50 [00:02<00:00, 20.02trial/s, best loss: -1.2271288933075213]
Оптимальные гиперпараметры для Strategy4 на объединенном наборе Train и Test: {'bb_period': np.float64(10.0), 'bb_std': np.float64(1.6971694262222652), 'ema_period': np.float64(18.0), 'ma_period': np.float64(32.0), 'macd_fast': np.float64(18.0), 'macd_signal': np.float64(14.0), 'macd_slow': np.float64(24.0), 'rsi_period': np.float64(16.0), 'sma': np.float64(11.0), 'stoch_d': np.float64(5.0), 'stoch_k': np.float64(16.0), 'stoch_slow': np.float64(7.0)}

3. Набор данных Test.  Начало бэктестирования Strategy4 с оптимизированными гиперпараметрами на наборе Test: {'bb_period': np.float64(10.0), 'bb_std': np.float64(1.6971694262222652), 'ema_period': np.float64(18.0), 'ma_period': np.float64(32.0), 'macd_fast': np.float64(18.0), 'macd_signal': np.float64(14.0), 'macd_slow': np.float64(24.0), 'rsi_period': np.float64(16.0), 'sma': np.float64(11.0), 'stoch_d': np.float64(5.0), 'stoch_k': np.float64(16.0), 'stoch_slow': np.float64(7.0)} с использованием ML

'Создаем объект класса Backtest'

'Запускаем бэктест'

Backtest.run:   0%|          | 0/137 [00:00<?, ?bar/s]

'Разделяем признаки и метки'

'RobustScaler'

Feature Importance:
 Mfi                8.742482
Atr14              8.404325
Adosc              7.392474
Linearreg_angle    7.186771
Adx                6.908534
Slowd              6.858115
Slowk              6.799921
Rsi                6.089863
Cci                5.737338
Macd               4.403013
Sma                3.996760
Ma_period          3.612280
Engulfing          3.607528
Bb_middle          3.470272
Bb_lower           3.363716
Obv                3.361065
Bb_upper           3.250872
Morningstar        2.608946
Doji               2.120873
Sar                2.084852
Hammer             0.000000
dtype: float64

'Повторяем все тоже самое с данными для теста'

'Для предсказания используем данные в столбацах ниже'

'Выводим предсказание'

[1 0 0 1 1 1 0 0 0 0 0 1 1 1 0 0 0 1 0 0 0 0 0 1 0 0 0 1 1]
0.27586206896551724
[[ 3  6]
 [15  5]]
              precision    recall  f1-score   support

           0       0.17      0.33      0.22         9
           1       0.45      0.25      0.32        20

    accuracy                           0.28        29
   macro avg       0.31      0.29      0.27        29
weighted avg       0.37      0.28      0.29        29

Backtest.run:   0%|          | 0/28 [00:00<?, ?bar/s]

Start                     2024-08-02 00:00:00
End                       2025-02-10 00:00:00
Duration                    192 days 00:00:00
Exposure Time [%]                   44.827586
Equity Final [$]                872832.051024
Equity Peak [$]                     1000000.0
Commissions [$]                  25966.993663
Return [%]                         -12.716795
Buy & Hold Return [%]               12.163353
Return (Ann.) [%]                  -69.330406
Volatility (Ann.) [%]                8.457544
CAGR [%]                           -16.348925
Sharpe Ratio                        -8.197464
Sortino Ratio                       -2.744602
Calmar Ratio                        -5.451877
Alpha [%]                           -12.10165
Beta                                -0.050574
Max. Drawdown [%]                  -12.716795
Avg. Drawdown [%]                  -12.716795
Max. Drawdown Duration      158 days 00:00:00
Avg. Drawdown Duration      158 days 00:00:00
# Trades                                    7
Win Rate [%]                        14.285714
Best Trade [%]                       0.328331
Worst Trade [%]                     -6.530961
Avg. Trade [%]                      -1.928304
Max. Trade Duration          41 days 00:00:00
dtype: object

'Выводим график :'

'Выводим Buy&Hold и GoldenCross :'

                                   Buy&Hold          GoldenCross
Start                   2022-03-16 00:00:00  2024-08-02 00:00:00
End                     2025-12-22 00:00:00  2025-02-10 00:00:00
Duration                 1377 days 00:00:00    192 days 00:00:00
Exposure Time [%]                 98.550725            44.827586
Equity Final [$]              157116.175976        872832.051024
Equity Peak [$]              1241024.699992            1000000.0
Commissions [$]               125412.009495         25966.993663
Return [%]                       -84.288382           -12.716795
Buy & Hold Return [%]            134.183253            12.163353
Return (Ann.) [%]                -57.330323           -69.330406
Volatility (Ann.) [%]             22.590782             8.457544
CAGR [%]                          -6.750463           -16.348925
Sharpe Ratio                      -2.537775            -8.197464
Sortino Ratio                     -1.350673            -2.744602
Calmar Ratio                       -0.64612            -5.451877
Alpha [%]                         35.048462            -12.10165
Beta                              -0.889357            -0.050574
Max. Drawdown [%]                -88.730192           -12.716795
Avg. Drawdown [%]                -25.754476           -12.716795
Max. Drawdown Duration   1202 days 00:00:00    158 days 00:00:00
Avg. Drawdown Duration    317 days 00:00:00    158 days 00:00:00
# Trades                                 51                    7
Win Rate [%]                      33.333333            14.285714
Best Trade [%]                    18.113954             0.328331
Worst Trade [%]                  -55.884979            -6.530961
Avg. Trade [%]                    -3.573869            -1.928304
Max. Trade Duration       224 days 00:00:00     41 days 00:00:00

risk_adjusted_return = -310.53
ROC AUC Score: 0.2972
Эквивалентна случайному угадыванию

4. Набор данных Test. Модель TSMixer. Начало бэктестирования Strategy4 с оптимизированными гиперпараметрами на наборе Test: {'bb_period': np.float64(10.0), 'bb_std': np.float64(1.6971694262222652), 'ema_period': np.float64(18.0), 'ma_period': np.float64(32.0), 'macd_fast': np.float64(18.0), 'macd_signal': np.float64(14.0), 'macd_slow': np.float64(24.0), 'rsi_period': np.float64(16.0), 'sma': np.float64(11.0), 'stoch_d': np.float64(5.0), 'stoch_k': np.float64(16.0), 'stoch_slow': np.float64(7.0)} с использованием ML
======================================================================
РАСПРЕДЕЛЕНИЕ КЛАССОВ
======================================================================
target
0    470
1    532
Name: count, dtype: int64

Баланс классов (доля класса 1): 0.531
Всего примеров: 1002
======================================================================
Размер окон признаков: (874, 128, 24)
Размер таргетов: (874,)
Размер индексов: (874,)
======================================================================
РАЗМЕРЫ ВЫБОРОК
======================================================================
Train: X=(874, 128, 24), y=(874,)
Test:  X=(201, 128, 24), y=(201,)

Распределение классов в test:
  Класс 0 (падение): 92 (45.8%)
  Класс 1 (рост):    109 (54.2%)
======================================================================
Train batches: 14
Test batches:  4

Пример батча:
  X: torch.Size([64, 128, 24])  (batch, lookback, num_features)
  y: torch.Size([64])  (batch,)

Пример батча test:
  X: torch.Size([64, 128, 24])  (batch, lookback, num_features)
  y: torch.Size([64])  (batch,)
======================================================================
Загружены лучшие веса из tsmixer_full_GOOGL.pt
======================================================================
ИНФОРМАЦИЯ О МОДЕЛИ
======================================================================
Всего параметров:      305,113
Обучаемых параметров:  305,113
Устройство:            cpu
======================================================================
Установлен новый Optimizer: AdamW с weight decay для регуляризации
Веса классов для Loss: 0 (Down): 1.0660, 1 (Up): 0.9417
✓ Optimizer, loss function и evaluation function настроены
======================================================================
НАЧАЛО ОБУЧЕНИЯ
======================================================================
Epoch  1/50 | Train Loss: 0.6971 | Train Acc: 0.5092 | Test Acc: 0.4577 | [Model Saved! Best Acc: 0.4577]
Epoch  2/50 | Train Loss: 0.6939 | Train Acc: 0.5275 | Test Acc: 0.4577
Epoch  3/50 | Train Loss: 0.6942 | Train Acc: 0.5137 | Test Acc: 0.5323 | [Model Saved! Best Acc: 0.5323]
Epoch  4/50 | Train Loss: 0.6909 | Train Acc: 0.5435 | Test Acc: 0.4378
Epoch  5/50 | Train Loss: 0.6907 | Train Acc: 0.5549 | Test Acc: 0.5025
Epoch  6/50 | Train Loss: 0.6918 | Train Acc: 0.5229 | Test Acc: 0.4577
Epoch  7/50 | Train Loss: 0.6918 | Train Acc: 0.5195 | Test Acc: 0.4279
Epoch  8/50 | Train Loss: 0.6881 | Train Acc: 0.5561 | Test Acc: 0.4428
Epoch  9/50 | Train Loss: 0.6906 | Train Acc: 0.5389 | Test Acc: 0.4478
Epoch 10/50 | Train Loss: 0.6930 | Train Acc: 0.5412 | Test Acc: 0.5174
Epoch 11/50 | Train Loss: 0.6911 | Train Acc: 0.5469 | Test Acc: 0.5323
Epoch 12/50 | Train Loss: 0.6895 | Train Acc: 0.5698 | Test Acc: 0.5174
Epoch 13/50 | Train Loss: 0.6902 | Train Acc: 0.5584 | Test Acc: 0.4677
Epoch 14/50 | Train Loss: 0.6915 | Train Acc: 0.5320 | Test Acc: 0.4378
Epoch 15/50 | Train Loss: 0.6905 | Train Acc: 0.5435 | Test Acc: 0.4478
Epoch 16/50 | Train Loss: 0.6890 | Train Acc: 0.5549 | Test Acc: 0.4577
Epoch 17/50 | Train Loss: 0.6851 | Train Acc: 0.5584 | Test Acc: 0.4826
Epoch 18/50 | Train Loss: 0.6901 | Train Acc: 0.5423 | Test Acc: 0.5124
Epoch 19/50 | Train Loss: 0.6855 | Train Acc: 0.5652 | Test Acc: 0.4826
Epoch 20/50 | Train Loss: 0.6815 | Train Acc: 0.5584 | Test Acc: 0.4378
Epoch 21/50 | Train Loss: 0.6803 | Train Acc: 0.5698 | Test Acc: 0.4776
Epoch 22/50 | Train Loss: 0.6725 | Train Acc: 0.6030 | Test Acc: 0.4627
Epoch 23/50 | Train Loss: 0.6623 | Train Acc: 0.6178 | Test Acc: 0.4627
Epoch 24/50 | Train Loss: 0.6511 | Train Acc: 0.6224 | Test Acc: 0.4876
Epoch 25/50 | Train Loss: 0.6288 | Train Acc: 0.6545 | Test Acc: 0.5522 | [Model Saved! Best Acc: 0.5522]
Epoch 26/50 | Train Loss: 0.5997 | Train Acc: 0.6865 | Test Acc: 0.5075
Epoch 27/50 | Train Loss: 0.5645 | Train Acc: 0.7128 | Test Acc: 0.5721 | [Model Saved! Best Acc: 0.5721]
Epoch 28/50 | Train Loss: 0.5287 | Train Acc: 0.7334 | Test Acc: 0.6020 | [Model Saved! Best Acc: 0.6020]
Epoch 29/50 | Train Loss: 0.4786 | Train Acc: 0.7609 | Test Acc: 0.5771
Epoch 30/50 | Train Loss: 0.4628 | Train Acc: 0.7941 | Test Acc: 0.6070 | [Model Saved! Best Acc: 0.6070]
Epoch 31/50 | Train Loss: 0.4451 | Train Acc: 0.7918 | Test Acc: 0.6617 | [Model Saved! Best Acc: 0.6617]
Epoch 32/50 | Train Loss: 0.4105 | Train Acc: 0.8124 | Test Acc: 0.6567
Epoch 33/50 | Train Loss: 0.3808 | Train Acc: 0.8204 | Test Acc: 0.6915 | [Model Saved! Best Acc: 0.6915]
Epoch 34/50 | Train Loss: 0.3447 | Train Acc: 0.8490 | Test Acc: 0.6866
Epoch 35/50 | Train Loss: 0.3252 | Train Acc: 0.8547 | Test Acc: 0.6866
Epoch 36/50 | Train Loss: 0.2566 | Train Acc: 0.9005 | Test Acc: 0.7214 | [Model Saved! Best Acc: 0.7214]
Epoch 37/50 | Train Loss: 0.2747 | Train Acc: 0.8913 | Test Acc: 0.7065
Epoch 38/50 | Train Loss: 0.2285 | Train Acc: 0.9016 | Test Acc: 0.7214
Epoch 39/50 | Train Loss: 0.2243 | Train Acc: 0.9108 | Test Acc: 0.7313 | [Model Saved! Best Acc: 0.7313]
Epoch 40/50 | Train Loss: 0.2143 | Train Acc: 0.9222 | Test Acc: 0.7512 | [Model Saved! Best Acc: 0.7512]
Epoch 41/50 | Train Loss: 0.2036 | Train Acc: 0.9199 | Test Acc: 0.7463
Epoch 42/50 | Train Loss: 0.1814 | Train Acc: 0.9291 | Test Acc: 0.7463
Epoch 43/50 | Train Loss: 0.1850 | Train Acc: 0.9279 | Test Acc: 0.7363
Epoch 44/50 | Train Loss: 0.1390 | Train Acc: 0.9485 | Test Acc: 0.7413
Epoch 45/50 | Train Loss: 0.1367 | Train Acc: 0.9485 | Test Acc: 0.7463
Epoch 46/50 | Train Loss: 0.1253 | Train Acc: 0.9565 | Test Acc: 0.7463
Epoch 47/50 | Train Loss: 0.1070 | Train Acc: 0.9565 | Test Acc: 0.7662 | [Model Saved! Best Acc: 0.7662]
Epoch 48/50 | Train Loss: 0.1140 | Train Acc: 0.9531 | Test Acc: 0.7910 | [Model Saved! Best Acc: 0.7910]
Epoch 49/50 | Train Loss: 0.0986 | Train Acc: 0.9588 | Test Acc: 0.7711
Epoch 50/50 | Train Loss: 0.0975 | Train Acc: 0.9634 | Test Acc: 0.7612
======================================================================
ОБУЧЕНИЕ ЗАВЕРШЕНО. Лучшая точность: 0.7910
======================================================================
======================================================================
ЗАГРУЖАЕМ ЛУЧШИЕ ВЕСА ПЕРЕД ФИНАЛЬНОЙ ОЦЕНКОЙ
Загружены лучшие веса из tsmixer_full_GOOGL.pt
======================================================================

======================================================================
ФИНАЛЬНЫЕ РЕЗУЛЬТАТЫ КЛАССИФИКАЦИИ
======================================================================
Test Accuracy: 0.7910 (79.10%)
Baseline (majority class): 0.5423 (54.23%)
Улучшение над baseline: 24.88%

----------------------------------------------------------------------
CLASSIFICATION REPORT
----------------------------------------------------------------------
              precision    recall  f1-score   support

    Down (0)     0.7976    0.7283    0.7614        92
      Up (1)     0.7863    0.8440    0.8142       109

    accuracy                         0.7910       201
   macro avg     0.7920    0.7861    0.7878       201
weighted avg     0.7915    0.7910    0.7900       201

----------------------------------------------------------------------
CONFUSION MATRIX
----------------------------------------------------------------------

              Predicted
                0      1
Actual 0       67     25
       1       17     92

----------------------------------------------------------------------
ИНТЕРПРЕТАЦИЯ
----------------------------------------------------------------------
True Positives (правильно предсказан рост):     92
True Negatives (правильно предсказано падение): 67
False Positives (ложный сигнал на рост):        25
False Negatives (пропущенный рост):             17

======================================================================
BACKTEST ТОРГОВЫХ СТРАТЕГИЙ
======================================================================
Buy & Hold:              -13.11%
Strategy (Long only):      2.08%
Strategy (Long/Short):    14.31%
======================================================================

Sharpe Ratio (годовой):
  Buy & Hold:           -0.272
  Strategy (Long only): 0.235
  Strategy (Long/Short):0.633
======================================================================

/tmp/ipython-input-577606817.py:532: UserWarning: Data index is not sorted in ascending order. Sorting.
  bt = Backtest(test_datadf_neu_backtest, ChronosNextDayDirection, cash=1000000, commission=.002, exclusive_orders=True, finalize_trades=True)

Backtest.run:   0%|          | 0/200 [00:00<?, ?bar/s]

Start                     2024-05-24 00:00:00
End                       2025-12-31 00:00:00
Duration                    586 days 00:00:00
Exposure Time [%]                   81.094527
Equity Final [$]               1169156.670896
Equity Peak [$]                1282446.534408
Commissions [$]                 199976.891977
Return [%]                          16.915667
Buy & Hold Return [%]               80.218841
Return (Ann.) [%]                   21.644967
Volatility (Ann.) [%]               28.086629
CAGR [%]                             6.951673
Sharpe Ratio                          0.77065
Sortino Ratio                        1.334647
Calmar Ratio                         1.130719
Alpha [%]                           10.841758
Beta                                 0.075717
Max. Drawdown [%]                  -19.142654
Avg. Drawdown [%]                   -3.422818
Max. Drawdown Duration      334 days 00:00:00
Avg. Drawdown Duration       44 days 00:00:00
# Trades                                   48
Win Rate [%]                        54.166667
Best Trade [%]                       13.05526
Worst Trade [%]                     -7.636833
Avg. Trade [%]                       0.326729
Max. Trade Duration          15 days 00:00:00
dtype: object

'risk_adjusted_return = -16.22'

Финальный ROC AUC на тесте: 0.8134

5. Набор данных Test. Модель Chronos. Начало бэктестирования Strategy4 с оптимизированными гиперпараметрами на наборе Test: {'bb_period': np.float64(10.0), 'bb_std': np.float64(1.6971694262222652), 'ema_period': np.float64(18.0), 'ma_period': np.float64(32.0), 'macd_fast': np.float64(18.0), 'macd_signal': np.float64(14.0), 'macd_slow': np.float64(24.0), 'rsi_period': np.float64(16.0), 'sma': np.float64(11.0), 'stoch_d': np.float64(5.0), 'stoch_k': np.float64(16.0), 'stoch_slow': np.float64(7.0)} с использованием ML
Обрабатываем данные для модели Chronos... ->
==================================================
Выставляем параметры для модели Chronos... ->
Pretrain BaseChronosPipeline... ->
==================================================
==================================================
ChronosNextDayDirection... ->

Backtest.run:   0%|          | 0/1001 [00:00<?, ?bar/s]

======================================================================
ROC AUC (Train): 0.4831
======================================================================
Best threshold: 0.0 Sharpe: 0.04050767495079694
==================================================
ChronosStrategy... ->

/tmp/ipython-input-2513420128.py:279: UserWarning: Data index is not sorted in ascending order. Sorting.
  bt_chronos = Backtest(

Backtest.run:   0%|          | 0/329 [00:00<?, ?bar/s]

==================================================
BuyHold... ->

/tmp/ipython-input-2513420128.py:292: UserWarning: Data index is not sorted in ascending order. Sorting.
  bt_bh = Backtest(

Backtest.run:   0%|          | 0/329 [00:00<?, ?bar/s]

==================================================
TemaGoldenCrossStrategy... ->

/tmp/ipython-input-2513420128.py:323: UserWarning: Data index is not sorted in ascending order. Sorting.
  btchronos = Backtest(test_datadf_neu, TemaGoldenCrossStrategy, cash=1000000, commission=.002, exclusive_orders=True, finalize_trades=True)

Backtest.run:   0%|          | 0/201 [00:00<?, ?bar/s]

'GoldenCrossStrategy:  '

,Buy&Hold,GoldenCross
Start,2024-05-24 00:00:00,2022-01-03 00:00:00
End,2025-12-31 00:00:00,2025-12-30 00:00:00
Duration,586 days 00:00:00,1457 days 00:00:00
Exposure Time [%],99.393939,74.351297
Equity Final [$],1785431.431985,715553.653941
Equity Peak [$],1842467.174228,1129263.675729
Commissions [$],5573.769736,450120.863821
Return [%],78.543143,-28.444635
Buy & Hold Return [%],80.218841,118.096503
Return (Ann.) [%],55.68266,-8.073029
Volatility (Ann.) [%],45.661374,23.522376
CAGR [%],28.309306,-5.624517
Sharpe Ratio,1.21947,-0.343206
Sortino Ratio,3.025996,-0.470431
Calmar Ratio,2.515445,-0.145453
Alpha [%],-1.638164,-64.943101
Beta,0.999532,0.309056
Max. Drawdown [%],-22.136308,-55.502476
Avg. Drawdown [%],-3.515303,-16.018059
Max. Drawdown Duration,199 days 00:00:00,1049 days 00:00:00
Avg. Drawdown Duration,20 days 00:00:00,254 days 00:00:00
# Trades,1,149
Win Rate [%],100.0,44.966443
Best Trade [%],78.705289,16.376323
Worst Trade [%],78.705289,-10.096114
Avg. Trade [%],78.705289,-0.224971
Max. Trade Duration,581 days 00:00:00,42 days 00:00:00
Avg. Trade Duration,581 days 00:00:00,6 days 00:00:00
Profit Factor,NaN,0.882633
Expectancy [%],78.705289,-0.160607
SQN,NaN,-0.862826
Kelly Criterion,NaN,-0.098319
_strategy,BuyHold,ChronosNextDayDirection
_equity_curve,Equity DrawdownPct Drawdown...,Equity DrawdownPct Drawdo...
_trades,Size EntryBar ExitBar EntryPrice ExitP...,Size EntryBar ExitBar EntryPrice Exi...

'risk_adjusted_return = -2.40'

6. Набор данных Valid. Начало бэктестирования Strategy4 с оптимизированными гиперпараметрами на объединенном наборе Train и Test: {'bb_period': np.float64(10.0), 'bb_std': np.float64(1.6971694262222652), 'ema_period': np.float64(18.0), 'ma_period': np.float64(32.0), 'macd_fast': np.float64(18.0), 'macd_signal': np.float64(14.0), 'macd_slow': np.float64(24.0), 'rsi_period': np.float64(16.0), 'sma': np.float64(11.0), 'stoch_d': np.float64(5.0), 'stoch_k': np.float64(16.0), 'stoch_slow': np.float64(7.0)}
======================================================================
РАСПРЕДЕЛЕНИЕ КЛАССОВ
======================================================================
target
0    470
1    532
Name: count, dtype: int64

Баланс классов (доля класса 1): 0.531
Всего примеров: 1002
======================================================================
Размер окон признаков: (874, 128, 24)
Размер таргетов: (874,)
Размер индексов: (874,)
======================================================================
РАЗМЕРЫ ВЫБОРОК
======================================================================
Train: X=(874, 128, 24), y=(874,)
Test:  X=(459, 128, 24), y=(459,)

Распределение классов в test:
  Класс 0 (падение): 310 (67.5%)
  Класс 1 (рост):    149 (32.5%)
======================================================================
Train batches: 14
Test batches:  8

Пример батча:
  X: torch.Size([64, 128, 24])  (batch, lookback, num_features)
  y: torch.Size([64])  (batch,)

Пример батча test:
  X: torch.Size([64, 128, 24])  (batch, lookback, num_features)
  y: torch.Size([64])  (batch,)
======================================================================
Load tsmixer_full_GOOGL.pt ...
Модель tsmixer_full_GOOGL.pt загружена.
Загружены лучшие веса из tsmixer_full_GOOGL.pt
======================================================================
ИНФОРМАЦИЯ О МОДЕЛИ
======================================================================
Всего параметров:      305,113
Обучаемых параметров:  305,113
Устройство:            cpu
======================================================================
Веса классов для Loss: 0 (Down): 1.0660, 1 (Up): 0.9417
✓ Optimizer, loss function и evaluation function настроены
======================================================================
НАЧАЛО ОБУЧЕНИЯ
======================================================================
======================================================================
ОБУЧЕНИЕ ЗАВЕРШЕНО. Лучшая точность: 0.0000
======================================================================
======================================================================
ЗАГРУЖАЕМ ЛУЧШИЕ ВЕСА ПЕРЕД ФИНАЛЬНОЙ ОЦЕНКОЙ
Загружены лучшие веса из tsmixer_full_GOOGL.pt
======================================================================

======================================================================
ФИНАЛЬНЫЕ РЕЗУЛЬТАТЫ КЛАССИФИКАЦИИ
======================================================================
Test Accuracy: 0.4379 (43.79%)
Baseline (majority class): 0.6754 (67.54%)
Улучшение над baseline: -23.75%

----------------------------------------------------------------------
CLASSIFICATION REPORT
----------------------------------------------------------------------
              precision    recall  f1-score   support

    Down (0)     0.6940    0.3000    0.4189       310
      Up (1)     0.3323    0.7248    0.4557       149

    accuracy                         0.4379       459
   macro avg     0.5132    0.5124    0.4373       459
weighted avg     0.5766    0.4379    0.4309       459

----------------------------------------------------------------------
CONFUSION MATRIX
----------------------------------------------------------------------

              Predicted
                0      1
Actual 0       93    217
       1       41    108

----------------------------------------------------------------------
ИНТЕРПРЕТАЦИЯ
----------------------------------------------------------------------
True Positives (правильно предсказан рост):     108
True Negatives (правильно предсказано падение): 93
False Positives (ложный сигнал на рост):        217
False Negatives (пропущенный рост):             41

======================================================================
BACKTEST ТОРГОВЫХ СТРАТЕГИЙ
======================================================================
Buy & Hold:               40.84%
Strategy (Long only):     68.94%
Strategy (Long/Short):    90.95%
======================================================================

Sharpe Ratio (годовой):
  Buy & Hold:           0.732
  Strategy (Long only): 1.172
  Strategy (Long/Short):1.236
======================================================================

/tmp/ipython-input-577606817.py:532: UserWarning: Data index is not sorted in ascending order. Sorting.
  bt = Backtest(test_datadf_neu_backtest, ChronosNextDayDirection, cash=1000000, commission=.002, exclusive_orders=True, finalize_trades=True)

Backtest.run:   0%|          | 0/458 [00:00<?, ?bar/s]

Start                     2025-03-17 00:00:00
End                       2025-12-31 00:00:00
Duration                    289 days 00:00:00
Exposure Time [%]                   88.453159
Equity Final [$]               1096328.706872
Equity Peak [$]                1256323.901559
Commissions [$]                 354786.339206
Return [%]                           9.632871
Buy & Hold Return [%]                91.04289
Return (Ann.) [%]                   12.221228
Volatility (Ann.) [%]                34.04226
CAGR [%]                             8.349587
Sharpe Ratio                         0.359002
Sortino Ratio                        0.673741
Calmar Ratio                         0.718207
Alpha [%]                          -59.921065
Beta                                 0.763969
Max. Drawdown [%]                  -17.016292
Avg. Drawdown [%]                   -7.742143
Max. Drawdown Duration      162 days 00:00:00
Avg. Drawdown Duration       31 days 00:00:00
# Trades                                   84
Win Rate [%]                        33.333333
Best Trade [%]                      11.782217
Worst Trade [%]                     -5.232074
Avg. Trade [%]                       0.109725
Max. Trade Duration          13 days 00:00:00
dtype: object

'risk_adjusted_return = -1.40'

Финальный ROC AUC на тесте: 0.5573
====================================================================================================

/usr/local/lib/python3.12/dist-packages/pandas/io/formats/style.py:3811: RuntimeWarning: invalid value encountered in scalar multiply
  norm = _matplotlib.colors.Normalize(smin - (rng * low), smax + (rng * high))

Анализ инструмента: NVDA
====================================================================================================

'\nЗагрузка данных с Yahoo Finance NVDA'

[*********************100%***********************]  1 of 1 completed

Размер данных: 1003 строк

Периоды наборов данных:
Train: 2022-01-03 - 2024-05-23
Test: 2024-05-24 - 2025-03-14
Valid: 2025-03-17 - 2025-12-31
TestMl: 2024-05-24 - 2025-03-14

1. Набор данных Train. Начало бэктестирования Strategy4 с гиперпараметрами по умолчанию: {'bb_period': 20, 'bb_std': 2.0, 'rsi_period': 14, 'sma': 10, 'ema_period': 4, 'ma_period': 10, 'macd_fast': 12, 'macd_slow': 26, 'macd_signal': 9, 'stoch_k': 14, 'stoch_d': 3, 'stoch_slow': 3}

Начало оптимизации гиперпараметров для Strategy4 на Train...
100%|██████████| 50/50 [00:02<00:00, 23.70trial/s, best loss: -0.0960917436003913]
Оптимальные гиперпараметры для Strategy4 на Train: {'bb_period': np.float64(12.0), 'bb_std': np.float64(2.9094720478074994), 'ema_period': np.float64(21.0), 'ma_period': np.float64(32.0), 'macd_fast': np.float64(19.0), 'macd_signal': np.float64(10.0), 'macd_slow': np.float64(38.0), 'rsi_period': np.float64(8.0), 'sma': np.float64(30.0), 'stoch_d': np.float64(4.0), 'stoch_k': np.float64(16.0), 'stoch_slow': np.float64(7.0)}

2. Набор данных Test. Начало бэктестирования Strategy4 с оптимизированными гиперпараметрами на наборе Train: {'bb_period': np.float64(12.0), 'bb_std': np.float64(2.9094720478074994), 'ema_period': np.float64(21.0), 'ma_period': np.float64(32.0), 'macd_fast': np.float64(19.0), 'macd_signal': np.float64(10.0), 'macd_slow': np.float64(38.0), 'rsi_period': np.float64(8.0), 'sma': np.float64(30.0), 'stoch_d': np.float64(4.0), 'stoch_k': np.float64(16.0), 'stoch_slow': np.float64(7.0)}

Объединенный набор данных Train и Test: 2022-01-03 - 2025-03-14

Начало оптимизации гиперпараметров для Strategy4 на объединенном наборе Train и Test...
100%|██████████| 50/50 [00:02<00:00, 19.94trial/s, best loss: -0.21603603808773097]
Оптимальные гиперпараметры для Strategy4 на объединенном наборе Train и Test: {'bb_period': np.float64(26.0), 'bb_std': np.float64(2.237224906917673), 'ema_period': np.float64(47.0), 'ma_period': np.float64(28.0), 'macd_fast': np.float64(14.0), 'macd_signal': np.float64(11.0), 'macd_slow': np.float64(39.0), 'rsi_period': np.float64(9.0), 'sma': np.float64(28.0), 'stoch_d': np.float64(6.0), 'stoch_k': np.float64(12.0), 'stoch_slow': np.float64(7.0)}

3. Набор данных Test.  Начало бэктестирования Strategy4 с оптимизированными гиперпараметрами на наборе Test: {'bb_period': np.float64(26.0), 'bb_std': np.float64(2.237224906917673), 'ema_period': np.float64(47.0), 'ma_period': np.float64(28.0), 'macd_fast': np.float64(14.0), 'macd_signal': np.float64(11.0), 'macd_slow': np.float64(39.0), 'rsi_period': np.float64(9.0), 'sma': np.float64(28.0), 'stoch_d': np.float64(6.0), 'stoch_k': np.float64(12.0), 'stoch_slow': np.float64(7.0)} с использованием ML

'Создаем объект класса Backtest'

'Запускаем бэктест'

Backtest.run:   0%|          | 0/60 [00:00<?, ?bar/s]

'Разделяем признаки и метки'

'RobustScaler'

Feature Importance:
 Slowd              11.568301
Linearreg_angle    10.409495
Mfi                 7.793759
Rsi                 6.994356
Adosc               6.315467
Atr14               6.213002
Cci                 6.048251
Slowk               5.463220
Macd                5.349060
Adx                 5.103767
Bb_lower            5.041945
Bb_upper            4.547342
Ma_period           4.469985
Sma                 4.465618
Obv                 3.878811
Bb_middle           2.989013
Engulfing           1.614732
Morningstar         0.891140
Doji                0.731832
Hammer              0.108868
Sar                 0.002035
dtype: float64

'Повторяем все тоже самое с данными для теста'

'Для предсказания используем данные в столбацах ниже'

'Выводим предсказание'

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0
 0]
0.2894736842105263
[[ 9  1]
 [26  2]]
              precision    recall  f1-score   support

           0       0.26      0.90      0.40        10
           1       0.67      0.07      0.13        28

    accuracy                           0.29        38
   macro avg       0.46      0.49      0.26        38
weighted avg       0.56      0.29      0.20        38

Backtest.run:   0%|          | 0/37 [00:00<?, ?bar/s]

Start                     2024-08-01 00:00:00
End                       2025-03-14 00:00:00
Duration                    225 days 00:00:00
Exposure Time [%]                    5.263158
Equity Final [$]                945714.293277
Equity Peak [$]                     1000000.0
Commissions [$]                    4091.95054
Return [%]                          -5.428571
Buy & Hold Return [%]               11.436668
Return (Ann.) [%]                  -30.936241
Volatility (Ann.) [%]                8.173947
CAGR [%]                            -6.059872
Sharpe Ratio                        -3.784737
Sortino Ratio                       -2.610216
Calmar Ratio                        -5.698782
Alpha [%]                           -5.450022
Beta                                 0.001876
Max. Drawdown [%]                   -5.428571
Avg. Drawdown [%]                   -5.428571
Max. Drawdown Duration       36 days 00:00:00
Avg. Drawdown Duration       36 days 00:00:00
# Trades                                    1
Win Rate [%]                              0.0
Best Trade [%]                      -5.440045
Worst Trade [%]                     -5.440045
Avg. Trade [%]                      -5.440045
Max. Trade Duration          12 days 00:00:00
dtype: object

'Выводим график :'

'Выводим Buy&Hold и GoldenCross :'

                                   Buy&Hold          GoldenCross
Start                   2022-03-10 00:00:00  2024-08-01 00:00:00
End                     2025-12-23 00:00:00  2025-03-14 00:00:00
Duration                 1384 days 00:00:00    225 days 00:00:00
Exposure Time [%]                 96.721311             5.263158
Equity Final [$]              601832.934334        945714.293277
Equity Peak [$]              1402935.767213            1000000.0
Commissions [$]                58873.153316           4091.95054
Return [%]                       -39.816707            -5.428571
Buy & Hold Return [%]            736.544308            11.436668
Return (Ann.) [%]                -87.726099           -30.936241
Volatility (Ann.) [%]             22.664806             8.173947
CAGR [%]                          -8.831087            -6.059872
Sharpe Ratio                      -3.870587            -3.784737
Sortino Ratio                     -0.878667            -2.610216
Calmar Ratio                      -1.440233            -5.698782
Alpha [%]                         94.334894            -5.450022
Beta                              -0.182136             0.001876
Max. Drawdown [%]                -60.911064            -5.428571
Avg. Drawdown [%]                -22.346779            -5.428571
Max. Drawdown Duration    600 days 00:00:00     36 days 00:00:00
Avg. Drawdown Duration    214 days 00:00:00     36 days 00:00:00
# Trades                                 20                    1
Win Rate [%]                           35.0                  0.0
Best Trade [%]                    27.309212            -5.440045
Worst Trade [%]                  -32.063659            -5.440045
Avg. Trade [%]                    -2.667289            -5.440045
Max. Trade Duration       167 days 00:00:00     12 days 00:00:00

risk_adjusted_return = -65.74
ROC AUC Score: 0.4750
Эквивалентна случайному угадыванию

4. Набор данных Test. Модель TSMixer. Начало бэктестирования Strategy4 с оптимизированными гиперпараметрами на наборе Test: {'bb_period': np.float64(26.0), 'bb_std': np.float64(2.237224906917673), 'ema_period': np.float64(47.0), 'ma_period': np.float64(28.0), 'macd_fast': np.float64(14.0), 'macd_signal': np.float64(11.0), 'macd_slow': np.float64(39.0), 'rsi_period': np.float64(9.0), 'sma': np.float64(28.0), 'stoch_d': np.float64(6.0), 'stoch_k': np.float64(12.0), 'stoch_slow': np.float64(7.0)} с использованием ML
======================================================================
РАСПРЕДЕЛЕНИЕ КЛАССОВ
======================================================================
target
0    465
1    537
Name: count, dtype: int64

Баланс классов (доля класса 1): 0.536
Всего примеров: 1002
======================================================================
Размер окон признаков: (874, 128, 24)
Размер таргетов: (874,)
Размер индексов: (874,)
======================================================================
РАЗМЕРЫ ВЫБОРОК
======================================================================
Train: X=(874, 128, 24), y=(874,)
Test:  X=(201, 128, 24), y=(201,)

Распределение классов в test:
  Класс 0 (падение): 95 (47.3%)
  Класс 1 (рост):    106 (52.7%)
======================================================================
Train batches: 14
Test batches:  4

Пример батча:
  X: torch.Size([64, 128, 24])  (batch, lookback, num_features)
  y: torch.Size([64])  (batch,)

Пример батча test:
  X: torch.Size([64, 128, 24])  (batch, lookback, num_features)
  y: torch.Size([64])  (batch,)
======================================================================
Загружены лучшие веса из tsmixer_full_NVDA.pt
======================================================================
ИНФОРМАЦИЯ О МОДЕЛИ
======================================================================
Всего параметров:      305,113
Обучаемых параметров:  305,113
Устройство:            cpu
======================================================================
Установлен новый Optimizer: AdamW с weight decay для регуляризации
Веса классов для Loss: 0 (Down): 1.0774, 1 (Up): 0.9330
✓ Optimizer, loss function и evaluation function настроены
======================================================================
НАЧАЛО ОБУЧЕНИЯ
======================================================================
Epoch  1/50 | Train Loss: 0.6931 | Train Acc: 0.5286 | Test Acc: 0.4726 | [Model Saved! Best Acc: 0.4726]
Epoch  2/50 | Train Loss: 0.6915 | Train Acc: 0.5389 | Test Acc: 0.4726
Epoch  3/50 | Train Loss: 0.6924 | Train Acc: 0.5435 | Test Acc: 0.4726
Epoch  4/50 | Train Loss: 0.6916 | Train Acc: 0.5320 | Test Acc: 0.4726
Epoch  5/50 | Train Loss: 0.6915 | Train Acc: 0.5309 | Test Acc: 0.4726
Epoch  6/50 | Train Loss: 0.6903 | Train Acc: 0.5538 | Test Acc: 0.4726
Epoch  7/50 | Train Loss: 0.6920 | Train Acc: 0.5526 | Test Acc: 0.4726
Epoch  8/50 | Train Loss: 0.6925 | Train Acc: 0.5263 | Test Acc: 0.4726
Epoch  9/50 | Train Loss: 0.6913 | Train Acc: 0.5183 | Test Acc: 0.4726
Epoch 10/50 | Train Loss: 0.6900 | Train Acc: 0.5343 | Test Acc: 0.4726
Epoch 11/50 | Train Loss: 0.6921 | Train Acc: 0.5195 | Test Acc: 0.4726
Epoch 12/50 | Train Loss: 0.6905 | Train Acc: 0.5286 | Test Acc: 0.4726
Epoch 13/50 | Train Loss: 0.6891 | Train Acc: 0.5217 | Test Acc: 0.4726
Epoch 14/50 | Train Loss: 0.6874 | Train Acc: 0.5572 | Test Acc: 0.4726
Epoch 15/50 | Train Loss: 0.6869 | Train Acc: 0.5458 | Test Acc: 0.4726
Epoch 16/50 | Train Loss: 0.6874 | Train Acc: 0.5595 | Test Acc: 0.4726
Epoch 17/50 | Train Loss: 0.6848 | Train Acc: 0.5549 | Test Acc: 0.4726
Epoch 18/50 | Train Loss: 0.6823 | Train Acc: 0.5870 | Test Acc: 0.4726
Epoch 19/50 | Train Loss: 0.6813 | Train Acc: 0.5732 | Test Acc: 0.4726
Epoch 20/50 | Train Loss: 0.6800 | Train Acc: 0.5492 | Test Acc: 0.4726
Epoch 21/50 | Train Loss: 0.6785 | Train Acc: 0.5698 | Test Acc: 0.4726
Epoch 22/50 | Train Loss: 0.6739 | Train Acc: 0.5904 | Test Acc: 0.4726
Epoch 23/50 | Train Loss: 0.6698 | Train Acc: 0.5732 | Test Acc: 0.4726
Epoch 24/50 | Train Loss: 0.6600 | Train Acc: 0.5938 | Test Acc: 0.4726
Epoch 25/50 | Train Loss: 0.6504 | Train Acc: 0.6339 | Test Acc: 0.4726
Epoch 26/50 | Train Loss: 0.6352 | Train Acc: 0.6396 | Test Acc: 0.4726
Epoch 27/50 | Train Loss: 0.6240 | Train Acc: 0.6670 | Test Acc: 0.4776 | [Model Saved! Best Acc: 0.4776]
Epoch 28/50 | Train Loss: 0.6076 | Train Acc: 0.6568 | Test Acc: 0.4776
Epoch 29/50 | Train Loss: 0.5895 | Train Acc: 0.6648 | Test Acc: 0.4776
Epoch 30/50 | Train Loss: 0.5740 | Train Acc: 0.6945 | Test Acc: 0.5124 | [Model Saved! Best Acc: 0.5124]
Epoch 31/50 | Train Loss: 0.5465 | Train Acc: 0.7185 | Test Acc: 0.5075
Epoch 32/50 | Train Loss: 0.5250 | Train Acc: 0.7174 | Test Acc: 0.5224 | [Model Saved! Best Acc: 0.5224]
Epoch 33/50 | Train Loss: 0.5030 | Train Acc: 0.7529 | Test Acc: 0.5821 | [Model Saved! Best Acc: 0.5821]
Epoch 34/50 | Train Loss: 0.5062 | Train Acc: 0.7494 | Test Acc: 0.5373
Epoch 35/50 | Train Loss: 0.4790 | Train Acc: 0.7700 | Test Acc: 0.5274
Epoch 36/50 | Train Loss: 0.4673 | Train Acc: 0.7815 | Test Acc: 0.5821
Epoch 37/50 | Train Loss: 0.4431 | Train Acc: 0.7941 | Test Acc: 0.5970 | [Model Saved! Best Acc: 0.5970]
Epoch 38/50 | Train Loss: 0.4032 | Train Acc: 0.8112 | Test Acc: 0.5970
Epoch 39/50 | Train Loss: 0.3808 | Train Acc: 0.8112 | Test Acc: 0.6119 | [Model Saved! Best Acc: 0.6119]
Epoch 40/50 | Train Loss: 0.3662 | Train Acc: 0.8295 | Test Acc: 0.6517 | [Model Saved! Best Acc: 0.6517]
Epoch 41/50 | Train Loss: 0.3760 | Train Acc: 0.8261 | Test Acc: 0.6269
Epoch 42/50 | Train Loss: 0.3451 | Train Acc: 0.8432 | Test Acc: 0.6517
Epoch 43/50 | Train Loss: 0.3258 | Train Acc: 0.8558 | Test Acc: 0.6468
Epoch 44/50 | Train Loss: 0.3092 | Train Acc: 0.8753 | Test Acc: 0.6766 | [Model Saved! Best Acc: 0.6766]
Epoch 45/50 | Train Loss: 0.2936 | Train Acc: 0.8684 | Test Acc: 0.6716
Epoch 46/50 | Train Loss: 0.2582 | Train Acc: 0.8936 | Test Acc: 0.6716
Epoch 47/50 | Train Loss: 0.2694 | Train Acc: 0.8856 | Test Acc: 0.6617
Epoch 48/50 | Train Loss: 0.2566 | Train Acc: 0.8867 | Test Acc: 0.6468
Epoch 49/50 | Train Loss: 0.2380 | Train Acc: 0.8959 | Test Acc: 0.6617
Epoch 50/50 | Train Loss: 0.2146 | Train Acc: 0.9073 | Test Acc: 0.6866 | [Model Saved! Best Acc: 0.6866]
======================================================================
ОБУЧЕНИЕ ЗАВЕРШЕНО. Лучшая точность: 0.6866
======================================================================
======================================================================
ЗАГРУЖАЕМ ЛУЧШИЕ ВЕСА ПЕРЕД ФИНАЛЬНОЙ ОЦЕНКОЙ
Загружены лучшие веса из tsmixer_full_NVDA.pt
======================================================================

======================================================================
ФИНАЛЬНЫЕ РЕЗУЛЬТАТЫ КЛАССИФИКАЦИИ
======================================================================
Test Accuracy: 0.6866 (68.66%)
Baseline (majority class): 0.5274 (52.74%)
Улучшение над baseline: 15.92%

----------------------------------------------------------------------
CLASSIFICATION REPORT
----------------------------------------------------------------------
              precision    recall  f1-score   support

    Down (0)     0.6311    0.8105    0.7097        95
      Up (1)     0.7722    0.5755    0.6595       106

    accuracy                         0.6866       201
   macro avg     0.7016    0.6930    0.6846       201
weighted avg     0.7055    0.6866    0.6832       201

----------------------------------------------------------------------
CONFUSION MATRIX
----------------------------------------------------------------------

              Predicted
                0      1
Actual 0       77     18
       1       45     61

----------------------------------------------------------------------
ИНТЕРПРЕТАЦИЯ
----------------------------------------------------------------------
True Positives (правильно предсказан рост):     61
True Negatives (правильно предсказано падение): 77
False Positives (ложный сигнал на рост):        18
False Negatives (пропущенный рост):             45

======================================================================
BACKTEST ТОРГОВЫХ СТРАТЕГИЙ
======================================================================
Buy & Hold:               70.32%
Strategy (Long only):      1.71%
Strategy (Long/Short):   -48.85%
======================================================================

Sharpe Ratio (годовой):
  Buy & Hold:           1.471
  Strategy (Long only): 0.228
  Strategy (Long/Short):-1.209
======================================================================

/tmp/ipython-input-577606817.py:532: UserWarning: Data index is not sorted in ascending order. Sorting.
  bt = Backtest(test_datadf_neu_backtest, ChronosNextDayDirection, cash=1000000, commission=.002, exclusive_orders=True, finalize_trades=True)

Backtest.run:   0%|          | 0/200 [00:00<?, ?bar/s]

Start                     2024-05-24 00:00:00
End                       2025-12-31 00:00:00
Duration                    586 days 00:00:00
Exposure Time [%]                   58.706468
Equity Final [$]               1940129.201151
Equity Peak [$]                1947904.604571
Commissions [$]                 190856.598641
Return [%]                           94.01292
Buy & Hold Return [%]               75.257724
Return (Ann.) [%]                  129.542079
Volatility (Ann.) [%]                78.82425
CAGR [%]                            32.977145
Sharpe Ratio                         1.643429
Sortino Ratio                        5.783003
Calmar Ratio                          4.44497
Alpha [%]                           81.720889
Beta                                 0.163332
Max. Drawdown [%]                  -29.143521
Avg. Drawdown [%]                   -3.709141
Max. Drawdown Duration      126 days 00:00:00
Avg. Drawdown Duration       18 days 00:00:00
# Trades                                   42
Win Rate [%]                        66.666667
Best Trade [%]                      13.121898
Worst Trade [%]                    -18.821889
Avg. Trade [%]                       1.593486
Max. Trade Duration           7 days 00:00:00
dtype: object

'risk_adjusted_return = -2984.70'

Финальный ROC AUC на тесте: 0.7384

5. Набор данных Test. Модель Chronos. Начало бэктестирования Strategy4 с оптимизированными гиперпараметрами на наборе Test: {'bb_period': np.float64(26.0), 'bb_std': np.float64(2.237224906917673), 'ema_period': np.float64(47.0), 'ma_period': np.float64(28.0), 'macd_fast': np.float64(14.0), 'macd_signal': np.float64(11.0), 'macd_slow': np.float64(39.0), 'rsi_period': np.float64(9.0), 'sma': np.float64(28.0), 'stoch_d': np.float64(6.0), 'stoch_k': np.float64(12.0), 'stoch_slow': np.float64(7.0)} с использованием ML
Обрабатываем данные для модели Chronos... ->
==================================================
Выставляем параметры для модели Chronos... ->
Pretrain BaseChronosPipeline... ->
==================================================
==================================================
ChronosNextDayDirection... ->

Backtest.run:   0%|          | 0/1001 [00:00<?, ?bar/s]

======================================================================
ROC AUC (Train): 0.4922
======================================================================
Best threshold: 0.0035 Sharpe: 0.04298748421291807
==================================================
ChronosStrategy... ->

/tmp/ipython-input-2513420128.py:279: UserWarning: Data index is not sorted in ascending order. Sorting.
  bt_chronos = Backtest(

Backtest.run:   0%|          | 0/329 [00:00<?, ?bar/s]

==================================================
BuyHold... ->

/tmp/ipython-input-2513420128.py:292: UserWarning: Data index is not sorted in ascending order. Sorting.
  bt_bh = Backtest(

Backtest.run:   0%|          | 0/329 [00:00<?, ?bar/s]

==================================================
TemaGoldenCrossStrategy... ->

/tmp/ipython-input-2513420128.py:323: UserWarning: Data index is not sorted in ascending order. Sorting.
  btchronos = Backtest(test_datadf_neu, TemaGoldenCrossStrategy, cash=1000000, commission=.002, exclusive_orders=True, finalize_trades=True)

Backtest.run:   0%|          | 0/201 [00:00<?, ?bar/s]

'GoldenCrossStrategy:  '

,Buy&Hold,GoldenCross
Start,2024-05-24 00:00:00,2022-01-03 00:00:00
End,2025-12-31 00:00:00,2025-12-30 00:00:00
Duration,586 days 00:00:00,1457 days 00:00:00
Exposure Time [%],99.393939,81.237525
Equity Final [$],1640744.713279,1416220.97029
Equity Peak [$],1814868.67674,1924392.155579
Commissions [$],5283.845208,725239.256752
Return [%],64.074471,41.622097
Buy & Hold Return [%],75.257724,523.828156
Return (Ann.) [%],45.953037,9.146295
Volatility (Ann.) [%],87.347876,50.081895
CAGR [%],23.729989,6.203625
Sharpe Ratio,0.526092,0.182627
Sortino Ratio,1.303276,0.321072
Calmar Ratio,1.617683,0.195764
Alpha [%],-10.315331,-103.004674
Beta,0.988467,0.276096
Max. Drawdown [%],-28.406704,-46.721043
Avg. Drawdown [%],-6.319331,-10.94816
Max. Drawdown Duration,175 days 00:00:00,645 days 00:00:00
Avg. Drawdown Duration,26 days 00:00:00,66 days 00:00:00
# Trades,1,129
Win Rate [%],100.0,50.387597
Best Trade [%],64.206285,30.910488
Worst Trade [%],64.206285,-30.077606
Avg. Trade [%],64.206285,0.270093
Max. Trade Duration,581 days 00:00:00,54 days 00:00:00
Avg. Trade Duration,581 days 00:00:00,8 days 00:00:00
Profit Factor,NaN,1.256842
Expectancy [%],64.206285,0.55294
SQN,NaN,0.383607
Kelly Criterion,NaN,0.048371
_strategy,BuyHold,ChronosNextDayDirection
_equity_curve,Equity DrawdownPct Drawdown...,Equity DrawdownPct Drawdown...
_trades,Size EntryBar ExitBar EntryPrice ExitP...,Size EntryBar ExitBar EntryPrice Ex...

'risk_adjusted_return = -2.22'

6. Набор данных Valid. Начало бэктестирования Strategy4 с оптимизированными гиперпараметрами на объединенном наборе Train и Test: {'bb_period': np.float64(26.0), 'bb_std': np.float64(2.237224906917673), 'ema_period': np.float64(47.0), 'ma_period': np.float64(28.0), 'macd_fast': np.float64(14.0), 'macd_signal': np.float64(11.0), 'macd_slow': np.float64(39.0), 'rsi_period': np.float64(9.0), 'sma': np.float64(28.0), 'stoch_d': np.float64(6.0), 'stoch_k': np.float64(12.0), 'stoch_slow': np.float64(7.0)}
======================================================================
РАСПРЕДЕЛЕНИЕ КЛАССОВ
======================================================================
target
0    465
1    537
Name: count, dtype: int64

Баланс классов (доля класса 1): 0.536
Всего примеров: 1002
======================================================================
Размер окон признаков: (874, 128, 24)
Размер таргетов: (874,)
Размер индексов: (874,)
======================================================================
РАЗМЕРЫ ВЫБОРОК
======================================================================
Train: X=(874, 128, 24), y=(874,)
Test:  X=(459, 128, 24), y=(459,)

Распределение классов в test:
  Класс 0 (падение): 321 (69.9%)
  Класс 1 (рост):    138 (30.1%)
======================================================================
Train batches: 14
Test batches:  8

Пример батча:
  X: torch.Size([64, 128, 24])  (batch, lookback, num_features)
  y: torch.Size([64])  (batch,)

Пример батча test:
  X: torch.Size([64, 128, 24])  (batch, lookback, num_features)
  y: torch.Size([64])  (batch,)
======================================================================
Load tsmixer_full_NVDA.pt ...
Модель tsmixer_full_NVDA.pt загружена.
Загружены лучшие веса из tsmixer_full_NVDA.pt
======================================================================
ИНФОРМАЦИЯ О МОДЕЛИ
======================================================================
Всего параметров:      305,113
Обучаемых параметров:  305,113
Устройство:            cpu
======================================================================
Веса классов для Loss: 0 (Down): 1.0774, 1 (Up): 0.9330
✓ Optimizer, loss function и evaluation function настроены
======================================================================
НАЧАЛО ОБУЧЕНИЯ
======================================================================
======================================================================
ОБУЧЕНИЕ ЗАВЕРШЕНО. Лучшая точность: 0.0000
======================================================================
======================================================================
ЗАГРУЖАЕМ ЛУЧШИЕ ВЕСА ПЕРЕД ФИНАЛЬНОЙ ОЦЕНКОЙ
Загружены лучшие веса из tsmixer_full_NVDA.pt
======================================================================

======================================================================
ФИНАЛЬНЫЕ РЕЗУЛЬТАТЫ КЛАССИФИКАЦИИ
======================================================================
Test Accuracy: 0.5599 (55.99%)
Baseline (majority class): 0.6993 (69.93%)
Улучшение над baseline: -13.94%

----------------------------------------------------------------------
CLASSIFICATION REPORT
----------------------------------------------------------------------
              precision    recall  f1-score   support

    Down (0)     0.7017    0.6449    0.6721       321
      Up (1)     0.3049    0.3623    0.3311       138

    accuracy                         0.5599       459
   macro avg     0.5033    0.5036    0.5016       459
weighted avg     0.5824    0.5599    0.5696       459

----------------------------------------------------------------------
CONFUSION MATRIX
----------------------------------------------------------------------

              Predicted
                0      1
Actual 0      207    114
       1       88     50

----------------------------------------------------------------------
ИНТЕРПРЕТАЦИЯ
----------------------------------------------------------------------
True Positives (правильно предсказан рост):     50
True Negatives (правильно предсказано падение): 207
False Positives (ложный сигнал на рост):        114
False Negatives (пропущенный рост):             88

======================================================================
BACKTEST ТОРГОВЫХ СТРАТЕГИЙ
======================================================================
Buy & Hold:              482.37%
Strategy (Long only):    170.84%
Strategy (Long/Short):    -2.93%
======================================================================

Sharpe Ratio (годовой):
  Buy & Hold:           2.107
  Strategy (Long only): 1.667
  Strategy (Long/Short):0.227
======================================================================

/tmp/ipython-input-577606817.py:532: UserWarning: Data index is not sorted in ascending order. Sorting.
  bt = Backtest(test_datadf_neu_backtest, ChronosNextDayDirection, cash=1000000, commission=.002, exclusive_orders=True, finalize_trades=True)

Backtest.run:   0%|          | 0/458 [00:00<?, ?bar/s]

Start                     2025-03-17 00:00:00
End                       2025-12-31 00:00:00
Duration                    289 days 00:00:00
Exposure Time [%]                   51.633987
Equity Final [$]                 882936.34825
Equity Peak [$]                1159976.954087
Commissions [$]                 294796.315094
Return [%]                         -11.706365
Buy & Hold Return [%]               56.056096
Return (Ann.) [%]                  -14.451975
Volatility (Ann.) [%]               31.474899
CAGR [%]                           -10.287713
Sharpe Ratio                        -0.459159
Sortino Ratio                       -0.623483
Calmar Ratio                        -0.473718
Alpha [%]                          -42.929106
Beta                                 0.556991
Max. Drawdown [%]                  -30.507524
Avg. Drawdown [%]                   -9.225853
Max. Drawdown Duration      107 days 00:00:00
Avg. Drawdown Duration       40 days 00:00:00
# Trades                                   74
Win Rate [%]                        36.486486
Best Trade [%]                      19.044332
Worst Trade [%]                    -15.874739
Avg. Trade [%]                      -0.143809
Max. Trade Duration           8 days 00:00:00
dtype: object

'risk_adjusted_return = -1.33'

Финальный ROC AUC на тесте: 0.4962
====================================================================================================

/usr/local/lib/python3.12/dist-packages/pandas/io/formats/style.py:3811: RuntimeWarning: invalid value encountered in scalar multiply
  norm = _matplotlib.colors.Normalize(smin - (rng * low), smax + (rng * high))

Анализ инструмента: BTC-USD
====================================================================================================

'\nЗагрузка данных с Yahoo Finance BTC-USD'

[*********************100%***********************]  1 of 1 completed

Размер данных: 1461 строк

Периоды наборов данных:
Train: 2022-01-01 - 2024-05-25
Test: 2024-05-26 - 2025-03-13
Valid: 2025-03-14 - 2025-12-31
TestMl: 2024-05-26 - 2025-03-13

1. Набор данных Train. Начало бэктестирования Strategy4 с гиперпараметрами по умолчанию: {'bb_period': 20, 'bb_std': 2.0, 'rsi_period': 14, 'sma': 10, 'ema_period': 4, 'ma_period': 10, 'macd_fast': 12, 'macd_slow': 26, 'macd_signal': 9, 'stoch_k': 14, 'stoch_d': 3, 'stoch_slow': 3}

Начало оптимизации гиперпараметров для Strategy4 на Train...
100%|██████████| 50/50 [00:02<00:00, 18.89trial/s, best loss: -1.22920153495918]
Оптимальные гиперпараметры для Strategy4 на Train: {'bb_period': np.float64(38.0), 'bb_std': np.float64(2.733303560929396), 'ema_period': np.float64(19.0), 'ma_period': np.float64(11.0), 'macd_fast': np.float64(11.0), 'macd_signal': np.float64(14.0), 'macd_slow': np.float64(27.0), 'rsi_period': np.float64(7.0), 'sma': np.float64(13.0), 'stoch_d': np.float64(5.0), 'stoch_k': np.float64(19.0), 'stoch_slow': np.float64(7.0)}

2. Набор данных Test. Начало бэктестирования Strategy4 с оптимизированными гиперпараметрами на наборе Train: {'bb_period': np.float64(38.0), 'bb_std': np.float64(2.733303560929396), 'ema_period': np.float64(19.0), 'ma_period': np.float64(11.0), 'macd_fast': np.float64(11.0), 'macd_signal': np.float64(14.0), 'macd_slow': np.float64(27.0), 'rsi_period': np.float64(7.0), 'sma': np.float64(13.0), 'stoch_d': np.float64(5.0), 'stoch_k': np.float64(19.0), 'stoch_slow': np.float64(7.0)}

Объединенный набор данных Train и Test: 2022-01-01 - 2025-03-13

Начало оптимизации гиперпараметров для Strategy4 на объединенном наборе Train и Test...
100%|██████████| 50/50 [00:02<00:00, 18.93trial/s, best loss: -1.2189164201619676]
Оптимальные гиперпараметры для Strategy4 на объединенном наборе Train и Test: {'bb_period': np.float64(28.0), 'bb_std': np.float64(2.993069944124646), 'ema_period': np.float64(20.0), 'ma_period': np.float64(12.0), 'macd_fast': np.float64(20.0), 'macd_signal': np.float64(8.0), 'macd_slow': np.float64(26.0), 'rsi_period': np.float64(7.0), 'sma': np.float64(17.0), 'stoch_d': np.float64(7.0), 'stoch_k': np.float64(20.0), 'stoch_slow': np.float64(7.0)}

3. Набор данных Test.  Начало бэктестирования Strategy4 с оптимизированными гиперпараметрами на наборе Test: {'bb_period': np.float64(28.0), 'bb_std': np.float64(2.993069944124646), 'ema_period': np.float64(20.0), 'ma_period': np.float64(12.0), 'macd_fast': np.float64(20.0), 'macd_signal': np.float64(8.0), 'macd_slow': np.float64(26.0), 'rsi_period': np.float64(7.0), 'sma': np.float64(17.0), 'stoch_d': np.float64(7.0), 'stoch_k': np.float64(20.0), 'stoch_slow': np.float64(7.0)} с использованием ML

'Создаем объект класса Backtest'

'Запускаем бэктест'

Backtest.run:   0%|          | 0/223 [00:00<?, ?bar/s]

'Разделяем признаки и метки'

'RobustScaler'

Feature Importance:
 Adx                10.211910
Adosc               8.297655
Mfi                 7.830437
Slowk               7.636976
Cci                 7.624974
Slowd               7.606454
Rsi                 6.070659
Linearreg_angle     5.832047
Obv                 5.788295
Macd                5.196708
Atr14               5.142330
Engulfing           4.635103
Bb_lower            3.805410
Sma                 3.100561
Bb_upper            3.065317
Bb_middle           3.062456
Ma_period           2.386008
Sar                 2.050528
Doji                0.246232
Hammer              0.231650
Morningstar         0.178289
dtype: float64

'Повторяем все тоже самое с данными для теста'

'Для предсказания используем данные в столбацах ниже'

'Выводим предсказание'

[1 1 1 1 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 1 1 0 1 1 0 0 0 1 0 0 0 1 1 1 1 0 0
 1 1 1 1 0 0 1 1 1 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1]
0.725
[[ 7  6]
 [16 51]]
              precision    recall  f1-score   support

           0       0.30      0.54      0.39        13
           1       0.89      0.76      0.82        67

    accuracy                           0.72        80
   macro avg       0.60      0.65      0.61        80
weighted avg       0.80      0.72      0.75        80

Backtest.run:   0%|          | 0/79 [00:00<?, ?bar/s]

Start                     2024-07-04 00:00:00
End                       2025-03-12 00:00:00
Duration                    251 days 00:00:00
Exposure Time [%]                        62.5
Equity Final [$]               1207111.378055
Equity Peak [$]                1304934.751586
Commissions [$]                 112082.594602
Return [%]                          20.711138
Buy & Hold Return [%]               46.938811
Return (Ann.) [%]                  136.032744
Volatility (Ann.) [%]              155.263094
CAGR [%]                            31.484821
Sharpe Ratio                         0.876143
Sortino Ratio                        3.805732
Calmar Ratio                         6.527068
Alpha [%]                           26.656366
Beta                                -0.126659
Max. Drawdown [%]                  -20.841324
Avg. Drawdown [%]                   -7.452502
Max. Drawdown Duration      180 days 00:00:00
Avg. Drawdown Duration       55 days 00:00:00
# Trades                                   26
Win Rate [%]                             50.0
Best Trade [%]                      16.508419
Worst Trade [%]                     -8.651161
Avg. Trade [%]                       0.772041
Max. Trade Duration          13 days 00:00:00
dtype: object

'Выводим график :'

'Выводим Buy&Hold и GoldenCross :'

                                   Buy&Hold          GoldenCross
Start                   2022-02-14 00:00:00  2024-07-04 00:00:00
End                     2025-12-31 00:00:00  2025-03-12 00:00:00
Duration                 1416 days 00:00:00    251 days 00:00:00
Exposure Time [%]                 99.107143                 62.5
Equity Final [$]              147837.260137       1207111.378055
Equity Peak [$]              1210181.614305       1304934.751586
Commissions [$]               189068.941238        112082.594602
Return [%]                       -85.216274            20.711138
Buy & Hold Return [%]            105.482886            46.938811
Return (Ann.) [%]                -88.358555           136.032744
Volatility (Ann.) [%]             16.636729           155.263094
CAGR [%]                         -28.837749            31.484821
Sharpe Ratio                      -5.311053             0.876143
Sortino Ratio                     -1.101513             3.805732
Calmar Ratio                      -0.984677             6.527068
Alpha [%]                        -70.003609            26.656366
Beta                              -0.144219            -0.126659
Max. Drawdown [%]                -89.733555           -20.841324
Avg. Drawdown [%]                -43.128697            -7.452502
Max. Drawdown Duration   1287 days 00:00:00    180 days 00:00:00
Avg. Drawdown Duration    470 days 00:00:00     55 days 00:00:00
# Trades                                110                   26
Win Rate [%]                      40.909091                 50.0
Best Trade [%]                     53.14368            16.508419
Worst Trade [%]                  -51.646632            -8.651161
Avg. Trade [%]                    -1.926406             0.772041
Max. Trade Duration        89 days 00:00:00     13 days 00:00:00

risk_adjusted_return = -72.09
ROC AUC Score: 0.7256
Пригодна для некритичных задач; требует дополнительной проверки

4. Набор данных Test. Модель TSMixer. Начало бэктестирования Strategy4 с оптимизированными гиперпараметрами на наборе Test: {'bb_period': np.float64(28.0), 'bb_std': np.float64(2.993069944124646), 'ema_period': np.float64(20.0), 'ma_period': np.float64(12.0), 'macd_fast': np.float64(20.0), 'macd_signal': np.float64(8.0), 'macd_slow': np.float64(26.0), 'rsi_period': np.float64(7.0), 'sma': np.float64(17.0), 'stoch_d': np.float64(7.0), 'stoch_k': np.float64(20.0), 'stoch_slow': np.float64(7.0)} с использованием ML
======================================================================
РАСПРЕДЕЛЕНИЕ КЛАССОВ
======================================================================
target
0    736
1    724
Name: count, dtype: int64

Баланс классов (доля класса 1): 0.496
Всего примеров: 1460
======================================================================
Размер окон признаков: (1332, 128, 24)
Размер таргетов: (1332,)
Размер индексов: (1332,)
======================================================================
РАЗМЕРЫ ВЫБОРОК
======================================================================
Train: X=(1332, 128, 24), y=(1332,)
Test:  X=(292, 128, 24), y=(292,)

Распределение классов в test:
  Класс 0 (падение): 147 (50.3%)
  Класс 1 (рост):    145 (49.7%)
======================================================================
Train batches: 21
Test batches:  5

Пример батча:
  X: torch.Size([64, 128, 24])  (batch, lookback, num_features)
  y: torch.Size([64])  (batch,)

Пример батча test:
  X: torch.Size([64, 128, 24])  (batch, lookback, num_features)
  y: torch.Size([64])  (batch,)
======================================================================
======================================================================
ИНФОРМАЦИЯ О МОДЕЛИ
======================================================================
Всего параметров:      305,113
Обучаемых параметров:  305,113
Устройство:            cpu
======================================================================
Установлен новый Optimizer: AdamW с weight decay для регуляризации
Веса классов для Loss: 0 (Down): 0.9918, 1 (Up): 1.0083
✓ Optimizer, loss function и evaluation function настроены
======================================================================
НАЧАЛО ОБУЧЕНИЯ
======================================================================
Epoch  1/50 | Train Loss: 0.6965 | Train Acc: 0.4910 | Test Acc: 0.5034 | [Model Saved! Best Acc: 0.5034]
Epoch  2/50 | Train Loss: 0.6953 | Train Acc: 0.4992 | Test Acc: 0.5034
Epoch  3/50 | Train Loss: 0.6952 | Train Acc: 0.4985 | Test Acc: 0.5034
Epoch  4/50 | Train Loss: 0.6935 | Train Acc: 0.4962 | Test Acc: 0.5034
Epoch  5/50 | Train Loss: 0.6936 | Train Acc: 0.5113 | Test Acc: 0.5034
Epoch  6/50 | Train Loss: 0.6919 | Train Acc: 0.5210 | Test Acc: 0.5342 | [Model Saved! Best Acc: 0.5342]
Epoch  7/50 | Train Loss: 0.6928 | Train Acc: 0.5038 | Test Acc: 0.5137
Epoch  8/50 | Train Loss: 0.6885 | Train Acc: 0.5503 | Test Acc: 0.5240
Epoch  9/50 | Train Loss: 0.6892 | Train Acc: 0.5360 | Test Acc: 0.5274
Epoch 10/50 | Train Loss: 0.6873 | Train Acc: 0.5511 | Test Acc: 0.5479 | [Model Saved! Best Acc: 0.5479]
Epoch 11/50 | Train Loss: 0.6787 | Train Acc: 0.5818 | Test Acc: 0.6233 | [Model Saved! Best Acc: 0.6233]
Epoch 12/50 | Train Loss: 0.6737 | Train Acc: 0.5983 | Test Acc: 0.6301 | [Model Saved! Best Acc: 0.6301]
Epoch 13/50 | Train Loss: 0.6672 | Train Acc: 0.6044 | Test Acc: 0.6610 | [Model Saved! Best Acc: 0.6610]
Epoch 14/50 | Train Loss: 0.6519 | Train Acc: 0.6306 | Test Acc: 0.6849 | [Model Saved! Best Acc: 0.6849]
Epoch 15/50 | Train Loss: 0.6492 | Train Acc: 0.6201 | Test Acc: 0.7021 | [Model Saved! Best Acc: 0.7021]
Epoch 16/50 | Train Loss: 0.6353 | Train Acc: 0.6554 | Test Acc: 0.7123 | [Model Saved! Best Acc: 0.7123]
Epoch 17/50 | Train Loss: 0.6308 | Train Acc: 0.6517 | Test Acc: 0.7192 | [Model Saved! Best Acc: 0.7192]
Epoch 18/50 | Train Loss: 0.6197 | Train Acc: 0.6584 | Test Acc: 0.7226 | [Model Saved! Best Acc: 0.7226]
Epoch 19/50 | Train Loss: 0.6243 | Train Acc: 0.6607 | Test Acc: 0.7329 | [Model Saved! Best Acc: 0.7329]
Epoch 20/50 | Train Loss: 0.6057 | Train Acc: 0.6659 | Test Acc: 0.7363 | [Model Saved! Best Acc: 0.7363]
Epoch 21/50 | Train Loss: 0.5995 | Train Acc: 0.6817 | Test Acc: 0.7055
Epoch 22/50 | Train Loss: 0.5986 | Train Acc: 0.6794 | Test Acc: 0.7055
Epoch 23/50 | Train Loss: 0.5789 | Train Acc: 0.6952 | Test Acc: 0.7397 | [Model Saved! Best Acc: 0.7397]
Epoch 24/50 | Train Loss: 0.5639 | Train Acc: 0.7200 | Test Acc: 0.7466 | [Model Saved! Best Acc: 0.7466]
Epoch 25/50 | Train Loss: 0.5512 | Train Acc: 0.7132 | Test Acc: 0.7329
Epoch 26/50 | Train Loss: 0.5490 | Train Acc: 0.7192 | Test Acc: 0.7466
Epoch 27/50 | Train Loss: 0.5237 | Train Acc: 0.7470 | Test Acc: 0.7534 | [Model Saved! Best Acc: 0.7534]
Epoch 28/50 | Train Loss: 0.5132 | Train Acc: 0.7440 | Test Acc: 0.7774 | [Model Saved! Best Acc: 0.7774]
Epoch 29/50 | Train Loss: 0.5143 | Train Acc: 0.7485 | Test Acc: 0.7637
Epoch 30/50 | Train Loss: 0.4861 | Train Acc: 0.7673 | Test Acc: 0.7945 | [Model Saved! Best Acc: 0.7945]
Epoch 31/50 | Train Loss: 0.4913 | Train Acc: 0.7560 | Test Acc: 0.7808
Epoch 32/50 | Train Loss: 0.4766 | Train Acc: 0.7665 | Test Acc: 0.7979 | [Model Saved! Best Acc: 0.7979]
Epoch 33/50 | Train Loss: 0.4506 | Train Acc: 0.7763 | Test Acc: 0.8048 | [Model Saved! Best Acc: 0.8048]
Epoch 34/50 | Train Loss: 0.4630 | Train Acc: 0.7845 | Test Acc: 0.7945
Epoch 35/50 | Train Loss: 0.4122 | Train Acc: 0.8146 | Test Acc: 0.8151 | [Model Saved! Best Acc: 0.8151]
Epoch 36/50 | Train Loss: 0.3954 | Train Acc: 0.8258 | Test Acc: 0.8185 | [Model Saved! Best Acc: 0.8185]
Epoch 37/50 | Train Loss: 0.4026 | Train Acc: 0.8221 | Test Acc: 0.8082
Epoch 38/50 | Train Loss: 0.3752 | Train Acc: 0.8266 | Test Acc: 0.8116
Epoch 39/50 | Train Loss: 0.3769 | Train Acc: 0.8311 | Test Acc: 0.7979
Epoch 40/50 | Train Loss: 0.3717 | Train Acc: 0.8303 | Test Acc: 0.8014
Epoch 41/50 | Train Loss: 0.3324 | Train Acc: 0.8423 | Test Acc: 0.8082
Epoch 42/50 | Train Loss: 0.3264 | Train Acc: 0.8566 | Test Acc: 0.8082
Epoch 43/50 | Train Loss: 0.2994 | Train Acc: 0.8709 | Test Acc: 0.8185
Epoch 44/50 | Train Loss: 0.3082 | Train Acc: 0.8716 | Test Acc: 0.8253 | [Model Saved! Best Acc: 0.8253]
Epoch 45/50 | Train Loss: 0.2990 | Train Acc: 0.8739 | Test Acc: 0.8185
Epoch 46/50 | Train Loss: 0.2864 | Train Acc: 0.8851 | Test Acc: 0.8253
Epoch 47/50 | Train Loss: 0.2891 | Train Acc: 0.8769 | Test Acc: 0.8219
Epoch 48/50 | Train Loss: 0.2674 | Train Acc: 0.8844 | Test Acc: 0.8356 | [Model Saved! Best Acc: 0.8356]
Epoch 49/50 | Train Loss: 0.2463 | Train Acc: 0.8971 | Test Acc: 0.8253
Epoch 50/50 | Train Loss: 0.2640 | Train Acc: 0.8986 | Test Acc: 0.8288
======================================================================
ОБУЧЕНИЕ ЗАВЕРШЕНО. Лучшая точность: 0.8356
======================================================================
======================================================================
ЗАГРУЖАЕМ ЛУЧШИЕ ВЕСА ПЕРЕД ФИНАЛЬНОЙ ОЦЕНКОЙ
Загружены лучшие веса из tsmixer_full_BTC-USD.pt
======================================================================

======================================================================
ФИНАЛЬНЫЕ РЕЗУЛЬТАТЫ КЛАССИФИКАЦИИ
======================================================================
Test Accuracy: 0.8356 (83.56%)
Baseline (majority class): 0.5034 (50.34%)
Улучшение над baseline: 33.22%

----------------------------------------------------------------------
CLASSIFICATION REPORT
----------------------------------------------------------------------
              precision    recall  f1-score   support

    Down (0)     0.8194    0.8639    0.8411       147
      Up (1)     0.8540    0.8069    0.8298       145

    accuracy                         0.8356       292
   macro avg     0.8367    0.8354    0.8354       292
weighted avg     0.8366    0.8356    0.8355       292

----------------------------------------------------------------------
CONFUSION MATRIX
----------------------------------------------------------------------

              Predicted
                0      1
Actual 0      127     20
       1       28    117

----------------------------------------------------------------------
ИНТЕРПРЕТАЦИЯ
----------------------------------------------------------------------
True Positives (правильно предсказан рост):     117
True Negatives (правильно предсказано падение): 127
False Positives (ложный сигнал на рост):        20
False Negatives (пропущенный рост):             28

======================================================================
BACKTEST ТОРГОВЫХ СТРАТЕГИЙ
======================================================================
Buy & Hold:              -23.51%
Strategy (Long only):      3.71%
Strategy (Long/Short):    18.95%
======================================================================

Sharpe Ratio (годовой):
  Buy & Hold:           -0.211
  Strategy (Long only): 0.259
  Strategy (Long/Short):0.547
======================================================================

/tmp/ipython-input-577606817.py:532: UserWarning: Data index is not sorted in ascending order. Sorting.
  bt = Backtest(test_datadf_neu_backtest, ChronosNextDayDirection, cash=1000000, commission=.002, exclusive_orders=True, finalize_trades=True)

Backtest.run:   0%|          | 0/291 [00:00<?, ?bar/s]

Start                     2024-05-26 00:00:00
End                       2025-12-31 00:00:00
Duration                    584 days 00:00:00
Exposure Time [%]                   69.520548
Equity Final [$]               4987479.115461
Equity Peak [$]                4987479.115461
Commissions [$]                 501339.833758
Return [%]                         398.747912
Buy & Hold Return [%]               27.716379
Return (Ann.) [%]                  645.334737
Volatility (Ann.) [%]              253.004994
CAGR [%]                           173.008194
Sharpe Ratio                          2.55068
Sortino Ratio                       47.961986
Calmar Ratio                        41.259733
Alpha [%]                          385.557176
Beta                                 0.475918
Max. Drawdown [%]                  -15.640788
Avg. Drawdown [%]                   -0.725566
Max. Drawdown Duration       94 days 00:00:00
Avg. Drawdown Duration        6 days 00:00:00
# Trades                                   66
Win Rate [%]                        77.272727
Best Trade [%]                      27.438503
Worst Trade [%]                     -7.473981
Avg. Trade [%]                       2.515072
Max. Trade Duration         295 days 00:00:00
dtype: object

'risk_adjusted_return = -1328573.24'

Финальный ROC AUC на тесте: 0.9154

5. Набор данных Test. Модель Chronos. Начало бэктестирования Strategy4 с оптимизированными гиперпараметрами на наборе Test: {'bb_period': np.float64(28.0), 'bb_std': np.float64(2.993069944124646), 'ema_period': np.float64(20.0), 'ma_period': np.float64(12.0), 'macd_fast': np.float64(20.0), 'macd_signal': np.float64(8.0), 'macd_slow': np.float64(26.0), 'rsi_period': np.float64(7.0), 'sma': np.float64(17.0), 'stoch_d': np.float64(7.0), 'stoch_k': np.float64(20.0), 'stoch_slow': np.float64(7.0)} с использованием ML
Обрабатываем данные для модели Chronos... ->
==================================================
Выставляем параметры для модели Chronos... ->
Pretrain BaseChronosPipeline... ->
==================================================
==================================================
ChronosNextDayDirection... ->

Backtest.run:   0%|          | 0/1459 [00:00<?, ?bar/s]

======================================================================
ROC AUC (Train): 0.4930
======================================================================
Best threshold: 0.01 Sharpe: 0.007274310448064092
==================================================
ChronosStrategy... ->

/tmp/ipython-input-2513420128.py:279: UserWarning: Data index is not sorted in ascending order. Sorting.
  bt_chronos = Backtest(

Backtest.run:   0%|          | 0/420 [00:00<?, ?bar/s]

==================================================
BuyHold... ->

/tmp/ipython-input-2513420128.py:292: UserWarning: Data index is not sorted in ascending order. Sorting.
  bt_bh = Backtest(

Backtest.run:   0%|          | 0/420 [00:00<?, ?bar/s]

==================================================
TemaGoldenCrossStrategy... ->

/tmp/ipython-input-2513420128.py:323: UserWarning: Data index is not sorted in ascending order. Sorting.
  btchronos = Backtest(test_datadf_neu, TemaGoldenCrossStrategy, cash=1000000, commission=.002, exclusive_orders=True, finalize_trades=True)

Backtest.run:   0%|          | 0/292 [00:00<?, ?bar/s]

'GoldenCrossStrategy:  '

,Buy&Hold,GoldenCross
Start,2024-05-26 00:00:00,2022-01-01 00:00:00
End,2025-12-31 00:00:00,2025-12-30 00:00:00
Duration,584 days 00:00:00,1459 days 00:00:00
Exposure Time [%],99.524941,83.424658
Equity Final [$],1262079.0025,269449.731686
Equity Peak [$],1773068.624344,1089108.44102
Commissions [$],4419.09125,393184.685307
Return [%],26.2079,-73.055027
Buy & Hold Return [%],27.716379,85.439387
Return (Ann.) [%],22.360249,-27.952413
Volatility (Ann.) [%],74.823512,28.706024
CAGR [%],15.658908,-27.968601
Sharpe Ratio,0.29884,-0.973747
Sortino Ratio,0.715375,-1.012146
Calmar Ratio,0.70613,-0.363195
Alpha [%],-0.863353,-84.884134
Beta,0.976724,0.13845
Max. Drawdown [%],-31.665915,-76.962627
Avg. Drawdown [%],-7.761857,-25.518005
Max. Drawdown Duration,216 days 00:00:00,1299 days 00:00:00
Avg. Drawdown Duration,34 days 00:00:00,333 days 00:00:00
# Trades,1,246
Win Rate [%],100.0,43.902439
Best Trade [%],26.976077,28.740516
Worst Trade [%],26.976077,-22.055621
Avg. Trade [%],26.976077,-0.530117
Max. Trade Duration,582 days 00:00:00,26 days 00:00:00
Avg. Trade Duration,582 days 00:00:00,4 days 00:00:00
Profit Factor,NaN,0.788681
Expectancy [%],26.976077,-0.398343
SQN,NaN,-1.725531
Kelly Criterion,NaN,-0.223414
_strategy,BuyHold,ChronosNextDayDirection
_equity_curve,Equity DrawdownPct Drawdown...,Equity DrawdownPct Drawdo...
_trades,Size EntryBar ExitBar EntryPrice E...,Size EntryBar ExitBar EntryPrice ...

'risk_adjusted_return = -69.25'

6. Набор данных Valid. Начало бэктестирования Strategy4 с оптимизированными гиперпараметрами на объединенном наборе Train и Test: {'bb_period': np.float64(28.0), 'bb_std': np.float64(2.993069944124646), 'ema_period': np.float64(20.0), 'ma_period': np.float64(12.0), 'macd_fast': np.float64(20.0), 'macd_signal': np.float64(8.0), 'macd_slow': np.float64(26.0), 'rsi_period': np.float64(7.0), 'sma': np.float64(17.0), 'stoch_d': np.float64(7.0), 'stoch_k': np.float64(20.0), 'stoch_slow': np.float64(7.0)}
======================================================================
РАСПРЕДЕЛЕНИЕ КЛАССОВ
======================================================================
target
0    736
1    724
Name: count, dtype: int64

Баланс классов (доля класса 1): 0.496
Всего примеров: 1460
======================================================================
Размер окон признаков: (1332, 128, 24)
Размер таргетов: (1332,)
Размер индексов: (1332,)
======================================================================
РАЗМЕРЫ ВЫБОРОК
======================================================================
Train: X=(1332, 128, 24), y=(1332,)
Test:  X=(551, 128, 24), y=(551,)

Распределение классов в test:
  Класс 0 (падение): 374 (67.9%)
  Класс 1 (рост):    177 (32.1%)
======================================================================
Train batches: 21
Test batches:  9

Пример батча:
  X: torch.Size([64, 128, 24])  (batch, lookback, num_features)
  y: torch.Size([64])  (batch,)

Пример батча test:
  X: torch.Size([64, 128, 24])  (batch, lookback, num_features)
  y: torch.Size([64])  (batch,)
======================================================================
Load tsmixer_full_BTC-USD.pt ...
Модель tsmixer_full_BTC-USD.pt загружена.
Загружены лучшие веса из tsmixer_full_BTC-USD.pt
======================================================================
ИНФОРМАЦИЯ О МОДЕЛИ
======================================================================
Всего параметров:      305,113
Обучаемых параметров:  305,113
Устройство:            cpu
======================================================================
Веса классов для Loss: 0 (Down): 0.9918, 1 (Up): 1.0083
✓ Optimizer, loss function и evaluation function настроены
======================================================================
НАЧАЛО ОБУЧЕНИЯ
======================================================================
======================================================================
ОБУЧЕНИЕ ЗАВЕРШЕНО. Лучшая точность: 0.0000
======================================================================
======================================================================
ЗАГРУЖАЕМ ЛУЧШИЕ ВЕСА ПЕРЕД ФИНАЛЬНОЙ ОЦЕНКОЙ
Загружены лучшие веса из tsmixer_full_BTC-USD.pt
======================================================================

======================================================================
ФИНАЛЬНЫЕ РЕЗУЛЬТАТЫ КЛАССИФИКАЦИИ
======================================================================
Test Accuracy: 0.5735 (57.35%)
Baseline (majority class): 0.6788 (67.88%)
Улучшение над baseline: -10.53%

----------------------------------------------------------------------
CLASSIFICATION REPORT
----------------------------------------------------------------------
              precision    recall  f1-score   support

    Down (0)     0.7372    0.5775    0.6477       374
      Up (1)     0.3876    0.5650    0.4598       177

    accuracy                         0.5735       551
   macro avg     0.5624    0.5713    0.5537       551
weighted avg     0.6249    0.5735    0.5873       551

----------------------------------------------------------------------
CONFUSION MATRIX
----------------------------------------------------------------------

              Predicted
                0      1
Actual 0      216    158
       1       77    100

----------------------------------------------------------------------
ИНТЕРПРЕТАЦИЯ
----------------------------------------------------------------------
True Positives (правильно предсказан рост):     100
True Negatives (правильно предсказано падение): 216
False Positives (ложный сигнал на рост):        158
False Negatives (пропущенный рост):             77

======================================================================
BACKTEST ТОРГОВЫХ СТРАТЕГИЙ
======================================================================
Buy & Hold:               22.58%
Strategy (Long only):    -33.23%
Strategy (Long/Short):   -70.20%
======================================================================

Sharpe Ratio (годовой):
  Buy & Hold:           0.433
  Strategy (Long only): -0.429
  Strategy (Long/Short):-1.053
======================================================================

/tmp/ipython-input-577606817.py:532: UserWarning: Data index is not sorted in ascending order. Sorting.
  bt = Backtest(test_datadf_neu_backtest, ChronosNextDayDirection, cash=1000000, commission=.002, exclusive_orders=True, finalize_trades=True)

Backtest.run:   0%|          | 0/550 [00:00<?, ?bar/s]

Start                     2025-03-14 00:00:00
End                       2025-12-31 00:00:00
Duration                    292 days 00:00:00
Exposure Time [%]                   66.787659
Equity Final [$]               1007237.439203
Equity Peak [$]                1246819.596578
Commissions [$]                 454885.209234
Return [%]                           0.723744
Buy & Hold Return [%]                4.215511
Return (Ann.) [%]                    0.902393
Volatility (Ann.) [%]               22.804501
CAGR [%]                             0.905497
Sharpe Ratio                         0.039571
Sortino Ratio                        0.057162
Calmar Ratio                         0.045011
Alpha [%]                           -1.080922
Beta                                 0.428101
Max. Drawdown [%]                  -20.048396
Avg. Drawdown [%]                   -5.307239
Max. Drawdown Duration      120 days 00:00:00
Avg. Drawdown Duration       36 days 00:00:00
# Trades                                  110
Win Rate [%]                        46.363636
Best Trade [%]                       4.850551
Worst Trade [%]                     -5.679805
Avg. Trade [%]                        0.00124
Max. Trade Duration           6 days 00:00:00
dtype: object

'risk_adjusted_return = -0.00'

Финальный ROC AUC на тесте: 0.5861
====================================================================================================

/usr/local/lib/python3.12/dist-packages/pandas/io/formats/style.py:3811: RuntimeWarning: invalid value encountered in scalar multiply
  norm = _matplotlib.colors.Normalize(smin - (rng * low), smax + (rng * high))

Определение стратегии с лучшими показателями инструменту и по набору данных
Лучшая стратегия: Strategy4
Лучший инструмент: BTC-USD
Лучший набор данных: test_neu
Доходность с корректировкой риска (Risk-Adjusted Returns): 2931.42

Оптимальные гиперпараметры:
bb_period: 38.0
bb_std: 2.733303560929396
ema_period: 19.0
ma_period: 11.0
macd_fast: 11.0
macd_signal: 14.0
macd_slow: 27.0
rsi_period: 7.0
sma: 13.0
stoch_d: 5.0
stoch_k: 19.0
stoch_slow: 7.0

Метрики производительности для лучшей стратегии:
Конечный капитал (final_equity) : 4987479.12
Количество сделок (n_trades): 66
Доходность (returns): 398.75%
Максимальная просадка (max_drawdown): 15.64%
Процент прибыльных сделок (win_rate): 77.27%
Коэффициент Шарпа (sharpe_ratio): 2.55
Коэффициент Сортино (sortino_ratio): 47.96
Фактор прибыли (profit_factor): 398.75

'\nЗагрузка данных с Yahoo Finance BTC-USD'

[*********************100%***********************]  1 of 1 completed

======================================================================
РАСПРЕДЕЛЕНИЕ КЛАССОВ
======================================================================
target
0    445
1    430
Name: count, dtype: int64

Баланс классов (доля класса 1): 0.491
Всего примеров: 875
======================================================================
Размер окон признаков: (747, 128, 24)
Размер таргетов: (747,)
Размер индексов: (747,)
======================================================================
РАЗМЕРЫ ВЫБОРОК
======================================================================
Train: X=(747, 128, 24), y=(747,)
Test:  X=(292, 128, 24), y=(292,)

Распределение классов в test:
  Класс 0 (падение): 147 (50.3%)
  Класс 1 (рост):    145 (49.7%)
======================================================================
Train batches: 12
Test batches:  5

Пример батча:
  X: torch.Size([64, 128, 24])  (batch, lookback, num_features)
  y: torch.Size([64])  (batch,)

Пример батча test:
  X: torch.Size([64, 128, 24])  (batch, lookback, num_features)
  y: torch.Size([64])  (batch,)
======================================================================
Load tsmixer_full_BTC-USD.pt ...

Модель tsmixer_full_BTC-USD.pt загружена.
Загружены лучшие веса из tsmixer_full_BTC-USD.pt
======================================================================
ИНФОРМАЦИЯ О МОДЕЛИ
======================================================================
Всего параметров:      305,113
Обучаемых параметров:  305,113
Устройство:            cpu
======================================================================
Веса классов для Loss: 0 (Down): 0.9831, 1 (Up): 1.0174
✓ Optimizer, loss function и evaluation function настроены
======================================================================
НАЧАЛО ОБУЧЕНИЯ
======================================================================
======================================================================
ОБУЧЕНИЕ ЗАВЕРШЕНО. Лучшая точность: 0.0000
======================================================================
======================================================================
ЗАГРУЖАЕМ ЛУЧШИЕ ВЕСА ПЕРЕД ФИНАЛЬНОЙ ОЦЕНКОЙ
Загружены лучшие веса из tsmixer_full_BTC-USD.pt
======================================================================

======================================================================
ФИНАЛЬНЫЕ РЕЗУЛЬТАТЫ КЛАССИФИКАЦИИ
======================================================================
Test Accuracy: 0.9623 (96.23%)
Baseline (majority class): 0.5034 (50.34%)
Улучшение над baseline: 45.89%

----------------------------------------------------------------------
CLASSIFICATION REPORT
----------------------------------------------------------------------
              precision    recall  f1-score   support

    Down (0)     0.9658    0.9592    0.9625       147
      Up (1)     0.9589    0.9655    0.9622       145

    accuracy                         0.9623       292
   macro avg     0.9623    0.9624    0.9623       292
weighted avg     0.9624    0.9623    0.9623       292

----------------------------------------------------------------------
CONFUSION MATRIX
----------------------------------------------------------------------

              Predicted
                0      1
Actual 0      141      6
       1        5    140

----------------------------------------------------------------------
ИНТЕРПРЕТАЦИЯ
----------------------------------------------------------------------
True Positives (правильно предсказан рост):     140
True Negatives (правильно предсказано падение): 141
False Positives (ложный сигнал на рост):        6
False Negatives (пропущенный рост):             5

======================================================================
BACKTEST ТОРГОВЫХ СТРАТЕГИЙ
======================================================================
Buy & Hold:              -23.51%
Strategy (Long only):    -30.85%
Strategy (Long/Short):   -46.10%
======================================================================

Sharpe Ratio (годовой):
  Buy & Hold:           -0.211
  Strategy (Long only): -0.739
  Strategy (Long/Short):-0.819
======================================================================

Backtest.run:   0%|          | 0/291 [00:00<?, ?bar/s]

Start                     2024-05-25 00:00:00
End                       2025-03-12 00:00:00
Duration                    291 days 00:00:00
Exposure Time [%]                   74.657534
Equity Final [$]              10865120.754766
Equity Peak [$]               10887462.894828
Commissions [$]                1141685.721797
Return [%]                         986.512075
Buy & Hold Return [%]               20.870883
Return (Ann.) [%]                 1872.618931
Volatility (Ann.) [%]              671.890174
CAGR [%]                          1892.936756
Sharpe Ratio                         2.787091
Sortino Ratio                      421.254003
Calmar Ratio                       798.810444
Alpha [%]                          975.361555
Beta                                 0.534262
Max. Drawdown [%]                   -2.344259
Avg. Drawdown [%]                   -0.333495
Max. Drawdown Duration        9 days 00:00:00
Avg. Drawdown Duration        4 days 00:00:00
# Trades                                   73
Win Rate [%]                        90.410959
Best Trade [%]                      27.438503
Worst Trade [%]                     -1.600423
Avg. Trade [%]                         3.3674
Max. Trade Duration           7 days 00:00:00
dtype: object

'risk_adjusted_return = -849995983.95'

Финальный ROC AUC на тесте: 0.9921